souffle: Explain.h File Reference
Explain.h File Reference
#include "ExplainProvenanceSLD.h"
#include <csignal>
#include <iostream>
#include <regex>
#include <string>
#include <ncurses.h>
#include "SouffleInterface.h"
#include "WriteStreamCSV.h"
Data Structures
class souffle::Explain
Namespaces
souffle
Macros
#define MAX_TREE_HEIGHT 500
#define MAX_TREE_WIDTH 500
Functions
Explain (ExplainProvenance &p, bool ncurses, int d=4)
void explain ()
void explain (SouffleProgram &prog, bool sld=true, bool ncurses=false)
void initialiseWindow ()
void printStr (const std::string &s)
void scrollTree (int maxx, int maxy)
~Explain ()
Macro Definition Documentation
#define MAX_TREE_HEIGHT 500
Definition at line 30 of file Explain.h.
Referenced by initialiseWindow(), and scrollTree().
#define MAX_TREE_WIDTH 500
Definition at line 31 of file Explain.h.
Referenced by initialiseWindow(), and scrollTree().
Function Documentation
Explain (ExplainProvenance & p, bool ncurses, int d = 4)
Definition at line 185 of file Explain.h.
Referenced by explain().
             : prov(p), ncurses(ncurses), depthLimit(d), output(nullptr), json(false) {}
void explain ()
Definition at line 191 of file Explain.h.
References souffle::Explain::depthLimit, e, souffle::ExplainProvenance::explain(), souffle::ExplainProvenance::explainSubproof(), souffle::ExplainProvenance::getRelationOutput(), souffle::ExplainProvenance::getRule(), initialiseWindow(), souffle::Explain::json, souffle::Explain::maxx, souffle::Explain::maxy, souffle::ExplainProvenance::measureRelation(), souffle::Explain::ncurses, souffle::Explain::output, souffle::Explain::parseTuple(), printStr(), souffle::Explain::prov, souffle::Explain::queryWindow, scrollTree(), souffle::split(), and souffle::Explain::treePad.
Referenced by souffle::main().
                    {
         if (ncurses && !output) {
             initialiseWindow();
             std::signal(SIGWINCH, nullptr);
         }
         // process commands
         char buf[100];
         std::string line;
         while (true) {
             if (ncurses && !output) {
                 // reset command line on each loop
                 werase(queryWindow);
                 wrefresh(queryWindow);
                 mvwprintw(queryWindow, 1, 0, "Enter command > ");
                 curs_set(1);
                 echo();
                 // get next command
                 wgetnstr(queryWindow, buf, 100);
                 noecho();
                 curs_set(0);
                 line = buf;
                 // reset tree display on each loop
                 werase(treePad);
                 prefresh(treePad, 0, 0, 0, 0, maxy - 3, maxx - 1);
             } else {
                 std::cout << "Enter command > ";
                 if (!getline(std::cin, line)) {
                     printStr("Exiting explain\n");
                     break;
                 }
             }
             std::vector<std::string> command = split(line, ' ', 1);
             if (command.empty()) {
                 continue;
             }
             if (command[0] == "setdepth") {
                 try {
                     depthLimit = std::stoi(command[1]);
                 } catch (std::exception& e) {
                     printStr("Usage: setdepth <depth>\n");
                     continue;
                 }
                 printStr("Depth is now " + std::to_string(depthLimit) + "\n");
             } else if (command[0] == "explain") {
                 std::pair<std::string, std::vector<std::string>> query;
                 if (command.size() == 2) {
                     query = parseTuple(command[1]);
                 } else {
                     printStr("Usage: explain relation_name(\"<string element1>\", <number element2>, ...)\n");
                     continue;
                 }
                 std::unique_ptr<TreeNode> t = prov.explain(query.first, query.second, depthLimit);
                 printTree(std::move(t));
             } else if (command[0] == "subproof") {
                 std::pair<std::string, std::vector<std::string>> query;
                 int label = -1;
                 if (command.size() > 1) {
                     query = parseTuple(command[1]);
                     label = std::stoi(query.second[0]);
                 } else {
                     printStr("Usage: subproof relation_name(<label>)\n");
                     continue;
                 }
                 std::unique_ptr<TreeNode> t = prov.explainSubproof(query.first, label, depthLimit);
                 printTree(std::move(t));
             } else if (command[0] == "rule") {
                 try {
                     auto query = split(command[1], ' ');
                     printStr(prov.getRule(query[0], std::stoi(query[1])) + "\n");
                 } catch (std::exception& e) {
                     printStr("Usage: rule <rule number>\n");
                     continue;
                 }
             } else if (command[0] == "printrel") {
                 try {
                     printStr(prov.getRelationOutput(command[1]));
                 } catch (std::exception& e) {
                     printStr("Usage: printrel <relation name>\n");
                     continue;
                 }
             } else if (command[0] == "measure") {
                 try {
                     printStr(prov.measureRelation(command[1]));
                 } catch (std::exception& e) {
                     printStr("Usage: printrel <relation name>\n");
                     continue;
                 }
             } else if (command[0] == "output") {
                 if (command.size() == 2) {
                     output = new std::ofstream(command[1]);
                 } else if (command.size() == 1) {
                     delete output;
                     output = nullptr;
                 } else {
                     printStr("Usage: output  [<filename>]\n");
                 }
             } else if (command[0] == "format") {
                 if (command[1] == "json") {
                     json = true;
                 } else if (command[1] == "proof") {
                     json = false;
                 } else {
                     printStr("Usage: format json/proof\n");
                 }
             } else if (command[0] == "exit") {
                 printStr("Exiting explain\n");
                 break;
             } else {
                 printStr(
                         "\n----------\n"
                         "Commands:\n"
                         "----------\n"
                         "setdepth <depth>: Set a limit for printed derivation tree height\n"
                         "explain <relation>(<element1>, <element2>, ...): Prints derivation tree\n"
                         "subproof <relation>(<label>): Prints derivation tree for a subproof, label is "
                         "generated if a derivation tree exceeds height limit\n"
                         "rule <relation name> <rule number>: Prints a rule\n"
                         "printrel <relation name>: Prints the tuples of a relation\n"
                         "output [<filename>]: Write output into a file/disable output\n"
                         "format json/proof: switch format between json and proof-trees\n"
                         "exit: Exits this interface\n\n");
             }
             // refresh treePad and allow scrolling
             if (ncurses && !output) {
                 prefresh(treePad, 0, 0, 0, 0, maxy - 3, maxx - 1);
                 scrollTree(maxx, maxy);
             }
         }
         if (ncurses && !output) {
             endwin();
         }
     }
void explain (SouffleProgram & prog, bool sld = true, bool ncurses = false) inline
Definition at line 333 of file Explain.h.
References Explain().
{
     std::cout << "Explain is invoked.\n";
     ExplainProvenanceSLD prov(prog);
     Explain exp(prov, ncurses);
     exp.explain();
 }
void initialiseWindow ()
Definition at line 171 of file Explain.h.
References MAX_TREE_HEIGHT, MAX_TREE_WIDTH, souffle::Explain::maxx, souffle::Explain::maxy, souffle::Explain::queryWindow, and souffle::Explain::treePad.
Referenced by explain().
{
         initscr();
         // get size of window
         getmaxyx(stdscr, maxy, maxx);
         // create windows for query and tree display
         queryWindow = makeQueryWindow();
         treePad = newpad(MAX_TREE_HEIGHT, MAX_TREE_WIDTH);
         keypad(treePad, true);
     }
void printStr (const std::string & s)
Definition at line 133 of file Explain.h.
References souffle::Explain::ncurses, souffle::Explain::output, and souffle::Explain::treePad.
Referenced by explain().
{
         if (ncurses && !output) {
             wprintw(treePad, s.c_str());
         } else {
             if (output) {
                 *output << s;
             } else {
                 std::cout << s;
             }
         }
     }
void scrollTree (int maxx, int maxy)
Definition at line 146 of file Explain.h.
References MAX_TREE_HEIGHT, MAX_TREE_WIDTH, souffle::Explain::treePad, and x.
Referenced by explain().
{
         int x = 0;
         int y = 0;
         while (true) {
             int ch = wgetch(treePad);
             if (ch == KEY_LEFT) {
                 if (x > 2) x -= 3;
             } else if (ch == KEY_RIGHT) {
                 if (x < MAX_TREE_WIDTH - 3) x += 3;
             } else if (ch == KEY_UP) {
                 if (y > 0) y -= 1;
             } else if (ch == KEY_DOWN) {
                 if (y < MAX_TREE_HEIGHT - 1) y += 1;
             } else {
                 ungetch(ch);
                 break;
             }
             prefresh(treePad, y, x, 0, 0, maxy - 3, maxx - 1);
         }
     }
~Explain ()
Definition at line 187 of file Explain.h.
References souffle::Explain::output.
                {
         delete output;
     }