souffle: souffle::RamBinaryOperator Class Reference
souffle::RamBinaryOperator Class Reference
Binary function.
#include <RamValue.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamBinaryOperator * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getLevel () const override
Get level.
const RamValue * getLHS () const
Get left-handside argument.
const RamValue & getLHSArgument () const
BinaryOp getOperator () const
Get operator symbol.
const RamValue * getRHS () const
Get right-handside argument.
const RamValue & getRHSArgument () const
void print (std::ostream &os) const override
Print.
RamBinaryOperator (BinaryOp op, std::unique_ptr< RamValue > l, std::unique_ptr< RamValue > r)
Public Member Functions inherited from souffle::RamValue
bool isConstant () const
Determines whether this value is a constant or not.
RamValue (RamNodeType type, bool isCnst)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::unique_ptr< RamValue > lhsArgument
Left-hand side argument.
BinaryOp operation
Operation symbol.
std::unique_ptr< RamValue > rhsArgument
Right-hand side argument.
Additional Inherited Members
Protected Attributes inherited from souffle::RamValue
bool cnst
Detailed Description
Binary function.
Definition at line 131 of file RamValue.h.
Constructor & Destructor Documentation
souffle::RamBinaryOperator::RamBinaryOperator (BinaryOp op, std::unique_ptr< RamValue > l, std::unique_ptr< RamValue > r) inline
Definition at line 143 of file RamValue.h.
Referenced by clone().
             : RamValue(RN_BinaryOperator, l->isConstant() && r->isConstant()), operation(op),
               lhsArgument(std::move(l)), rhsArgument(std::move(r)) {}
Member Function Documentation
void souffle::RamBinaryOperator::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 212 of file RamValue.h.
References lhsArgument, map, and rhsArgument.
{
         lhsArgument = map(std::move(lhsArgument));
         rhsArgument = map(std::move(rhsArgument));
     }
RamBinaryOperator* souffle::RamBinaryOperator::clone () const inline override virtual
Create clone.
Implements souffle::RamValue.
Definition at line 204 of file RamValue.h.
References lhsArgument, operation, RamBinaryOperator(), and rhsArgument.
{
         RamBinaryOperator* res =
                 new RamBinaryOperator(operation, std::unique_ptr<RamValue>(lhsArgument->clone()),
                         std::unique_ptr<RamValue>(rhsArgument->clone()));
         return res;
     }
bool souffle::RamBinaryOperator::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 219 of file RamValue.h.
References getLHSArgument(), getOperator(), and getRHSArgument().
{
         assert(nullptr != dynamic_cast<const RamBinaryOperator*>(&node));
         const auto& other = static_cast<const RamBinaryOperator&>(node);
         return getOperator() == other.getOperator() && getLHSArgument() == other.getLHSArgument() &&
                getRHSArgument() == other.getRHSArgument();
     }
std::vector<const RamNode*> souffle::RamBinaryOperator::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 199 of file RamValue.h.
References lhsArgument, and rhsArgument.
{
         return toVector<const RamNode*>(lhsArgument.get(), rhsArgument.get());
     }
size_t souffle::RamBinaryOperator::getLevel () const inline override virtual
Get level.
Implements souffle::RamValue.
Definition at line 194 of file RamValue.h.
References lhsArgument, and rhsArgument.
{
         return std::max(lhsArgument->getLevel(), rhsArgument->getLevel());
     }
const RamValue* souffle::RamBinaryOperator::getLHS () const inline
Get left-handside argument.
Definition at line 169 of file RamValue.h.
References lhsArgument.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalVal().
{
         return lhsArgument.get();
     }
const RamValue& souffle::RamBinaryOperator::getLHSArgument () const inline
Definition at line 172 of file RamValue.h.
References lhsArgument.
Referenced by equal().
{
         assert(lhsArgument);
         return *lhsArgument;
     }
BinaryOp souffle::RamBinaryOperator::getOperator () const inline
Get operator symbol.
Definition at line 188 of file RamValue.h.
References operation.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalVal().
{
         return operation;
     }
const RamValue* souffle::RamBinaryOperator::getRHS () const inline
Get right-handside argument.
Definition at line 179 of file RamValue.h.
References rhsArgument.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalVal().
{
         return rhsArgument.get();
     }
const RamValue& souffle::RamBinaryOperator::getRHSArgument () const inline
Definition at line 182 of file RamValue.h.
References rhsArgument.
Referenced by equal().
{
         assert(rhsArgument);
         return *rhsArgument;
     }
void souffle::RamBinaryOperator::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 148 of file RamValue.h.
References souffle::getSymbolForBinaryOp(), lhsArgument, souffle::MAX, operation, and rhsArgument.
{
         if (operation < BinaryOp::MAX) {
             // print infix notation
             os << "(";
             lhsArgument->print(os);
             os << getSymbolForBinaryOp(operation);
             rhsArgument->print(os);
             os << ")";
         } else {
             // print prefix notation
             os << getSymbolForBinaryOp(operation);
             os << "(";
             lhsArgument->print(os);
             os << ",";
             rhsArgument->print(os);
             os << ")";
         }
     }
Field Documentation
std::unique_ptr<RamValue> souffle::RamBinaryOperator::lhsArgument private
Left-hand side argument.
Definition at line 137 of file RamValue.h.
Referenced by apply(), clone(), getChildNodes(), getLevel(), getLHS(), getLHSArgument(), and print().
BinaryOp souffle::RamBinaryOperator::operation private
Operation symbol.
Definition at line 134 of file RamValue.h.
Referenced by clone(), getOperator(), and print().
std::unique_ptr<RamValue> souffle::RamBinaryOperator::rhsArgument private
Right-hand side argument.
Definition at line 140 of file RamValue.h.
Referenced by apply(), clone(), getChildNodes(), getLevel(), getRHS(), getRHSArgument(), and print().
The documentation for this class was generated from the following file:
RamValue.h