souffle: souffle::RamRelation Class Reference
souffle::RamRelation Class Reference
A RAM Relation in the RAM intermediate representation.
#include <RamRelation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamRelation * clone () const override
Create clone.
const std::string getArg (uint32_t i) const
const std::string getArgTypeQualifier (uint32_t i) const
unsigned getArity () const
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const std::string & getName () const
const SymbolMask & getSymbolMask () const
const bool isBrie () const
const bool isBTree () const
const bool isComputed () const
const bool isCoverable () const
const bool isEqRel () const
const bool isHashset () const
const bool isInput () const
const bool isOutput () const
const bool isRbtset () const
const bool isTemp () const
bool operator< (const RamRelation &other) const
void print (std::ostream &out) const override
Print RAM node.
RamRelation ()
RamRelation (const std::string &name, unsigned arity, const bool istemp, const bool hashset=false)
RamRelation (std::string name, unsigned arity, std::vector< std::string > attributeNames={}, std::vector< std::string > attributeTypeQualifiers={}, SymbolMask mask=SymbolMask(0), const bool input=false, const bool computed=false, const bool output=false, const bool btree=false, const bool rbtset=false, const bool hashset=false, const bool brie=false, const bool eqrel=false, const bool istemp=false)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
unsigned arity = 0
Arity, i.e., number of attributes.
std::vector< std::string > attributeNames
Name of attributes.
std::vector< std::string > attributeTypeQualifiers
Type of attributes.
bool brie = false
bool btree = false
bool computed = false
bool eqrel = false
bool hashset = false
bool input = false
Relation qualifiers.
bool istemp = false
SymbolMask mask
TODO (#541): legacy, i.e., duplicated information.
std::string name
Name of relation.
bool output = false
bool rbtset = false
Detailed Description
A RAM Relation in the RAM intermediate representation.
TODO (#541): Make RamRelation a sub-class of RAM node. TODO (#541): Tidy-up interface and attributes
Definition at line 40 of file RamRelation.h.
Constructor & Destructor Documentation
souffle::RamRelation::RamRelation () inline
Definition at line 72 of file RamRelation.h.
Referenced by clone().
 : RamNode(RN_Relation), mask(arity) {}
souffle::RamRelation::RamRelation (const std::string & name, unsigned arity, const bool istemp, const bool hashset = false) inline
Definition at line 74 of file RamRelation.h.
References hashset, and istemp.
             : RamRelation(name, arity) {
         this->hashset = hashset;
         this->istemp = istemp;
     }
souffle::RamRelation::RamRelation (std::string name, unsigned arity, std::vector< std::string > attributeNames = {}, std::vector< std::string > attributeTypeQualifiers = {}, SymbolMask mask = SymbolMask(0), const bool input = false, const bool computed = false, const bool output = false, const bool btree = false, const bool rbtset = false, const bool hashset = false, const bool brie = false, const bool eqrel = false, const bool istemp = false) inline
Definition at line 80 of file RamRelation.h.
                                                                                       {},
             std::vector<std::string> attributeTypeQualifiers = {}, SymbolMask mask = SymbolMask(0),
             const bool input = false, const bool computed = false, const bool output = false,
             const bool btree = false, const bool rbtset = false, const bool hashset = false,
             const bool brie = false, const bool eqrel = false, const bool istemp = false)
             : RamNode(RN_Relation), name(std::move(name)), arity(arity),
               attributeNames(std::move(attributeNames)),
               attributeTypeQualifiers(std::move(attributeTypeQualifiers)), mask(std::move(mask)),
               input(input), output(output), computed(computed), btree(btree), rbtset(rbtset),
               hashset(hashset), brie(brie), eqrel(eqrel), istemp(istemp) {
         assert(this->attributeNames.size() == arity || this->attributeNames.empty());
         assert(this->attributeTypeQualifiers.size() == arity || this->attributeTypeQualifiers.empty());
     }
Member Function Documentation
void souffle::RamRelation::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 195 of file RamRelation.h.
 {}
RamRelation* souffle::RamRelation::clone () const inline override virtual
Create clone.
Implements souffle::RamNode.
Definition at line 188 of file RamRelation.h.
References attributeNames, attributeTypeQualifiers, brie, btree, computed, eqrel, hashset, input, istemp, mask, output, RamRelation(), and rbtset.
{
         RamRelation* res = new RamRelation(name, arity, attributeNames, attributeTypeQualifiers, mask, input,
                 computed, output, btree, rbtset, hashset, brie, eqrel, istemp);
         return res;
     }
bool souffle::RamRelation::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 199 of file RamRelation.h.
References attributeNames, attributeTypeQualifiers, isBrie(), isBTree(), isComputed(), isEqRel(), isHashset(), isInput(), isOutput(), isRbtset(), isTemp(), souffle::SymbolMask::mask, mask, and name.
{
         assert(nullptr != dynamic_cast<const RamRelation*>(&node));
         const auto& other = static_cast<const RamRelation&>(node);
         return name == other.name && arity == other.arity && attributeNames == other.attributeNames &&
                attributeTypeQualifiers == other.attributeTypeQualifiers && mask == other.mask &&
                isInput() == other.isInput() && isOutput() == other.isOutput() &&
                isComputed() == other.isComputed() && isBTree() == other.isBTree() &&
                isRbtset() == other.isRbtset() && isHashset() == other.isHashset() &&
                isBrie() == other.isBrie() && isEqRel() == other.isEqRel() && isTemp() == other.isTemp();
     }
const std::string souffle::RamRelation::getArg (uint32_t i) const inline
Definition at line 98 of file RamRelation.h.
References attributeNames, and i.
Referenced by souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::RamCreate::print(), print(), and souffle::IndexSetAnalysis::print().
{
         if (!attributeNames.empty()) {
             return attributeNames[i];
         }
         if (arity == 0) {
             return "";
         }
         return "c" + std::to_string(i);
     }
const std::string souffle::RamRelation::getArgTypeQualifier (uint32_t i) const inline
Definition at line 108 of file RamRelation.h.
References attributeTypeQualifiers.
Referenced by souffle::InterpreterProgInterface::InterpreterProgInterface().
{
         return (i < attributeTypeQualifiers.size()) ? attributeTypeQualifiers[i] : "";
     }
unsigned souffle::RamRelation::getArity () const inline
Definition at line 157 of file RamRelation.h.
References arity.
Referenced by souffle::Interpreter::evalOp(), souffle::Interpreter::evalStmt(), souffle::Synthesiser::generateCode(), souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getSynthesiserRelation(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::RamCreate::print(), and souffle::IndexSetAnalysis::print().
{
         return arity;
     }
std::vector<const RamNode*> souffle::RamRelation::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 183 of file RamRelation.h.
{
         return std::vector<const RamNode*>();  // no child nodes
     }
const std::string& souffle::RamRelation::getName () const inline
Definition at line 94 of file RamRelation.h.
References name.
Referenced by souffle::Interpreter::evalStmt(), souffle::Interpreter::executeMain(), souffle::Synthesiser::generateCode(), souffle::IndexSetAnalysis::getIndexes(), souffle::Synthesiser::getRelationName(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::RamCreate::print(), souffle::RamLoad::print(), souffle::RamStore::print(), souffle::RamClear::print(), souffle::RamDrop::print(), souffle::RamFact::print(), souffle::RamLogSize::print(), souffle::RamPrintSize::print(), and souffle::Interpreter::swapRelation().
{
         return name;
     }
const SymbolMask& souffle::RamRelation::getSymbolMask () const inline
Definition at line 112 of file RamRelation.h.
References mask.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalStmt(), and souffle::Synthesiser::generateCode().
{
         return mask;
     }
const bool souffle::RamRelation::isBrie () const inline
Definition at line 140 of file RamRelation.h.
References brie.
Referenced by equal(), souffle::SynthesiserRelation::getSynthesiserRelation(), and print().
{
         return brie;
     }
const bool souffle::RamRelation::isBTree () const inline
Definition at line 128 of file RamRelation.h.
References btree.
Referenced by equal(), souffle::SynthesiserRelation::getSynthesiserRelation(), and print().
{
         return btree;
     }
const bool souffle::RamRelation::isComputed () const inline
Definition at line 120 of file RamRelation.h.
References computed.
Referenced by equal().
{
         return computed;
     }
const bool souffle::RamRelation::isCoverable () const inline
Definition at line 149 of file RamRelation.h.
References isHashset().
{
         return !isHashset();
     }
const bool souffle::RamRelation::isEqRel () const inline
Definition at line 144 of file RamRelation.h.
References eqrel.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::SynthesiserRelation::getSynthesiserRelation(), and print().
{
         return eqrel;
     }
const bool souffle::RamRelation::isHashset () const inline
Definition at line 136 of file RamRelation.h.
References hashset.
Referenced by equal(), souffle::SynthesiserRelation::getSynthesiserRelation(), isCoverable(), and print().
{
         return hashset;
     }
const bool souffle::RamRelation::isInput () const inline
Definition at line 116 of file RamRelation.h.
References input.
Referenced by equal().
{
         return input;
     }
const bool souffle::RamRelation::isOutput () const inline
Definition at line 124 of file RamRelation.h.
References output.
Referenced by equal().
{
         return output;
     }
const bool souffle::RamRelation::isRbtset () const inline
Definition at line 132 of file RamRelation.h.
References rbtset.
Referenced by equal(), souffle::SynthesiserRelation::getSynthesiserRelation(), and print().
{
         return rbtset;
     }
const bool souffle::RamRelation::isTemp () const inline
Definition at line 153 of file RamRelation.h.
References istemp.
Referenced by souffle::Synthesiser::emitCode(), and equal().
{
         return istemp;
     }
bool souffle::RamRelation::operator< (const RamRelation & other) const inline
Definition at line 161 of file RamRelation.h.
References name.
{
         return name < other.name;
     }
void souffle::RamRelation::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 166 of file RamRelation.h.
References arity, getArg(), i, isBrie(), isBTree(), isEqRel(), isHashset(), and isRbtset().
{
         out << name << "(";
         out << getArg(0);
         for (unsigned i = 1; i < arity; i++) {
             out << ",";
             out << getArg(i);
         }
         out << ")";
         if (isBTree()) out << " btree";
         if (isRbtset()) out << " rbtset";
         if (isHashset()) out << " hashset";
         if (isBrie()) out << " brie";
         if (isEqRel()) out << " eqrel";
     }
Field Documentation
unsigned souffle::RamRelation::arity = 0 protected
Arity, i.e., number of attributes.
Definition at line 46 of file RamRelation.h.
Referenced by getArity(), and print().
std::vector<std::string> souffle::RamRelation::attributeNames protected
Name of attributes.
Definition at line 49 of file RamRelation.h.
Referenced by clone(), equal(), and getArg().
std::vector<std::string> souffle::RamRelation::attributeTypeQualifiers protected
Type of attributes.
Definition at line 52 of file RamRelation.h.
Referenced by clone(), equal(), and getArgTypeQualifier().
bool souffle::RamRelation::brie = false protected
Definition at line 66 of file RamRelation.h.
Referenced by clone(), and isBrie().
bool souffle::RamRelation::btree = false protected
Definition at line 63 of file RamRelation.h.
Referenced by clone(), and isBTree().
bool souffle::RamRelation::computed = false protected
Definition at line 61 of file RamRelation.h.
Referenced by clone(), and isComputed().
bool souffle::RamRelation::eqrel = false protected
Definition at line 67 of file RamRelation.h.
Referenced by clone(), and isEqRel().
bool souffle::RamRelation::hashset = false protected
Definition at line 65 of file RamRelation.h.
Referenced by clone(), isHashset(), and RamRelation().
bool souffle::RamRelation::input = false protected
Relation qualifiers.
Definition at line 59 of file RamRelation.h.
Referenced by clone(), and isInput().
bool souffle::RamRelation::istemp = false protected
Definition at line 69 of file RamRelation.h.
Referenced by clone(), isTemp(), and RamRelation().
SymbolMask souffle::RamRelation::mask protected
TODO (#541): legacy, i.e., duplicated information.
Definition at line 55 of file RamRelation.h.
Referenced by clone(), equal(), and getSymbolMask().
std::string souffle::RamRelation::name protected
Name of relation.
Definition at line 43 of file RamRelation.h.
Referenced by equal(), getName(), and operator<().
bool souffle::RamRelation::output = false protected
Definition at line 60 of file RamRelation.h.
Referenced by clone(), and isOutput().
bool souffle::RamRelation::rbtset = false protected
Definition at line 64 of file RamRelation.h.
Referenced by clone(), and isRbtset().
The documentation for this class was generated from the following file:
RamRelation.h