souffle: souffle::RamProvenanceNotExists Class Reference
souffle::RamProvenanceNotExists Class Reference
Not existence check for a relation for provenance existence check.
#include <RamCondition.h>
Public Member Functions
void addArg (std::unique_ptr< RamValue > v)
Add argument.
void apply (const RamNodeMapper &map) override
Apply.
RamProvenanceNotExists * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
SearchColumns getKey () const
Get key.
size_t getLevel () override
Get level.
const RamRelation & getRelation () const
Get relation.
std::vector< RamValue * > getValues () const
Get arguments.
bool isTotal () const
Is key total.
void print (std::ostream &os) const override
Print.
RamProvenanceNotExists (std::unique_ptr< RamRelation > rel)
Public Member Functions inherited from souffle::RamCondition
RamCondition (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamRelation > relation
std::vector< std::unique_ptr
< RamValue > > values
Pattern – nullptr if undefined.
Detailed Description
Not existence check for a relation for provenance existence check.
Definition at line 323 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamProvenanceNotExists::RamProvenanceNotExists (std::unique_ptr< RamRelation > rel) inline
Definition at line 333 of file RamCondition.h.
Referenced by clone().
             : RamCondition(RN_ProvenanceNotExists), relation(std::move(rel)) {}
Member Function Documentation
void souffle::RamProvenanceNotExists::addArg (std::unique_ptr< RamValue > v) inline
Add argument.
Definition at line 347 of file RamCondition.h.
References values.
Referenced by souffle::AstTranslator::translateClause().
{
         values.push_back(std::move(v));
     }
void souffle::RamProvenanceNotExists::apply (const RamNodeMapper & map) inline override virtual
Apply.
Implements souffle::RamNode.
Definition at line 422 of file RamCondition.h.
References map, relation, and values.
{
         relation = map(std::move(relation));
         for (auto& val : values) {
             if (val != nullptr) {
                 val = map(std::move(val));
             }
         }
     }
RamProvenanceNotExists* souffle::RamProvenanceNotExists::clone () const inline override virtual
Create clone.
Implements souffle::RamCondition.
Definition at line 408 of file RamCondition.h.
References souffle::RamValue::clone(), RamProvenanceNotExists(), relation, and values.
{
         RamProvenanceNotExists* res =
                 new RamProvenanceNotExists(std::unique_ptr<RamRelation>(relation->clone()));
         for (auto& cur : values) {
             RamValue* val = nullptr;
             if (cur != nullptr) {
                 val = cur->clone();
             }
             res->values.push_back(std::unique_ptr<RamValue>(val));
         }
         return res;
     }
bool souffle::RamProvenanceNotExists::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 433 of file RamCondition.h.
References souffle::equal_targets(), getRelation(), and values.
{
         assert(dynamic_cast<const RamProvenanceNotExists*>(&node));
         const RamProvenanceNotExists& other = static_cast<const RamProvenanceNotExists&>(node);
         return getRelation() == other.getRelation() && equal_targets(values, other.values);
     }
std::vector<const RamNode*> souffle::RamProvenanceNotExists::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 399 of file RamCondition.h.
References relation, and values.
{
         std::vector<const RamNode*> res = {relation.get()};
         for (const auto& cur : values) {
             res.push_back(cur.get());
         }
         return res;
     }
SearchColumns souffle::RamProvenanceNotExists::getKey () const inline
Get key.
Definition at line 377 of file RamCondition.h.
References i, and values.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalCond().
{
         SearchColumns res = 0;
         // values.size() - 1 because we discard the height annotation
         for (unsigned i = 0; i < values.size() - 1; i++) {
             if (values[i]) {
                 res |= (1 << i);
             }
         }
         return res;
     }
size_t souffle::RamProvenanceNotExists::getLevel () inline override virtual
Get level.
Implements souffle::RamCondition.
Definition at line 352 of file RamCondition.h.
References level, and values.
{
         size_t level = 0;
         for (const auto& cur : values) {
             if (cur) {
                 level = std::max(level, cur->getLevel());
             }
         }
         return level;
     }
const RamRelation& souffle::RamProvenanceNotExists::getRelation () const inline
Get relation.
Definition at line 337 of file RamCondition.h.
References relation.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalCond().
{
         return *relation;
     }
std::vector<RamValue*> souffle::RamProvenanceNotExists::getValues () const inline
Get arguments.
Definition at line 342 of file RamCondition.h.
References souffle::toPtrVector(), and values.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalCond().
{
         return toPtrVector(values);
     }
bool souffle::RamProvenanceNotExists::isTotal () const inline
Is key total.
Definition at line 389 of file RamCondition.h.
References values.
{
         for (const auto& cur : values) {
             if (!cur) {
                 return false;
             }
         }
         return true;
     }
void souffle::RamProvenanceNotExists::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 363 of file RamCondition.h.
References souffle::join(), relation, and values.
{
         os << "("
            << join(values, ",",
                       [](std::ostream& out, const std::unique_ptr<RamValue>& value) {
                           if (!value) {
                               out << "_";
                           } else {
                               out << *value;
                           }
                       })
            << ") prov∉ " << relation->getName();
     }
Field Documentation
std::unique_ptr<RamRelation> souffle::RamProvenanceNotExists::relation protected
Definition at line 326 of file RamCondition.h.
Referenced by apply(), clone(), getChildNodes(), getRelation(), and print().
std::vector<std::unique_ptr<RamValue> > souffle::RamProvenanceNotExists::values protected
Pattern – nullptr if undefined.
Definition at line 330 of file RamCondition.h.
Referenced by addArg(), apply(), clone(), equal(), getChildNodes(), getKey(), getLevel(), getValues(), isTotal(), and print().
The documentation for this class was generated from the following file:
RamCondition.h