souffle: souffle::RamPack Class Reference
souffle::RamPack Class Reference
Record pack operation.
#include <RamValue.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
arguments (std::move(args))
RamPack * clone () const override
Create clone.
std::vector< RamValue * > getArguments () const
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getLevel () const override
Get level.
std::vector< RamValue * > getValues () const
Get values.
void print (std::ostream &os) const override
Print.
RamPack (std::vector< std::unique_ptr< RamValue >> args)
Public Member Functions inherited from souffle::RamValue
bool isConstant () const
Determines whether this value is a constant or not.
RamValue (RamNodeType type, bool isCnst)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::vector< std::unique_ptr
< RamValue > > arguments
Arguments.
Additional Inherited Members
Protected Attributes inherited from souffle::RamValue
bool cnst
Detailed Description
Record pack operation.
Definition at line 474 of file RamValue.h.
Constructor & Destructor Documentation
souffle::RamPack::RamPack (std::vector< std::unique_ptr< RamValue >> args) inline
Definition at line 481 of file RamValue.h.
Referenced by clone().
             : RamValue(RN_Pack,
                       all_of(args, [](const std::unique_ptr<RamValue>& a) { return a && a->isConstant(); })),
Member Function Documentation
void souffle::RamPack::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 543 of file RamValue.h.
References arguments, and map.
{
         for (auto& arg : arguments) {
             if (arg != nullptr) {
                 arg = map(std::move(arg));
             }
         }
     }
souffle::RamPack::arguments (std:: moveargs) inline
Definition at line 484 of file RamValue.h.
 {}
RamPack* souffle::RamPack::clone () const inline override virtual
Create clone.
Implements souffle::RamValue.
Definition at line 530 of file RamValue.h.
References arguments, souffle::RamValue::clone(), and RamPack().
{
         RamPack* res = new RamPack({});
         for (auto& cur : arguments) {
             RamValue* arg = nullptr;
             if (cur != nullptr) {
                 arg = cur->clone();
             }
             res->arguments.push_back(std::unique_ptr<RamValue>(arg));
         }
         return res;
     }
bool souffle::RamPack::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 553 of file RamValue.h.
References arguments, and souffle::equal_targets().
{
         assert(nullptr != dynamic_cast<const RamPack*>(&node));
         const auto& other = static_cast<const RamPack&>(node);
         return equal_targets(arguments, other.arguments);
     }
std::vector<RamValue*> souffle::RamPack::getArguments () const inline
Definition at line 491 of file RamValue.h.
References arguments, and souffle::toPtrVector().
{
         return toPtrVector(arguments);
     }
std::vector<const RamNode*> souffle::RamPack::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 519 of file RamValue.h.
References arguments.
{
         std::vector<const RamNode*> res;
         for (const auto& cur : arguments) {
             if (cur) {
                 res.push_back(cur.get());
             }
         }
         return res;
     }
size_t souffle::RamPack::getLevel () const inline override virtual
Get level.
Implements souffle::RamValue.
Definition at line 508 of file RamValue.h.
References arguments, and level.
{
         size_t level = 0;
         for (const auto& arg : arguments) {
             if (arg) {
                 level = std::max(level, arg->getLevel());
             }
         }
         return level;
     }
std::vector<RamValue*> souffle::RamPack::getValues () const inline
Get values.
Definition at line 488 of file RamValue.h.
References arguments, and souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalVal().
{
         return toPtrVector(arguments);
     }
void souffle::RamPack::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 496 of file RamValue.h.
References arguments, and souffle::join().
{
         os << "[" << join(arguments, ",", [](std::ostream& out, const std::unique_ptr<RamValue>& arg) {
             if (arg) {
                 out << *arg;
             } else {
                 out << "_";
             }
         }) << "]";
     }
Field Documentation
std::vector<std::unique_ptr<RamValue> > souffle::RamPack::arguments private
Arguments.
Definition at line 478 of file RamValue.h.
Referenced by apply(), clone(), equal(), getArguments(), getChildNodes(), getLevel(), getValues(), and print().
The documentation for this class was generated from the following file:
RamValue.h