souffle: souffle::RamUnaryOperator Class Reference
souffle::RamUnaryOperator Class Reference
Unary function.
#include <RamValue.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamUnaryOperator * clone () const override
Create clone.
const RamValue & getArgument () const
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getLevel () const override
Get level.
UnaryOp getOperator () const
Get operator.
const RamValue * getValue () const
Get Argument.
void print (std::ostream &os) const override
Print.
RamUnaryOperator (UnaryOp op, std::unique_ptr< RamValue > v)
Public Member Functions inherited from souffle::RamValue
bool isConstant () const
Determines whether this value is a constant or not.
RamValue (RamNodeType type, bool isCnst)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::unique_ptr< RamValue > argument
Argument of unary function.
UnaryOp operation
Operation symbol.
Additional Inherited Members
Protected Attributes inherited from souffle::RamValue
bool cnst
Detailed Description
Unary function.
Definition at line 63 of file RamValue.h.
Constructor & Destructor Documentation
souffle::RamUnaryOperator::RamUnaryOperator (UnaryOp op, std::unique_ptr< RamValue > v) inline
Definition at line 72 of file RamValue.h.
Referenced by clone().
             : RamValue(RN_UnaryOperator, v->isConstant()), operation(op), argument(std::move(v)) {}
Member Function Documentation
void souffle::RamUnaryOperator::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 114 of file RamValue.h.
References argument, and map.
{
         argument = map(std::move(argument));
     }
RamUnaryOperator* souffle::RamUnaryOperator::clone () const inline override virtual
Create clone.
Implements souffle::RamValue.
Definition at line 108 of file RamValue.h.
References argument, operation, and RamUnaryOperator().
{
         RamUnaryOperator* res = new RamUnaryOperator(operation, std::unique_ptr<RamValue>(argument->clone()));
         return res;
     }
bool souffle::RamUnaryOperator::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 120 of file RamValue.h.
References getArgument(), and getOperator().
{
         assert(nullptr != dynamic_cast<const RamUnaryOperator*>(&node));
         const auto& other = static_cast<const RamUnaryOperator&>(node);
         return getOperator() == other.getOperator() && getArgument() == other.getArgument();
     }
const RamValue& souffle::RamUnaryOperator::getArgument () const inline
Definition at line 87 of file RamValue.h.
References argument.
Referenced by equal().
{
         return *argument;
     }
std::vector<const RamNode*> souffle::RamUnaryOperator::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 103 of file RamValue.h.
References argument.
{
         return toVector<const RamNode*>(argument.get());
     }
size_t souffle::RamUnaryOperator::getLevel () const inline override virtual
Get level.
Implements souffle::RamValue.
Definition at line 98 of file RamValue.h.
References argument.
{
         return argument->getLevel();
     }
UnaryOp souffle::RamUnaryOperator::getOperator () const inline
Get operator.
Definition at line 92 of file RamValue.h.
References operation.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalVal().
{
         return operation;
     }
const RamValue* souffle::RamUnaryOperator::getValue () const inline
Get Argument.
Definition at line 84 of file RamValue.h.
References argument.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalVal().
{
         return argument.get();
     }
void souffle::RamUnaryOperator::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 76 of file RamValue.h.
References argument, souffle::getSymbolForUnaryOp(), and operation.
{
         os << getSymbolForUnaryOp(operation) << "(";
         argument->print(os);
         os << ")";
     }
Field Documentation
std::unique_ptr<RamValue> souffle::RamUnaryOperator::argument private
Argument of unary function.
Definition at line 69 of file RamValue.h.
Referenced by apply(), clone(), getArgument(), getChildNodes(), getLevel(), getValue(), and print().
UnaryOp souffle::RamUnaryOperator::operation private
Operation symbol.
Definition at line 66 of file RamValue.h.
Referenced by clone(), getOperator(), and print().
The documentation for this class was generated from the following file:
RamValue.h