souffle: souffle::ReadStreamCSV Class Reference
souffle::ReadStreamCSV Class Reference
#include <ReadStreamCSV.h>
Public Member Functions
ReadStreamCSV (std::istream &file, const SymbolMask &symbolMask, SymbolTable &symbolTable, const IODirectives &ioDirectives, const bool provenance=false)
~ReadStreamCSV () override=default
Public Member Functions inherited from souffle::ReadStream
template<typename T >
void readAll (T &relation)
ReadStream (const SymbolMask &symbolMask, SymbolTable &symbolTable, const bool prov)
virtual ~ReadStream ()=default
Protected Member Functions
std::string getDelimiter (const IODirectives &ioDirectives) const
std::map< int, int > getInputColumnMap (const IODirectives &ioDirectives, const unsigned arity) const
std::unique_ptr< RamDomain[]> readNextTuple () override
Read and return the next tuple.
Protected Attributes
const std::string delimiter
std::istream & file
std::map< int, int > inputMap
size_t lineNumber
Protected Attributes inherited from souffle::ReadStream
const bool isProvenance
const SymbolMask & symbolMask
SymbolTable & symbolTable
Detailed Description
Definition at line 38 of file ReadStreamCSV.h.
Constructor & Destructor Documentation
souffle::ReadStreamCSV::ReadStreamCSV (std::istream & file, const SymbolMask & symbolMask, SymbolTable & symbolTable, const IODirectives & ioDirectives, const bool provenance = false) inline
Definition at line 40 of file ReadStreamCSV.h.
References souffle::SymbolMask::getArity(), and inputMap.
             : ReadStream(symbolMask, symbolTable, provenance), delimiter(getDelimiter(ioDirectives)),
               file(file), lineNumber(0), inputMap(getInputColumnMap(ioDirectives, symbolMask.getArity())) {
         while (this->inputMap.size() < symbolMask.getArity()) {
             int size = this->inputMap.size();
             this->inputMap[size] = size;
         }
     }
souffle::ReadStreamCSV::~ReadStreamCSV () override default
Member Function Documentation
std::string souffle::ReadStreamCSV::getDelimiter (const IODirectives & ioDirectives) const inline protected
Definition at line 157 of file ReadStreamCSV.h.
References souffle::IODirectives::get(), and souffle::IODirectives::has().
{
         if (ioDirectives.has("delimiter")) {
             return ioDirectives.get("delimiter");
         }
         return "\t";
     }
std::map<int, int> souffle::ReadStreamCSV::getInputColumnMap (const IODirectives & ioDirectives, const unsigned arity) const inline protected
Definition at line 164 of file ReadStreamCSV.h.
References arity, souffle::IODirectives::get(), souffle::IODirectives::has(), and inputMap.
{
         std::string columnString = "";
         if (ioDirectives.has("columns")) {
             columnString = ioDirectives.get("columns");
         }
         std::map<int, int> inputMap;
         if (!columnString.empty()) {
             std::istringstream iss(columnString);
             std::string mapping;
             int index = 0;
             while (std::getline(iss, mapping, ':')) {
                 inputMap[stoi(mapping)] = index++;
             }
             if (inputMap.size() < arity) {
                 throw std::invalid_argument("Invalid column set was given: <" + columnString + ">");
             }
         } else {
             while (inputMap.size() < arity) {
                 int size = inputMap.size();
                 inputMap[size] = size;
             }
         }
         return inputMap;
     }
std::unique_ptr<RamDomain[]> souffle::ReadStreamCSV::readNextTuple () inline override protected virtual
Read and return the next tuple.
Returns nullptr if no tuple was readable.
Returns
Implements souffle::ReadStream.
Reimplemented in souffle::ReadFileCSV.
Definition at line 59 of file ReadStreamCSV.h.
References delimiter, file, souffle::SymbolMask::getArity(), inputMap, souffle::ReadStream::isProvenance, souffle::SymbolMask::isSymbol(), lineNumber, souffle::ReadStream::symbolMask, souffle::ReadStream::symbolTable, and souffle::SymbolTable::unsafeLookup().
Referenced by souffle::ReadFileCSV::readNextTuple().
{
         if (file.eof()) {
             return nullptr;
         }
         std::string line;
         std::unique_ptr<RamDomain[]> tuple = std::make_unique<RamDomain[]>(symbolMask.getArity());
         bool error = false;
         if (!getline(file, line)) {
             return nullptr;
         }
         // Handle Windows line endings on non-Windows systems
         if (line.back() == '\r') {
             line = line.substr(0, line.length() - 1);
         }
         ++lineNumber;
         size_t start = 0, end = 0, columnsFilled = 0;
         for (uint32_t column = 0; end < line.length(); column++) {
             if (isProvenance && columnsFilled >= symbolMask.getArity() - 2) {
                 end = line.length();
                 break;
             }
             end = line.find(delimiter, start);
             if (end == std::string::npos) {
                 end = line.length();
             }
             std::string element;
             if (start <= end && end <= line.length()) {
                 element = line.substr(start, end - start);
                 if (element.empty()) {
                     element = "n/a";
                 }
             } else {
                 if (!error) {
                     std::stringstream errorMessage;
                     errorMessage << "Value missing in column " << column + 1 << " in line " << lineNumber
                                  << "; ";
                     throw std::invalid_argument(errorMessage.str());
                 }
                 element = "n/a";
             }
             start = end + delimiter.size();
             if (inputMap.count(column) == 0) {
                 continue;
             }
             ++columnsFilled;
             if (symbolMask.isSymbol(column)) {
                 tuple[inputMap[column]] = symbolTable.unsafeLookup(element);
             } else {
                 try {
 #if RAM_DOMAIN_SIZE == 64
                     tuple[inputMap[column]] = std::stoll(element);
 #else
                     tuple[inputMap[column]] = std::stoi(element);
 #endif
                 } catch (...) {
                     if (!error) {
                         std::stringstream errorMessage;
                         errorMessage << "Error converting number <" + element + "> in column " << column + 1
                                      << " in line " << lineNumber << "; ";
                         throw std::invalid_argument(errorMessage.str());
                     }
                 }
             }
         }
         // add two provenance columns
         if (isProvenance) {
             tuple[symbolMask.getArity() - 2] = 0;
             tuple[symbolMask.getArity() - 1] = 0;
             if (columnsFilled >= symbolMask.getArity() - 2 && columnsFilled <= symbolMask.getArity()) {
                 columnsFilled = symbolMask.getArity();
             }
             // columnsFilled += 2;
         }
         if (columnsFilled != symbolMask.getArity()) {
             std::stringstream errorMessage;
             errorMessage << "Values missing in line " << lineNumber << "; ";
             throw std::invalid_argument(errorMessage.str());
         }
         if (end != line.length()) {
             if (!error) {
                 std::stringstream errorMessage;
                 errorMessage << "Too many cells in line " << lineNumber << "; ";
                 throw std::invalid_argument(errorMessage.str());
             }
         }
         if (error) {
             throw std::invalid_argument("cannot parse fact file");
         }
         return tuple;
     }
Field Documentation
const std::string souffle::ReadStreamCSV::delimiter protected
Definition at line 190 of file ReadStreamCSV.h.
Referenced by readNextTuple().
std::istream& souffle::ReadStreamCSV::file protected
Definition at line 191 of file ReadStreamCSV.h.
Referenced by souffle::ReadFileCSV::ReadFileCSV(), and readNextTuple().
std::map<int, int> souffle::ReadStreamCSV::inputMap protected
Definition at line 193 of file ReadStreamCSV.h.
Referenced by getInputColumnMap(), readNextTuple(), and ReadStreamCSV().
size_t souffle::ReadStreamCSV::lineNumber protected
Definition at line 192 of file ReadStreamCSV.h.
Referenced by readNextTuple().
The documentation for this class was generated from the following file:
ReadStreamCSV.h