souffle: souffle::ResolveAliasesTransformer Class Reference
souffle::ResolveAliasesTransformer Class Reference
Transformation pass to eliminate grounded aliases.
#include <AstTransforms.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Static Public Member Functions
static std::unique_ptr< AstClause > removeTrivialEquality (const AstClause &clause)
Removes trivial equalities of the form t = t from the given clause.
static std::unique_ptr< AstClause > resolveAliases (const AstClause &clause)
Converts the given clause into a version without variables aliasing grounded variables.
static void resolveAliases (AstProgram &program)
Eliminate grounded aliases in the given program.
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Static Private Member Functions
static void removeComplexTermsInAtoms (AstClause &clause)
Detailed Description
Transformation pass to eliminate grounded aliases.
e.g. resolve a(r) , r = [x,y] => a(x,y)
Definition at line 40 of file AstTransforms.h.
Member Function Documentation
std::string souffle::ResolveAliasesTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 49 of file AstTransforms.h.
{
         return "ResolveAliasesTransformer";
     }
void souffle::ResolveAliasesTransformer::removeComplexTermsInAtoms (AstClause & clause) static private
Definition at line 396 of file AstTransforms.cpp.
References souffle::AstClause::addToBody(), souffle::any_of(), souffle::EQ, souffle::AstClause::getBodyLiterals(), map, and souffle::toString().
Referenced by resolveAliases().
{
     // restore temporary variables for expressions in atoms
     // get list of atoms
     std::vector<AstAtom*> atoms;
     for (AstLiteral* cur : clause.getBodyLiterals()) {
         if (auto* arg = dynamic_cast<AstAtom*>(cur)) {
             atoms.push_back(arg);
         }
     }
     // find all binary operations in atoms
     std::vector<const AstArgument*> terms;
     for (const AstAtom* cur : atoms) {
         for (const AstArgument* arg : cur->getArguments()) {
             // only interested in functions
             if (!(dynamic_cast<const AstFunctor*>(arg))) {
                 continue;
             }
             // add this one if not yet registered
             if (!any_of(terms, [&](const AstArgument* cur) { return *cur == *arg; })) {
                 terms.push_back(arg);
             }
         }
     }
     // substitute them with variables (a real map would compare pointers)
     using substitution_map =
             std::vector<std::pair<std::unique_ptr<AstArgument>, std::unique_ptr<AstVariable>>>;
     substitution_map map;
     int var_counter = 0;
     for (const AstArgument* arg : terms) {
         map.push_back(std::make_pair(std::unique_ptr<AstArgument>(arg->clone()),
                 std::make_unique<AstVariable>(" _tmp_" + toString(var_counter++))));
     }
     // apply mapping to replace terms with variables
     struct Update : public AstNodeMapper {
         const substitution_map& map;
         Update(const substitution_map& map) : map(map) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             // check whether node needs to be replaced
             for (const auto& cur : map) {
                 if (*cur.first == *node) {
                     return std::unique_ptr<AstNode>(cur.second->clone());
                 }
             }
             // continue recursively
             node->apply(*this);
             return node;
         }
     };
     Update update(map);
     // update atoms
     for (AstAtom* atom : atoms) {
         atom->apply(update);
     }
     // add variable constraints to clause
     for (const auto& cur : map) {
         clause.addToBody(std::make_unique<AstBinaryConstraint>(BinaryConstraintOp::EQ,
                 std::unique_ptr<AstArgument>(cur.second->clone()),
                 std::unique_ptr<AstArgument>(cur.first->clone())));
     }
 }
std::unique_ptr< AstClause > souffle::ResolveAliasesTransformer::removeTrivialEquality (const AstClause & clause) static
Removes trivial equalities of the form t = t from the given clause.
Parameters
clause the clause to be processed
Returns
a modified clone of the given clause
Definition at line 377 of file AstTransforms.cpp.
References souffle::AstClause::cloneHead(), souffle::EQ, souffle::AstClause::getBodyLiterals(), and rel().
Referenced by resolveAliases().
{
     // finally: remove t = t constraints
     std::unique_ptr<AstClause> res(clause.cloneHead());
     for (AstLiteral* cur : clause.getBodyLiterals()) {
         // filter out t = t
         if (auto* rel = dynamic_cast<AstBinaryConstraint*>(cur)) {
             if (rel->getOperator() == BinaryConstraintOp::EQ) {
                 if (*rel->getLHS() == *rel->getRHS()) {
                     continue;  // skip this one
                 }
             }
         }
         res->addToBody(std::unique_ptr<AstLiteral>(cur->clone()));
     }
     // done
     return res;
 }
std::unique_ptr< AstClause > souffle::ResolveAliasesTransformer::resolveAliases (const AstClause & clause) static
Converts the given clause into a version without variables aliasing grounded variables.
Parameters
clause the clause to be processed
Returns
a clone of the processed clause
This alias analysis utilizes unification over the equality constraints in clauses.
Definition at line 260 of file AstTransforms.cpp.
References b, souffle::AstClause::clone(), souffle::EQ, souffle::AstBinaryConstraint::getLHS(), souffle::AstBinaryConstraint::getOperator(), souffle::AstBinaryConstraint::getRHS(), i, rel(), and souffle::visitDepthFirst().
Referenced by resolveAliases(), and transform().
{
     /**
      * This alias analysis utilizes unification over the equality
      * constraints in clauses.
      */
     // -- utilities --
     // tests whether something is a ungrounded variable
     auto isVar = [&](const AstArgument& arg) { return dynamic_cast<const AstVariable*>(&arg); };
     // tests whether something is a record
     auto isRec = [&](const AstArgument& arg) { return dynamic_cast<const AstRecordInit*>(&arg); };
     // tests whether a value a occurs in a term b
     auto occurs = [](const AstArgument& a, const AstArgument& b) {
         bool res = false;
         visitDepthFirst(b, [&](const AstArgument& cur) { res = res || cur == a; });
         return res;
     };
     // I) extract equations
     std::vector<Equation> equations;
     visitDepthFirst(clause, [&](const AstBinaryConstraint& rel) {
         if (rel.getOperator() == BinaryConstraintOp::EQ) {
             equations.push_back(Equation(rel.getLHS(), rel.getRHS()));
         }
     });
     // II) compute unifying substitution
     Substitution substitution;
     // a utility for processing newly identified mappings
     auto newMapping = [&](const std::string& var, const AstArgument* term) {
         // found a new substitution
         Substitution newMapping(var, term);
         // apply substitution to all remaining equations
         for (auto& cur : equations) {
             cur.apply(newMapping);
         }
         // add mapping v -> t to substitution
         substitution.append(newMapping);
     };
     while (!equations.empty()) {
         // get next equation to compute
         Equation cur = equations.back();
         equations.pop_back();
         // shortcuts for left/right
         const AstArgument& a = *cur.lhs;
         const AstArgument& b = *cur.rhs;
         // #1:   t = t   => skip
         if (a == b) {
             continue;
         }
         // #2:   [..] = [..]   => decompose
         if (isRec(a) && isRec(b)) {
             // get arguments
             const auto& args_a = static_cast<const AstRecordInit&>(a).getArguments();
             const auto& args_b = static_cast<const AstRecordInit&>(b).getArguments();
             // make sure sizes are identical
             assert(args_a.size() == args_b.size());
             // create new equalities
             for (size_t i = 0; i < args_a.size(); ++i) {
                 equations.push_back(Equation(args_a[i], args_b[i]));
             }
             continue;
         }
         // neither is a variable
         if (!isVar(a) && !isVar(b)) {
             continue;  // => nothing to do
         }
         // both are variables
         if (isVar(a) && isVar(b)) {
             // a new mapping is found
             auto& var = static_cast<const AstVariable&>(a);
             newMapping(var.getName(), &b);
             continue;
         }
         // #3:   t = v   => swap
         if (!isVar(a)) {
             equations.push_back(Equation(b, a));
             continue;
         }
         // now we know a is a variable
         assert(isVar(a));
         // we have   v = t
         const auto& v = static_cast<const AstVariable&>(a);
         const AstArgument& t = b;
         // #4:   v occurs in t
         if (occurs(v, t)) {
             continue;
         }
         assert(!occurs(v, t));
         // add new maplet
         newMapping(v.getName(), &t);
     }
     // III) compute resulting clause
     return substitution(std::unique_ptr<AstClause>(clause.clone()));
 }
void souffle::ResolveAliasesTransformer::resolveAliases (AstProgram & program) static
Eliminate grounded aliases in the given program.
Parameters
program the program to be processed
Definition at line 75 of file AstTransforms.cpp.
References souffle::AstProgram::appendClause(), souffle::AstRelation::getClauses(), rel(), souffle::AstProgram::removeClause(), removeComplexTermsInAtoms(), removeTrivialEquality(), resolveAliases(), and souffle::visitDepthFirst().
{
     // get all clauses
     std::vector<const AstClause*> clauses;
     visitDepthFirst(program, [&](const AstRelation& rel) {
         for (const auto& cur : rel.getClauses()) {
             clauses.push_back(cur);
         }
     });
     // clean all clauses
     for (const AstClause* cur : clauses) {
         // -- Step 1 --
         // get rid of aliases
         std::unique_ptr<AstClause> noAlias = resolveAliases(*cur);
         // clean up equalities
         std::unique_ptr<AstClause> cleaned = removeTrivialEquality(*noAlias);
         // -- Step 2 --
         // restore simple terms in atoms
         removeComplexTermsInAtoms(*cleaned);
         // exchange rule
         program.removeClause(cur);
         program.appendClause(std::move(cleaned));
     }
 }
bool souffle::ResolveAliasesTransformer::transform (AstTranslationUnit & translationUnit) inline override private virtual
Implements souffle::AstTransformer.
Definition at line 42 of file AstTransforms.h.
References souffle::AstTranslationUnit::getProgram(), and resolveAliases().
{
         resolveAliases(*translationUnit.getProgram());
         return true;
     }
The documentation for this class was generated from the following files:
AstTransforms.h
AstTransforms.cpp