souffle: souffle::RamLoad Class Reference
souffle::RamLoad Class Reference
Load data into a relation.
#include <RamStatement.h>
Public Member Functions
RamLoad * clone () const override
Create clone.
const std::vector< IODirectives > & getIODirectives () const
void print (std::ostream &os, int tabpos) const override
Pretty print.
RamLoad (std::unique_ptr< RamRelation > rel, std::vector< IODirectives > ioDirectives)
Public Member Functions inherited from souffle::RamRelationStatement
void apply (const RamNodeMapper &map) override
Apply mapper.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamRelation & getRelation () const
Get RAM relation.
RamRelationStatement (RamNodeType type, std::unique_ptr< RamRelation > r)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Private Attributes
const std::vector< IODirectives > ioDirectives
Additional Inherited Members
Protected Member Functions inherited from souffle::RamRelationStatement
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr< RamRelation > relation
Relation.
Detailed Description
Load data into a relation.
Definition at line 126 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamLoad::RamLoad (std::unique_ptr< RamRelation > rel, std::vector< IODirectives > ioDirectives) inline
Definition at line 128 of file RamStatement.h.
Referenced by clone().
             : RamRelationStatement(RN_Load, std::move(rel)), ioDirectives(std::move(ioDirectives)) {}
Member Function Documentation
RamLoad* souffle::RamLoad::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 145 of file RamStatement.h.
References ioDirectives, RamLoad(), and souffle::RamRelationStatement::relation.
{
         RamLoad* res = new RamLoad(std::unique_ptr<RamRelation>(relation->clone()), ioDirectives);
         return res;
     }
const std::vector<IODirectives>& souffle::RamLoad::getIODirectives () const inline
Definition at line 131 of file RamStatement.h.
References ioDirectives.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalStmt(), and souffle::Synthesiser::generateCode().
{
         return ioDirectives;
     }
void souffle::RamLoad::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print.
Implements souffle::RamStatement.
Definition at line 136 of file RamStatement.h.
References souffle::RamRelation::getName(), souffle::RamRelationStatement::getRelation(), ioDirectives, and souffle::join().
{
         os << std::string(tabpos, '\t');
         os << "LOAD DATA FOR " << getRelation().getName() << " FROM {";
         os << join(ioDirectives, "], [",
                 [](std::ostream& out, const IODirectives& directives) { out << directives; });
         os << ioDirectives << "}";
     };
Field Documentation
const std::vector<IODirectives> souffle::RamLoad::ioDirectives private
Definition at line 151 of file RamStatement.h.
Referenced by clone(), getIODirectives(), and print().
The documentation for this class was generated from the following file:
RamStatement.h