souffle: souffle::concurrent_list< T > Class Template Reference
souffle::concurrent_list< T > Class Template Reference
A concurrent list data structure, which is implemented through a chunked linked-list.
#include <BlockList.h>
Data Structures
struct cv_data
Public Member Functions
T & at (size_t index) const
void clear ()
concurrent_list ()
concurrent_list (concurrent_list &&other)
concurrent_list & operator= (concurrent_list other)
T & operator[] (size_t index) const
void push_back (T val)
size_t size () const
the concept of size() in a threaded environment is peculiar However, it is guaranteed that the size returned is a valid index+1 if the data structure has not been concurrently reduced.
~concurrent_list ()
Private Attributes
std::atomic< cv_data * > cData
const size_t chunk_size = 1000
std::atomic< size_t > container_size
std::mutex writeMutex
Detailed Description
template<class T>
class souffle::concurrent_list< T >
A concurrent list data structure, which is implemented through a chunked linked-list.
On their own, get/push_back are threadsafe, however clearing/destructing is undefined behaviour if get/push_backs are in progress.
Definition at line 33 of file BlockList.h.
Constructor & Destructor Documentation
template<class T> souffle::concurrent_list< T >::concurrent_list () inline
Definition at line 54 of file BlockList.h.
                       {
         auto* curr = new cv_data;
         curr->m_size = 0;
         curr->m_data = new T[chunk_size];
         curr->next = nullptr;
         cData = curr;
         container_size = 0;
     }
template<class T> souffle::concurrent_list< T >::concurrent_list (concurrent_list< T > && other) inline
Definition at line 63 of file BlockList.h.
                                              : concurrent_list() {
         std::unique_lock<std::mutex> lk1(other.writeMutex);
         std::unique_lock<std::mutex> lk2(writeMutex);
         // no std::swap as atomics are unmoveable
         size_t tmp = this->container_size.load();
         this->container_size.store(other.container_size);
         other.container_size.store(tmp);
         // no std::swap as atomics are unmoveable
         cv_data* tmpPtr = this->cData.load();
         this->cData.store(other.cData);
         other.cData.store(tmpPtr);
     }
template<class T> souffle::concurrent_list< T >::~concurrent_list () inline
Definition at line 91 of file BlockList.h.
{
         // lock just to let writes finish
         std::unique_lock<std::mutex> lk(writeMutex);
         auto curr = cData.load();
         while (curr != nullptr) {
             cv_data* tmpnext = curr->next;
             delete[] curr->m_data;
             delete curr;
             curr = tmpnext;
         }
     }
Member Function Documentation
template<class T> T& souffle::concurrent_list< T >::at (size_t index) const inline
Definition at line 150 of file BlockList.h.
Referenced by souffle::BlockList< parent_t >::BlockList(), souffle::BlockList< parent_t >::clear(), and souffle::BlockList< parent_t >::~BlockList().
{
         return this->operator[](index);
     }
template<class T> void souffle::concurrent_list< T >::clear () inline
Definition at line 171 of file BlockList.h.
Referenced by souffle::BlockList< parent_t >::clear(), and souffle::BlockList< parent_t >::niptuck().
                  {
         std::unique_lock<std::mutex> lk(writeMutex);
         cv_data* curr = cData;
         while (curr != nullptr) {
             cv_data* tmpnext = curr->next;
             delete[] curr->m_data;
             delete curr;
             curr = tmpnext;
         }
         curr = new cv_data;
         curr->m_size = 0;
         curr->m_data = new T[chunk_size];
         curr->next = nullptr;
         container_size = 0;
         cData = curr;
     }
template<class T> concurrent_list& souffle::concurrent_list< T >::operator= (concurrent_list< T > other) inline
Definition at line 78 of file BlockList.h.
{
         size_t tmp = this->container_size.load();
         this->container_size.store(other.container_size);
         other.container_size.store(tmp);
         cv_data* tmpPtr = this->cData.load();
         this->cData.store(other.cData);
         other.cData.store(tmpPtr);
         return *this;
     }
template<class T> T& souffle::concurrent_list< T >::operator[] (size_t index) const inline
Definition at line 155 of file BlockList.h.
Referenced by souffle::concurrent_list< parent_t * >::at().
{
         if (index >= container_size) throw "invalid index";
         auto curr = cData.load();
         while (index >= chunk_size) {
             curr = curr->next.load();
             index -= chunk_size;
         }
         return curr->m_data[index];
     }
template<class T> void souffle::concurrent_list< T >::push_back (T val) inline
Definition at line 119 of file BlockList.h.
Referenced by souffle::BlockList< parent_t >::add(), souffle::BlockList< parent_t >::BlockList(), and souffle::BlockList< parent_t >::niptuck().
{
         std::unique_lock<std::mutex> lk(writeMutex);
         cv_data* curr = cData.load();
         // fast forward curr until non-null
         while (curr->next.load() != nullptr) curr = curr->next.load();
         cv_data* shadow = nullptr;
         cv_data* front = curr;
         // do we need to expand?
         if (curr->m_size == chunk_size) {
             shadow = new cv_data;
             shadow->m_size = 0;
             shadow->m_data = new T[chunk_size];
             shadow->next = nullptr;
             front = shadow;
         }
         front->m_data[front->m_size] = val;
         front->m_size += 1;
         if (shadow != nullptr) curr->next = shadow;
         container_size += 1;
     }
template<class T> size_t souffle::concurrent_list< T >::size () const inline
the concept of size() in a threaded environment is peculiar However, it is guaranteed that the size returned is a valid index+1 if the data structure has not been concurrently reduced.
Definition at line 110 of file BlockList.h.
Referenced by souffle::BlockList< parent_t >::BlockList(), souffle::BlockList< parent_t >::clear(), and souffle::BlockList< parent_t >::~BlockList().
{
         return container_size;
     }
Field Documentation
template<class T> std::atomic<cv_data*> souffle::concurrent_list< T >::cData private
Definition at line 51 of file BlockList.h.
Referenced by souffle::concurrent_list< parent_t * >::clear(), souffle::concurrent_list< parent_t * >::concurrent_list(), souffle::concurrent_list< parent_t * >::operator=(), souffle::concurrent_list< parent_t * >::operator[](), souffle::concurrent_list< parent_t * >::push_back(), and souffle::concurrent_list< parent_t * >::~concurrent_list().
template<class T> const size_t souffle::concurrent_list< T >::chunk_size = 1000 private
Definition at line 35 of file BlockList.h.
Referenced by souffle::concurrent_list< parent_t * >::clear(), souffle::concurrent_list< parent_t * >::concurrent_list(), souffle::concurrent_list< parent_t * >::operator[](), and souffle::concurrent_list< parent_t * >::push_back().
template<class T> std::atomic<size_t> souffle::concurrent_list< T >::container_size private
Definition at line 46 of file BlockList.h.
Referenced by souffle::concurrent_list< parent_t * >::clear(), souffle::concurrent_list< parent_t * >::concurrent_list(), souffle::concurrent_list< parent_t * >::operator=(), souffle::concurrent_list< parent_t * >::operator[](), souffle::concurrent_list< parent_t * >::push_back(), and souffle::concurrent_list< parent_t * >::size().
template<class T> std::mutex souffle::concurrent_list< T >::writeMutex mutable private
Definition at line 49 of file BlockList.h.
Referenced by souffle::concurrent_list< parent_t * >::clear(), souffle::concurrent_list< parent_t * >::concurrent_list(), souffle::concurrent_list< parent_t * >::push_back(), and souffle::concurrent_list< parent_t * >::~concurrent_list().
The documentation for this class was generated from the following file:
BlockList.h