souffle: souffle::DisjointSet::iterator Class Reference
souffle::DisjointSet::iterator Class Reference
iterator stuff
#include <UnionFind.h>
Public Member Functions
iterator (DisjointSet *ds, parent_t representative)
iterator (DisjointSet *ds, parent_t representative, bool)
iterator (DisjointSet *ds, bool isRepIter)
iterator (DisjointSet *ds, bool isRepIter, bool)
parent_t operator* ()
const parent_t operator* () const
iterator & operator++ (int)
iterator operator++ ()
Private Types
enum iterType { iterSubReps, iterReps }
Private Member Functions
void advance ()
parent_t yield () const
Private Attributes
iterType cType
DisjointSet * ds
BlockList< parent_t >::iterator memberIterator
std::unordered_map< parent_t,
BlockList< parent_t >
>::iterator repIter
Friends
bool operator!= (const iterator &x, const iterator &y)
bool operator== (const iterator &x, const iterator &y)
Detailed Description
iterator stuff
Definition at line 166 of file UnionFind.h.
Member Enumeration Documentation
enum souffle::DisjointSet::iterator::iterType private
Enumerator
iterSubReps
iterReps
Definition at line 174 of file UnionFind.h.
 { iterSubReps, iterReps };
Constructor & Destructor Documentation
souffle::DisjointSet::iterator::iterator (DisjointSet * ds, parent_t representative) inline
Definition at line 207 of file UnionFind.h.
                 : ds(ds), memberIterator(ds->repToSubords[representative].begin()), cType(iterSubReps){};
souffle::DisjointSet::iterator::iterator (DisjointSet * ds, parent_t representative, bool) inline
Definition at line 209 of file UnionFind.h.
                 : ds(ds), memberIterator(ds->repToSubords[representative].end()), cType(iterSubReps){};
souffle::DisjointSet::iterator::iterator (DisjointSet * ds, bool isRepIter) inline
Definition at line 212 of file UnionFind.h.
                 : ds(ds), repIter(ds->repToSubords.begin()), cType(iterReps){};
souffle::DisjointSet::iterator::iterator (DisjointSet * ds, bool isRepIter, bool) inline
Definition at line 214 of file UnionFind.h.
                 : ds(ds), repIter(ds->repToSubords.end()), cType(iterReps){};
Member Function Documentation
void souffle::DisjointSet::iterator::advance () inline private
Definition at line 179 of file UnionFind.h.
References cType, iterReps, iterSubReps, memberIterator, and repIter.
Referenced by operator++().
{
             switch (cType) {
                 case iterSubReps:
                     ++memberIterator;
                     break;
                 case iterReps:
                     ++repIter;
                     break;
                 default:
                     throw "invalid iterator type";
             }
         }
parent_t souffle::DisjointSet::iterator::operator* () inline
Definition at line 228 of file UnionFind.h.
References yield().
{
             return yield();
         }
const parent_t souffle::DisjointSet::iterator::operator* () const inline
Definition at line 232 of file UnionFind.h.
References yield().
{
             return yield();
         }
iterator& souffle::DisjointSet::iterator::operator++ (int) inline
Definition at line 217 of file UnionFind.h.
References advance().
{
             advance();
             return *this;
         }
iterator souffle::DisjointSet::iterator::operator++ () inline
Definition at line 222 of file UnionFind.h.
References advance().
{
             iterator ret(*this);
             advance();
             return ret;
         }
parent_t souffle::DisjointSet::iterator::yield () const inline private
Definition at line 192 of file UnionFind.h.
References cType, ds, iterReps, iterSubReps, memberIterator, souffle::DisjointSet::staleList(), and souffle::DisjointSet::staleMap().
Referenced by operator*().
{
             if (ds->staleList() || ds->staleMap()) throw "iterator modification exception";
             switch (cType) {
                 case iterSubReps:
                     return *memberIterator;
                 case iterReps:
                     return (*repIter).first;
                 default:
                     throw "invalid iterator type";
             }
         }
Friends And Related Function Documentation
bool operator!= (const iterator & x, const iterator & y) friend
Definition at line 249 of file UnionFind.h.
{
             return !(x == y);
         };
bool operator== (const iterator & x, const iterator & y) friend
Definition at line 236 of file UnionFind.h.
{
             switch (x.cType) {
                 case iterSubReps:
                     return y.cType == iterSubReps && x.memberIterator == y.memberIterator;
                 case iterReps:
                     return y.cType == iterReps && x.repIter == y.repIter;
                 default:
                     throw "invalid iterator type";
             }
         };
Field Documentation
iterType souffle::DisjointSet::iterator::cType private
Definition at line 176 of file UnionFind.h.
Referenced by advance(), and yield().
DisjointSet* souffle::DisjointSet::iterator::ds private
Definition at line 167 of file UnionFind.h.
Referenced by yield().
BlockList<parent_t>::iterator souffle::DisjointSet::iterator::memberIterator private
Definition at line 172 of file UnionFind.h.
Referenced by advance(), and yield().
std::unordered_map<parent_t, BlockList<parent_t> >::iterator souffle::DisjointSet::iterator::repIter private
Definition at line 170 of file UnionFind.h.
Referenced by advance().
The documentation for this class was generated from the following file:
UnionFind.h