souffle: souffle::BlockList< T > Class Template Reference
souffle::BlockList< T > Class Template Reference
A class that is designed to mimic std::list, but with better destructor speed It achieves this by allocating comparatively large chunks of memory as it needs This is not thread safe, except, when there is guarantee of at most one writer AND the TBB data structure is in use.
#include <BlockList.h>
Data Structures
class iterator
Public Member Functions
void add (const T &val)
Add a value to the blocklist.
template<>
void add (const std::atomic< block_t > &val)
iterator begin ()
BlockList ()
BlockList (const BlockList &other)
copy constructor
BlockList (BlockList &&other)
move constructor
void clear ()
Clear all elements from the BlockList.
iterator end ()
T & get (const size_t index) const
Retrieve a reference to the stored value at index.
void niptuck (BlockList &other)
Move the other list's elements here REMOVING them from the other Similar to std::list.splice()
BlockList & operator= (BlockList other)
T pop ()
Remove the last element from the data and destroying the block if its the last one in it.
size_t size () const
Size of List.
~BlockList ()
Private Attributes
souffle::concurrent_list< T * > listData
size_t m_size = 0
Detailed Description
template<class T>
class souffle::BlockList< T >
A class that is designed to mimic std::list, but with better destructor speed It achieves this by allocating comparatively large chunks of memory as it needs This is not thread safe, except, when there is guarantee of at most one writer AND the TBB data structure is in use.
Definition at line 208 of file BlockList.h.
Constructor & Destructor Documentation
template<class T> souffle::BlockList< T >::BlockList () inline
Definition at line 214 of file BlockList.h.
 : listData() {}
template<class T> souffle::BlockList< T >::BlockList (const BlockList< T > & other) inline
copy constructor
Definition at line 217 of file BlockList.h.
{
         size_t othblocks = other.listData.size();
         for (size_t i = 0; i < othblocks; ++i) {
             listData.push_back(new T[BLOCKSIZE]);
             memcpy(listData.at(i), other.listData.at(i), BLOCKSIZE);
         }
         this->m_size = other.m_size;
     }
template<class T> souffle::BlockList< T >::BlockList (BlockList< T > && other) inline
move constructor
Definition at line 227 of file BlockList.h.
                                  : BlockList() {
         std::swap(listData, other.listData);
         std::swap(m_size, other.m_size);
     }
template<class T> souffle::BlockList< T >::~BlockList () inline
Definition at line 238 of file BlockList.h.
                  {
         for (size_t i = 0; i < listData.size(); ++i) {
             T* r = listData.at(i);
             delete[] r;
         }
     }
Member Function Documentation
template<class T> void souffle::BlockList< T >::add (const T & val) inline
Add a value to the blocklist.
Parameters
val : value to be added
Definition at line 257 of file BlockList.h.
Referenced by souffle::DisjointSet::makeNode(), and souffle::BlockList< parent_t >::niptuck().
{
         // store it in the vector
         size_t blocknum = m_size >> BLOCKBITS;
         size_t blockindex = m_size & (BLOCKSIZE - 1);
         // we need to add a new block
         if (blockindex == 0) {
             this->listData.push_back(new T[BLOCKSIZE]);
         }
         this->listData[blocknum][blockindex] = T(val);
         ++m_size;
     }
template<> void souffle::BlockList< std::atomic< block_t > >::add (const std::atomic< block_t > & val) inline
Definition at line 414 of file BlockList.h.
References souffle::BLOCKBITS, and souffle::BLOCKSIZE.
{
     // store it in the vector
     size_t blocknum = m_size >> BLOCKBITS;
     size_t blockindex = m_size & (BLOCKSIZE - 1);
     // we need to add a new block
     if (blockindex == 0) {
         this->listData.push_back(new std::atomic<block_t>[BLOCKSIZE]);
     }
     // we need to assign inplace for atomics
     this->listData[blocknum][blockindex] = val.load();
     ++m_size;
 }
template<class T> iterator souffle::BlockList< T >::begin () inline
Definition at line 404 of file BlockList.h.
                      {
         return iterator(this);
     };
template<class T> void souffle::BlockList< T >::clear () inline
Clear all elements from the BlockList.
Definition at line 289 of file BlockList.h.
Referenced by souffle::DisjointSet::clear().
                  {
         for (size_t i = 0; i < listData.size(); ++i) {
             delete[] listData.at(i);
         }
         listData.clear();
         m_size = 0;
     }
template<class T> iterator souffle::BlockList< T >::end () inline
Definition at line 407 of file BlockList.h.
                    {
         return iterator(this, size());
     };
template<class T> T& souffle::BlockList< T >::get (const size_t index) const inline
Retrieve a reference to the stored value at index.
Parameters
index position to search
Returns
the value at index
Definition at line 277 of file BlockList.h.
Referenced by souffle::DisjointSet::get(), and souffle::BlockList< T >::iterator::operator*().
{
         if (index < 0 || index >= this->size()) throw std::runtime_error("out of bounds");
         size_t blocknum = index >> BLOCKBITS;
         size_t blockindex = index & (BLOCKSIZE - 1);
         return listData[blocknum][blockindex];
     }
template<class T> void souffle::BlockList< T >::niptuck (BlockList< T > & other) inline
Move the other list's elements here REMOVING them from the other Similar to std::list.splice()
Parameters
other the other list
Definition at line 330 of file BlockList.h.
{
         if (other.size() == 0) return;
         // fill up the remainder of this BLs last block with elements from the end of other's
         size_t requiredEmpties = BLOCKSIZE - (m_size & (BLOCKSIZE - 1));
         // we ignore the case of having to remove the entire block - its more efficient to do later
         if (requiredEmpties != BLOCKSIZE) {
             // pop and add
             for (size_t rem = requiredEmpties; rem > 0 && other.size() > 0; --rem) {
                 this->add(other.pop());
             }
         }
         // negative values mess up the shift
         if (other.size() == 0) {
             other.listData.clear();
             other.m_size = 0;
             return;
         }
         // if we have remainder, we've got to make sure that we simply plonk in the pointers
         // size-1, because BLOCKSIZE >> BLOCKBITS should equal 1
         size_t otherblocks = (other.m_size - 1) >> BLOCKBITS;
         ++otherblocks;
         for (size_t i = 0; i < otherblocks; ++i) {
             listData.push_back(other.listData[i]);
         }
         this->m_size += other.m_size;
         other.listData.clear();
         other.m_size = 0;
     }
template<class T> BlockList& souffle::BlockList< T >::operator= (BlockList< T > other) inline
Definition at line 232 of file BlockList.h.
{
         std::swap(this->listData, other.listData);
         std::swap(this->m_size, other.m_size);
         return *this;
     }
template<class T> T souffle::BlockList< T >::pop () inline
Remove the last element from the data and destroying the block if its the last one in it.
Returns
the copied value
Definition at line 302 of file BlockList.h.
Referenced by souffle::BlockList< parent_t >::niptuck().
             {
         if (m_size == 0) throw std::runtime_error("pop called on empty blocklist");
         --m_size;
         size_t blocknum = m_size >> BLOCKBITS;
         size_t blockindex = m_size & (BLOCKSIZE - 1);
         // we need to destroy the block - we're the last one standing
         if (blockindex == 0) {
             T retVal = listData[blocknum][blockindex];
             delete[] listData[blocknum];
             listData.pop_back();
             return retVal;
         } else {
             return listData[blocknum][blockindex];
         }
     }
template<class T> size_t souffle::BlockList< T >::size () const inline
Size of List.
Returns
the number of elements currently stored
Definition at line 249 of file BlockList.h.
Referenced by souffle::BlockList< parent_t >::end(), souffle::BlockList< parent_t >::get(), souffle::DisjointSet::makeNode(), souffle::BlockList< parent_t >::niptuck(), and souffle::DisjointSet::size().
{
         return m_size;
     };
Field Documentation
template<class T> souffle::concurrent_list<T*> souffle::BlockList< T >::listData private
Definition at line 209 of file BlockList.h.
Referenced by souffle::BlockList< parent_t >::add(), souffle::BlockList< parent_t >::BlockList(), souffle::BlockList< parent_t >::clear(), souffle::BlockList< parent_t >::get(), souffle::BlockList< parent_t >::niptuck(), souffle::BlockList< parent_t >::operator=(), souffle::BlockList< parent_t >::pop(), and souffle::BlockList< parent_t >::~BlockList().
template<class T> size_t souffle::BlockList< T >::m_size = 0 mutable private
Definition at line 211 of file BlockList.h.
Referenced by souffle::BlockList< parent_t >::add(), souffle::BlockList< parent_t >::BlockList(), souffle::BlockList< parent_t >::clear(), souffle::BlockList< parent_t >::niptuck(), souffle::BlockList< parent_t >::operator=(), souffle::BlockList< parent_t >::pop(), and souffle::BlockList< parent_t >::size().
The documentation for this class was generated from the following file:
BlockList.h