souffle: souffle::AstTypeCast Class Reference
souffle::AstTypeCast Class Reference
An argument capable of casting a value of one type into another.
#include <AstArgument.h>
Public Member Functions
void apply (const AstNodeMapper &map) override
Mutates this node.
AstTypeCast (std::unique_ptr< AstArgument > value, std::string type)
AstTypeCast * clone () const override
Creates a clone of this AST sub-structure.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
const std::string & getType () const
AstArgument * getValue () const
void print (std::ostream &os) const override
Output to a given output stream.
Public Member Functions inherited from souffle::AstArgument
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Private Attributes
std::string type
The target type name.
std::unique_ptr< AstArgument > value
The value to be casted.
Detailed Description
An argument capable of casting a value of one type into another.
Definition at line 603 of file AstArgument.h.
Constructor & Destructor Documentation
souffle::AstTypeCast::AstTypeCast (std::unique_ptr< AstArgument > value, std::string type) inline
Definition at line 611 of file AstArgument.h.
Referenced by clone().
             : value(std::move(value)), type(std::move(type)) {}
Member Function Documentation
void souffle::AstTypeCast::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 641 of file AstArgument.h.
References map, and value.
{
         value = map(std::move(value));
     }
AstTypeCast* souffle::AstTypeCast::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstArgument.
Definition at line 634 of file AstArgument.h.
References AstTypeCast(), souffle::AstNode::getSrcLoc(), type, and value.
{
         auto res = new AstTypeCast(std::unique_ptr<AstArgument>(value->clone()), type);
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstTypeCast::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 647 of file AstArgument.h.
References type, and value.
{
         assert(nullptr != dynamic_cast<const AstTypeCast*>(&node));
         const auto& other = static_cast<const AstTypeCast&>(node);
         return type == other.type && *value == *other.value;
     }
std::vector<const AstNode*> souffle::AstTypeCast::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Reimplemented from souffle::AstArgument.
Definition at line 627 of file AstArgument.h.
References souffle::AstArgument::getChildNodes(), and value.
{
         auto res = AstArgument::getChildNodes();
         res.push_back(value.get());
         return res;
     }
const std::string& souffle::AstTypeCast::getType () const inline
Definition at line 622 of file AstArgument.h.
References type.
{
         return type;
     }
AstArgument* souffle::AstTypeCast::getValue () const inline
Definition at line 618 of file AstArgument.h.
References value.
Referenced by souffle::BddBddBTranslator::visitTypeCast(), and souffle::LogicbloxConverter::visitTypeCast().
{
         return value.get();
     }
void souffle::AstTypeCast::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 614 of file AstArgument.h.
References type, and value.
{
         os << *value << " as " << type;
     }
Field Documentation
std::string souffle::AstTypeCast::type private
The target type name.
Definition at line 608 of file AstArgument.h.
Referenced by clone(), equal(), getType(), and print().
std::unique_ptr<AstArgument> souffle::AstTypeCast::value private
The value to be casted.
Definition at line 605 of file AstArgument.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getValue(), and print().
The documentation for this class was generated from the following file:
AstArgument.h