souffle: souffle::ram::detail::GenericRelation< config, arity, Indices > Class Template Reference
souffle::ram::detail::GenericRelation< config, arity, Indices > Class Template Reference
A generic relation type to customizable by some data structure configuration struct.
#include <CompiledRelation.h>
Data Structures
struct operation_context
Public Types
using iterator = decltype(std::declval< group_type >().template get< full_index >().begin())
Public Types inherited from souffle::ram::detail::RelationBase< arity, GenericRelation< config, arity, Indices...> >
using tuple_type = Tuple< RamDomain, arity >
Public Member Functions
iterator begin () const
bool contains (const tuple_type &tuple, operation_context &) const
operation_context createContext ()
bool empty () const
iterator end () const
template<typename I >
auto equalRange (const tuple_type &value, operation_context &) const -> decltype(indices.template equal_range< I >(value))
template<typename I >
auto equalRange (const tuple_type &value) const -> decltype(indices.template equal_range< I >(value))
template<unsigned... Columns>
auto equalRange (const tuple_type &value) const -> decltype(indices.template equal_range< index< Columns...>>(value))
template<unsigned... Columns>
auto equalRange (const tuple_type &value, operation_context &) const -> decltype(indices.template equal_range< index< Columns...>>(value))
bool insert (const tuple_type &tuple, operation_context &)
template<typename Setup , typename... Idxs>
void insertAll (const Relation< Setup, arity, Idxs...> &other)
std::vector< range< iterator > > partition () const
std::ostream & printDescription (std::ostream &out=std::cout) const
void purge ()
template<typename I >
range< iterator > scan () const
std::size_t size () const
Public Member Functions inherited from souffle::ram::detail::RelationBase< arity, GenericRelation< config, arity, Indices...> >
bool contains (Args...args) const
bool contains (const tuple_type &tuple) const
std::string getDescription () const
bool insert (Args...args)
bool insert (const RamDomain *ramDomain)
bool insert (const tuple_type &tuple)
void printHintStatistics (std::ostream &out, const std::string &prefix="") const
Private Types
using base = RelationBase< arity, GenericRelation< config, arity, Indices...>>
using full_index = typename index_utils::get_first_full_index< arity, Indices..., typename index_utils::get_full_index< arity >::type >::type
using group_type = typename std::conditional< index_utils::contains_full_index< arity, Indices...>::value, GenericRelationGroup< config, arity, Indices...>, GenericRelationGroup< config, arity, typename index_utils::get_full_index< arity >::type, Indices...>>::type
using main_index_type = typename std::remove_reference< decltype(std::declval< group_type >().template get< full_index >())>::type
using tuple_type = typename base::tuple_type
Private Member Functions
main_index_type & getMainIndex ()
const main_index_type & getMainIndex () const
Private Attributes
group_type indices
std::mutex lock
Detailed Description
template<typename config, unsigned arity, typename... Indices>
class souffle::ram::detail::GenericRelation< config, arity, Indices >
A generic relation type to customizable by some data structure configuration struct.
The relation type utilized to implement relations only utilizing a hash based data structure.
Definition at line 197 of file CompiledRelation.h.
Member Typedef Documentation
template<typename config , unsigned arity, typename... Indices> using souffle::ram::detail::GenericRelation< config, arity, Indices >::base = RelationBase<arity, GenericRelation<config, arity, Indices...>> private
Definition at line 1165 of file CompiledRelation.h.
template<typename config , unsigned arity, typename... Indices> using souffle::ram::detail::GenericRelation< config, arity, Indices >::full_index = typename index_utils::get_first_full_index<arity, Indices..., typename index_utils::get_full_index<arity>::type>::type private
Definition at line 1177 of file CompiledRelation.h.
template<typename config , unsigned arity, typename... Indices> using souffle::ram::detail::GenericRelation< config, arity, Indices >::group_type = typename std::conditional<index_utils::contains_full_index<arity, Indices...>::value, GenericRelationGroup<config, arity, Indices...>, GenericRelationGroup<config, arity, typename index_utils::get_full_index<arity>::type, Indices...>>::type private
Definition at line 1173 of file CompiledRelation.h.
template<typename config , unsigned arity, typename... Indices> using souffle::ram::detail::GenericRelation< config, arity, Indices >::iterator = decltype(std::declval<group_type>().template get<full_index>().begin())
Definition at line 1189 of file CompiledRelation.h.
template<typename config , unsigned arity, typename... Indices> using souffle::ram::detail::GenericRelation< config, arity, Indices >::main_index_type = typename std::remove_reference<decltype(std::declval<group_type>().template get<full_index>())>::type private
Definition at line 1180 of file CompiledRelation.h.
template<typename config , unsigned arity, typename... Indices> using souffle::ram::detail::GenericRelation< config, arity, Indices >::tuple_type = typename base::tuple_type private
Definition at line 1167 of file CompiledRelation.h.
Member Function Documentation
template<typename config , unsigned arity, typename... Indices> iterator souffle::ram::detail::GenericRelation< config, arity, Indices >::begin () const inline
Definition at line 1259 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::getMainIndex().
Referenced by souffle::ram::detail::GenericRelation< config, arity, Indices >::partition().
{
         return getMainIndex().begin();
     }
template<typename config , unsigned arity, typename... Indices> bool souffle::ram::detail::GenericRelation< config, arity, Indices >::contains (const tuple_type & tuple, operation_context &) const inline
Definition at line 1212 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::getMainIndex().
Referenced by souffle::ram::detail::GenericRelation< config, arity, Indices >::insert().
{
         return getMainIndex().contains(tuple);
     }
template<typename config , unsigned arity, typename... Indices> operation_context souffle::ram::detail::GenericRelation< config, arity, Indices >::createContext () inline
Definition at line 1200 of file CompiledRelation.h.
{
         return {};
     }
template<typename config , unsigned arity, typename... Indices> bool souffle::ram::detail::GenericRelation< config, arity, Indices >::empty () const inline
Definition at line 1204 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::getMainIndex().
{
         return getMainIndex().empty();
     }
template<typename config , unsigned arity, typename... Indices> iterator souffle::ram::detail::GenericRelation< config, arity, Indices >::end () const inline
Definition at line 1263 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::getMainIndex().
Referenced by souffle::ram::detail::GenericRelation< config, arity, Indices >::partition().
{
         return getMainIndex().end();
     }
template<typename config , unsigned arity, typename... Indices> template<typename I > auto souffle::ram::detail::GenericRelation< config, arity, Indices >::equalRange (const tuple_type & value, operation_context &) const -> decltype(indices.template equal_range<I>(value)) inline
Definition at line 1237 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::indices.
{
         return indices.template equal_range<I>(value);
     }
template<typename config , unsigned arity, typename... Indices> template<typename I > auto souffle::ram::detail::GenericRelation< config, arity, Indices >::equalRange (const tuple_type & value) const -> decltype(indices.template equal_range<I>(value)) inline
Definition at line 1243 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::indices.
{
         return indices.template equal_range<I>(value);
     }
template<typename config , unsigned arity, typename... Indices> template<unsigned... Columns> auto souffle::ram::detail::GenericRelation< config, arity, Indices >::equalRange (const tuple_type & value) const -> decltype(indices.template equal_range<index<Columns...>>(value)) inline
Definition at line 1248 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::indices.
{
         return indices.template equal_range<index<Columns...>>(value);
     }
template<typename config , unsigned arity, typename... Indices> template<unsigned... Columns> auto souffle::ram::detail::GenericRelation< config, arity, Indices >::equalRange (const tuple_type & value, operation_context &) const -> decltype(indices.template equal_range<index<Columns...>>(value)) inline
Definition at line 1254 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::indices.
{
         return indices.template equal_range<index<Columns...>>(value);
     }
template<typename config , unsigned arity, typename... Indices> main_index_type& souffle::ram::detail::GenericRelation< config, arity, Indices >::getMainIndex () inline private
Definition at line 1283 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::indices.
Referenced by souffle::ram::detail::GenericRelation< config, arity, Indices >::begin(), souffle::ram::detail::GenericRelation< config, arity, Indices >::contains(), souffle::ram::detail::GenericRelation< config, arity, Indices >::empty(), souffle::ram::detail::GenericRelation< config, arity, Indices >::end(), souffle::ram::detail::GenericRelation< config, arity, Indices >::scan(), and souffle::ram::detail::GenericRelation< config, arity, Indices >::size().
{
         return indices.template get<full_index>();
     }
template<typename config , unsigned arity, typename... Indices> const main_index_type& souffle::ram::detail::GenericRelation< config, arity, Indices >::getMainIndex () const inline private
Definition at line 1287 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::indices.
{
         return indices.template get<full_index>();
     }
template<typename config , unsigned arity, typename... Indices> bool souffle::ram::detail::GenericRelation< config, arity, Indices >::insert (const tuple_type & tuple, operation_context &) inline
Definition at line 1216 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::contains(), souffle::ram::detail::GenericRelation< config, arity, Indices >::indices, and souffle::ram::detail::GenericRelation< config, arity, Indices >::lock.
Referenced by souffle::ram::detail::GenericRelation< config, arity, Indices >::insertAll().
{
         std::lock_guard<std::mutex> guard(lock);
         if (contains(tuple)) return false;
         indices.insert(tuple);
         return true;
     }
template<typename config , unsigned arity, typename... Indices> template<typename Setup , typename... Idxs> void souffle::ram::detail::GenericRelation< config, arity, Indices >::insertAll (const Relation< Setup, arity, Idxs...> & other) inline
Definition at line 1224 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::insert().
{
         for (const tuple_type& cur : other) {
             insert(cur);
         }
     }
template<typename config , unsigned arity, typename... Indices> std::vector<range<iterator> > souffle::ram::detail::GenericRelation< config, arity, Indices >::partition () const inline
Definition at line 1271 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::begin(), souffle::ram::detail::GenericRelation< config, arity, Indices >::end(), and souffle::range< Iter >::partition().
{
         range<iterator> full(begin(), end());
         return full.partition(100);
     }
template<typename config , unsigned arity, typename... Indices> std::ostream& souffle::ram::detail::GenericRelation< config, arity, Indices >::printDescription (std::ostream & out = std::cout) const inline
Definition at line 1277 of file CompiledRelation.h.
References arity, and souffle::getName.
{
         out << config::getName() << "-based relaton of arity=" << arity;
         return out;
     }
template<typename config , unsigned arity, typename... Indices> void souffle::ram::detail::GenericRelation< config, arity, Indices >::purge () inline
Definition at line 1267 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::indices.
                  {
         indices.clear();
     }
template<typename config , unsigned arity, typename... Indices> template<typename I > range<iterator> souffle::ram::detail::GenericRelation< config, arity, Indices >::scan () const inline
Definition at line 1231 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::getMainIndex().
{
         const auto& index = getMainIndex();
         return {index.begin(), index.end()};
     }
template<typename config , unsigned arity, typename... Indices> std::size_t souffle::ram::detail::GenericRelation< config, arity, Indices >::size () const inline
Definition at line 1208 of file CompiledRelation.h.
References souffle::ram::detail::GenericRelation< config, arity, Indices >::getMainIndex().
{
         return getMainIndex().size();
     }
Field Documentation
template<typename config , unsigned arity, typename... Indices> group_type souffle::ram::detail::GenericRelation< config, arity, Indices >::indices private
Definition at line 1183 of file CompiledRelation.h.
Referenced by souffle::ram::detail::GenericRelation< config, arity, Indices >::equalRange(), souffle::ram::detail::GenericRelation< config, arity, Indices >::getMainIndex(), souffle::ram::detail::GenericRelation< config, arity, Indices >::insert(), and souffle::ram::detail::GenericRelation< config, arity, Indices >::purge().
template<typename config , unsigned arity, typename... Indices> std::mutex souffle::ram::detail::GenericRelation< config, arity, Indices >::lock private
Definition at line 1186 of file CompiledRelation.h.
Referenced by souffle::ram::detail::GenericRelation< config, arity, Indices >::insert().
The documentation for this class was generated from the following file:
CompiledRelation.h