souffle: souffle::DisjointSet Class Reference
souffle::DisjointSet Class Reference
Structure that emulates a Disjoint Set, i.e.
#include <UnionFind.h>
Data Structures
class iterator
iterator stuff
Public Member Functions
iterator begin (parent_t rep)
iterator beginReps ()
void clear ()
Clears the DisjointSet of all nodes Invalidates all iterators.
DisjointSet ()
iterator end (parent_t rep)
iterator endReps ()
void findAll ()
Performs a find operation on every node s.t.
parent_t findNode (parent_t x, bool isStrong=true)
Equivalent to the find() function in union/find Find the highest ancestor of the provided node - flattening as we go.
void genMap ()
Generate representative->group map for all elements in the disjoint set Keys of the map are the representatives Values are the representative's children.
std::atomic< block_t > & get (parent_t node) const
Yield reference to the node by its node index.
block_t makeNode ()
Create a node with its parent as itself, rank 0.
size_t numInSet (parent_t rep)
DisjointSet & operator= (const DisjointSet &old)
parent_t readOnlyFindNode (parent_t x) const
Read only version of findNode i.e.
bool sameSet (parent_t x, parent_t y)
Check whether the two indices are in the same set.
size_t size () const
bool staleList () const
bool staleMap () const
void unionNodes (parent_t x, parent_t y)
Union the two specified index nodes.
Static Public Member Functions
static parent_t b2p (const block_t inblock)
Ï Extract parent from block.
static rank_t b2r (const block_t inblock)
Extract rank from block.
static block_t pr2b (const parent_t parent, const rank_t rank)
Yield a block given parent and rank.
Private Member Functions
bool updateRoot (const parent_t x, const rank_t oldrank, const parent_t y, const rank_t newrank, bool isStrong)
Update the root of the tree of which x is, to have y as the base instead.
Private Attributes
BlockList< std::atomic< block_t > > a_blocks
std::atomic< bool > isStale
souffle::shared_mutex mapLock
std::atomic< bool > mapStale
souffle::shared_mutex nodeLock
std::unordered_map< parent_t,
BlockList< parent_t > > repToSubords
Detailed Description
Structure that emulates a Disjoint Set, i.e.
a data structure that supports efficient union-find operations
Definition at line 43 of file UnionFind.h.
Constructor & Destructor Documentation
souffle::DisjointSet::DisjointSet () inline
Definition at line 59 of file UnionFind.h.
 : isStale(true), mapStale(true){};
Member Function Documentation
static parent_t souffle::DisjointSet::b2p (const block_t inblock) inline static
Ï Extract parent from block.
Parameters
inblock the block to be masked
Returns
The parent_t contained in the upper half of block_t
Definition at line 427 of file UnionFind.h.
References souffle::split_size.
Referenced by findNode(), genMap(), readOnlyFindNode(), sameSet(), and updateRoot().
{
         return (parent_t)(inblock >> split_size);
     };
static rank_t souffle::DisjointSet::b2r (const block_t inblock) inline static
Extract rank from block.
Parameters
inblock the block to be masked
Returns
the rank_t contained in the lower half of block_t
Definition at line 436 of file UnionFind.h.
References souffle::rank_mask.
Referenced by findNode(), unionNodes(), and updateRoot().
{
         return (rank_t)(inblock & rank_mask);
     };
iterator souffle::DisjointSet::begin (parent_t rep) inline
Definition at line 270 of file UnionFind.h.
References genMap().
{
         this->genMap();
         return iterator(this, rep);
     };
iterator souffle::DisjointSet::beginReps () inline
Definition at line 260 of file UnionFind.h.
References genMap().
{
         this->genMap();
         return iterator(this, true);
     };
void souffle::DisjointSet::clear () inline
Clears the DisjointSet of all nodes Invalidates all iterators.
Definition at line 283 of file UnionFind.h.
References a_blocks, souffle::BlockList< T >::clear(), isStale, souffle::shared_mutex::lock(), mapStale, nodeLock, repToSubords, and souffle::shared_mutex::unlock().
Referenced by souffle::SparseDisjointSet< DomainInt >::clear().
                  {
         // Warning! Not threadsafe..
         nodeLock.lock();
         isStale = true;
         mapStale = true;
         repToSubords.clear();
         a_blocks.clear();
         nodeLock.unlock();
     }
iterator souffle::DisjointSet::end (parent_t rep) inline
Definition at line 274 of file UnionFind.h.
References genMap().
{
         this->genMap();
         return iterator(this, rep, true);
     };
iterator souffle::DisjointSet::endReps () inline
Definition at line 264 of file UnionFind.h.
References genMap().
{
         this->genMap();
         return iterator(this, true, true);
     };
void souffle::DisjointSet::findAll () inline
Performs a find operation on every node s.t.
all nodes have a direct ref to their set's representative This is only performed if necessary.
Definition at line 349 of file UnionFind.h.
References findNode(), i, isStale, and size().
Referenced by genMap().
                    {
         if (isStale) {
             // TODO: check whether we should use strong=false/true in findNode args
             for (parent_t i = 0; i < size(); ++i) findNode(i);
             isStale.store(false);
         }
     }
parent_t souffle::DisjointSet::findNode (parent_t x, bool isStrong = true) inline
Equivalent to the find() function in union/find Find the highest ancestor of the provided node - flattening as we go.
Parameters
x the node to find the parent of, whilst flattening its set-tree
Returns
The parent of x
Definition at line 103 of file UnionFind.h.
References b2p(), b2r(), isStale, mapStale, pr2b(), and x.
Referenced by findAll(), souffle::SparseDisjointSet< DomainInt >::findNode(), sameSet(), and unionNodes().
{
         // If x is its own parent return immediately
         if (x == b2p(get(x))) {
             return x;
         }
         isStale.store(true);
         mapStale.store(true);
         block_t xState = get(x);
         parent_t newParent = findNode(b2p(xState));
         block_t newState = pr2b(newParent, b2r(xState));
         if (isStrong)
             this->get(x).compare_exchange_strong(xState, newState);
         else
             this->get(x).compare_exchange_weak(xState, newState);
         return newParent;
     }
void souffle::DisjointSet::genMap () inline
Generate representative->group map for all elements in the disjoint set Keys of the map are the representatives Values are the representative's children.
Definition at line 389 of file UnionFind.h.
References b2p(), findAll(), i, souffle::shared_mutex::lock(), mapLock, mapStale, repToSubords, size(), and souffle::shared_mutex::unlock().
Referenced by begin(), beginReps(), end(), endReps(), and numInSet().
                   {
         if (mapStale) {
             mapLock.lock();
             if (!mapStale) {
                 mapLock.unlock();
                 return;
             }
             findAll();
             mapStale.store(false);
             repToSubords.clear();
             for (parent_t i = 0; i < size(); ++i) {
                 repToSubords[b2p(this->get(i))].add(i);
             }
             mapLock.unlock();
         }
     }
std::atomic<block_t>& souffle::DisjointSet::get (parent_t node) const inline
Yield reference to the node by its node index.
Parameters
node node to be searched
Returns
the parent block of the specified node
Definition at line 91 of file UnionFind.h.
References a_blocks, and souffle::BlockList< T >::get().
{
         auto& ret = a_blocks.get(node);
         return ret;
     };
block_t souffle::DisjointSet::makeNode () inline
Create a node with its parent as itself, rank 0.
Returns
the newly created block
Definition at line 362 of file UnionFind.h.
References a_blocks, souffle::BlockList< T >::add(), isStale, souffle::shared_mutex::lock(), mapStale, nodeLock, pr2b(), souffle::BlockList< T >::size(), souffle::shared_mutex::unlock(), and x.
Referenced by souffle::SparseDisjointSet< DomainInt >::toDense().
{
         nodeLock.lock();
         isStale.store(true);
         mapStale.store(true);
         // its parent is itself (size indicates the position in the listData structure)
         auto xpar = (parent_t)a_blocks.size();
         rank_t xrank = 0;
         block_t x = pr2b(xpar, xrank);
         a_blocks.add(x);
         isStale.store(true);
         mapStale.store(true);
         nodeLock.unlock();
         return x;
     };
size_t souffle::DisjointSet::numInSet (parent_t rep) inline
Definition at line 411 of file UnionFind.h.
References genMap(), souffle::shared_mutex::lock_shared(), mapLock, repToSubords, and souffle::shared_mutex::unlock_shared().
Referenced by souffle::SparseDisjointSet< DomainInt >::sizeOfRepresentativeSet().
{
         // we may not have an up to date map underneath
         genMap();
         mapLock.lock_shared();
         auto sz = repToSubords.at(rep).size();
         mapLock.unlock_shared();
         return sz;
     };
DisjointSet& souffle::DisjointSet::operator= (const DisjointSet & old) inline
Definition at line 62 of file UnionFind.h.
References a_blocks, isStale, mapStale, and repToSubords.
{
         if (this == &old) return *this;
         a_blocks = old.a_blocks;
         repToSubords = old.repToSubords;
         isStale.store(old.isStale.load());
         mapStale.store(old.mapStale.load());
         return *this;
     }
static block_t souffle::DisjointSet::pr2b (const parent_t parent, const rank_t rank) inline static
Yield a block given parent and rank.
Parameters
parent the top half bits
rank the lower half bits
Returns
the resultant block after merge
Definition at line 446 of file UnionFind.h.
References souffle::split_size.
Referenced by findNode(), makeNode(), and updateRoot().
{
         return (((block_t)parent) << split_size) | rank;
     };
parent_t souffle::DisjointSet::readOnlyFindNode (parent_t x) const inline
Read only version of findNode i.e.
it doesn't compress the tree when searching - it only finds the top representative
Parameters
x the node to find the rep of
Returns
the representative that is found
Definition at line 130 of file UnionFind.h.
References b2p(), p, and x.
Referenced by souffle::SparseDisjointSet< DomainInt >::readOnlyFindNode(), and souffle::SparseDisjointSet< DomainInt >::sizeOfRepresentativeSet().
{
         block_t ii = get(x);
         parent_t p = b2p(ii);
         if (x == p) return x;
         return readOnlyFindNode(p);
     }
bool souffle::DisjointSet::sameSet (parent_t x, parent_t y) inline
Check whether the two indices are in the same set.
Parameters
x node to be checked
y node to be checked
Returns
where the two indices are in the same set
Definition at line 303 of file UnionFind.h.
References b2p(), and findNode().
Referenced by souffle::SparseDisjointSet< DomainInt >::sameSet().
{
         while (true) {
             x = findNode(x, false);
             y = findNode(y, false);
             if (x == y) return true;
             // if x's parent is itself, they are not the same set
             if (b2p(get(x)) == x) return false;
         }
     }
size_t souffle::DisjointSet::size () const inline
Definition at line 73 of file UnionFind.h.
References a_blocks, and souffle::BlockList< T >::size().
Referenced by findAll(), genMap(), and souffle::SparseDisjointSet< DomainInt >::size().
{
         auto sz = a_blocks.size();
         return sz;
     };
bool souffle::DisjointSet::staleList () const inline
Definition at line 78 of file UnionFind.h.
References isStale.
Referenced by souffle::DisjointSet::iterator::yield().
{
         return isStale;
     };
bool souffle::DisjointSet::staleMap () const inline
Definition at line 82 of file UnionFind.h.
References mapStale.
Referenced by souffle::DisjointSet::iterator::yield().
{
         return mapStale;
     };
void souffle::DisjointSet::unionNodes (parent_t x, parent_t y) inline
Union the two specified index nodes.
Parameters
x node to be unioned
y node to be unioned
Definition at line 318 of file UnionFind.h.
References b2r(), findNode(), isStale, mapStale, and updateRoot().
Referenced by souffle::SparseDisjointSet< DomainInt >::unionNodes().
{
         while (true) {
             x = findNode(x, false);
             y = findNode(y, false);
             // no need to union if both already in same set
             if (x == y) return;
             isStale.store(true);
             mapStale.store(true);
             rank_t xrank = b2r(get(x));
             rank_t yrank = b2r(get(y));
             // if x comes before y (better rank or earlier & equal node)
             if (xrank > yrank || ((xrank == yrank) && x > y)) {
                 std::swap(x, y);
                 std::swap(xrank, yrank);
             }
             // join the trees together
             // perhaps we can optimise the use of compare_exchange_strong here, as we're in a pessimistic loop
             if (!updateRoot(x, xrank, y, yrank, true)) continue;
             if (xrank == yrank) updateRoot(y, yrank, y, yrank + 1, false);
             break;
         }
     }
bool souffle::DisjointSet::updateRoot (const parent_t x, const rank_t oldrank, const parent_t y, const rank_t newrank, bool isStrong) inline private
Update the root of the tree of which x is, to have y as the base instead.
Parameters
x : old root
oldrank : old root rank
y : new root
newrank : new root rank
Returns
Whether the update succeeded (fails if another root update/union has been perfomed in the interim)
Definition at line 147 of file UnionFind.h.
References b2p(), b2r(), isStale, mapStale, pr2b(), and x.
Referenced by unionNodes().
{
         isStale.store(true);
         mapStale.store(true);
         block_t oldState = get(x);
         parent_t nextN = b2p(oldState);
         rank_t rankN = b2r(oldState);
         if (nextN != x || rankN != oldrank) return false;
         // set the parent and rank of the new record
         block_t newVal = pr2b(y, newrank);
         if (isStrong) return this->get(x).compare_exchange_strong(oldState, newVal);
         return this->get(x).compare_exchange_weak(oldState, newVal);
     }
Field Documentation
BlockList<std::atomic<block_t> > souffle::DisjointSet::a_blocks private
Definition at line 45 of file UnionFind.h.
Referenced by clear(), get(), makeNode(), operator=(), and size().
std::atomic<bool> souffle::DisjointSet::isStale private
Definition at line 51 of file UnionFind.h.
Referenced by clear(), findAll(), findNode(), makeNode(), operator=(), staleList(), unionNodes(), and updateRoot().
souffle::shared_mutex souffle::DisjointSet::mapLock mutable private
Definition at line 55 of file UnionFind.h.
Referenced by genMap(), and numInSet().
std::atomic<bool> souffle::DisjointSet::mapStale private
Definition at line 52 of file UnionFind.h.
Referenced by clear(), findNode(), genMap(), makeNode(), operator=(), staleMap(), unionNodes(), and updateRoot().
souffle::shared_mutex souffle::DisjointSet::nodeLock mutable private
Definition at line 48 of file UnionFind.h.
Referenced by clear(), and makeNode().
std::unordered_map<parent_t, BlockList<parent_t> > souffle::DisjointSet::repToSubords private
Definition at line 56 of file UnionFind.h.
Referenced by clear(), genMap(), numInSet(), and operator=().
The documentation for this class was generated from the following file:
UnionFind.h