souffle: souffle::RamCreate Class Reference
souffle::RamCreate Class Reference
Create new RAM relation.
#include <RamStatement.h>
Public Member Functions
RamCreate * clone () const override
Create clone.
void print (std::ostream &os, int tabpos) const override
Pretty print.
RamCreate (std::unique_ptr< RamRelation > rel)
Public Member Functions inherited from souffle::RamRelationStatement
void apply (const RamNodeMapper &map) override
Apply mapper.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamRelation & getRelation () const
Get RAM relation.
RamRelationStatement (RamNodeType type, std::unique_ptr< RamRelation > r)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Additional Inherited Members
Protected Member Functions inherited from souffle::RamRelationStatement
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr< RamRelation > relation
Relation.
Detailed Description
Create new RAM relation.
Definition at line 94 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamCreate::RamCreate (std::unique_ptr< RamRelation > rel) inline
Definition at line 96 of file RamStatement.h.
Referenced by clone().
 : RamRelationStatement(RN_Create, std::move(rel)) {}
Member Function Documentation
RamCreate* souffle::RamCreate::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 117 of file RamStatement.h.
References RamCreate(), and souffle::RamRelationStatement::relation.
{
         RamCreate* res = new RamCreate(std::unique_ptr<RamRelation>(relation->clone()));
         return res;
     }
void souffle::RamCreate::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print.
Implements souffle::RamStatement.
Definition at line 99 of file RamStatement.h.
References souffle::RamRelation::getArg(), souffle::RamRelation::getArity(), souffle::RamRelation::getName(), souffle::RamRelationStatement::getRelation(), and i.
{
         // TODO (#541): add type information for attributes
         os << std::string(tabpos, '\t');
         os << "CREATE " << getRelation().getName() << "(";
         os << getRelation().getArg(0);
         for (size_t i = 1; i < getRelation().getArity(); i++) {
             os << ",";
             os << getRelation().getArg(i);
         }
         os << ")";
         if (getRelation().isBTree()) os << " btree";
         if (getRelation().isRbtset()) os << " rbtset";
         if (getRelation().isHashset()) os << " hashset";
         if (getRelation().isBrie()) os << " brie";
         if (getRelation().isEqRel()) os << " eqrel";
     };
The documentation for this class was generated from the following file:
RamStatement.h