souffle: souffle::RamNumber Class Reference
souffle::RamNumber Class Reference
Number Constant.
#include <RamValue.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamNumber * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
RamDomain getConstant () const
Get constant.
size_t getLevel () const override
Get level.
void print (std::ostream &os) const override
Print.
RamNumber (RamDomain c)
Public Member Functions inherited from souffle::RamValue
bool isConstant () const
Determines whether this value is a constant or not.
RamValue (RamNodeType type, bool isCnst)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
RamDomain constant
Constant value.
Additional Inherited Members
Protected Attributes inherited from souffle::RamValue
bool cnst
Detailed Description
Number Constant.
Definition at line 381 of file RamValue.h.
Constructor & Destructor Documentation
souffle::RamNumber::RamNumber (RamDomain c) inline
Definition at line 386 of file RamValue.h.
Referenced by clone().
 : RamValue(RN_Number, true), constant(c) {}
Member Function Documentation
void souffle::RamNumber::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 417 of file RamValue.h.
 {}
RamNumber* souffle::RamNumber::clone () const inline override virtual
Create clone.
Implements souffle::RamValue.
Definition at line 411 of file RamValue.h.
References constant, and RamNumber().
{
         auto* res = new RamNumber(constant);
         return res;
     }
bool souffle::RamNumber::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 421 of file RamValue.h.
References getConstant().
{
         assert(nullptr != dynamic_cast<const RamNumber*>(&node));
         const auto& other = static_cast<const RamNumber&>(node);
         return getConstant() == other.getConstant();
     }
std::vector<const RamNode*> souffle::RamNumber::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 406 of file RamValue.h.
{
         return std::vector<const RamNode*>();  // no child nodes
     }
RamDomain souffle::RamNumber::getConstant () const inline
Get constant.
Definition at line 390 of file RamValue.h.
References constant.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalVal().
{
         return constant;
     }
size_t souffle::RamNumber::getLevel () const inline override virtual
Get level.
Implements souffle::RamValue.
Definition at line 401 of file RamValue.h.
{
         return 0;
     }
void souffle::RamNumber::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 395 of file RamValue.h.
References constant.
{
         os << "number(" << constant << ")";
     }
Field Documentation
RamDomain souffle::RamNumber::constant private
Constant value.
Definition at line 383 of file RamValue.h.
Referenced by clone(), getConstant(), and print().
The documentation for this class was generated from the following file:
RamValue.h