souffle: souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper Class Reference
souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper Class Reference
Public Member Functions
iterator_base * clone () const override
iterator_wrapper (uint32_t arg_id, const Relation *rel, const typename RelType::iterator &arg_it)
tuple & operator* () override
void operator++ () override
Protected Member Functions
bool equal (const iterator_base &o) const override
Private Attributes
RelType::iterator it
const Relation * relation
tuple t
Detailed Description
template<uint32_t id, class RelType, class TupleType, size_t Arity, bool IsInputRel, bool IsOutputRel>
class souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper
Definition at line 80 of file CompiledSouffle.h.
Constructor & Destructor Documentation
template<uint32_t id, class RelType , class TupleType , size_t Arity, bool IsInputRel, bool IsOutputRel> souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::iterator_wrapper (uint32_t arg_id, const Relation * rel, const typename RelType::iterator & arg_it) inline
Definition at line 86 of file CompiledSouffle.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::clone().
                 : iterator_base(arg_id), it(arg_it), relation(rel), t(rel) {}
Member Function Documentation
template<uint32_t id, class RelType , class TupleType , size_t Arity, bool IsInputRel, bool IsOutputRel> iterator_base* souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::clone () const inline override
Definition at line 98 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::iterator_wrapper().
{
             return new iterator_wrapper(*this);
         }
template<uint32_t id, class RelType , class TupleType , size_t Arity, bool IsInputRel, bool IsOutputRel> bool souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::equal (const iterator_base & o) const inline override protected
Definition at line 103 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::it, and o.
{
             const auto& casted = static_cast<const iterator_wrapper&>(o);
             return it == casted.it;
         }
template<uint32_t id, class RelType , class TupleType , size_t Arity, bool IsInputRel, bool IsOutputRel> tuple& souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::operator* () inline override
Definition at line 91 of file CompiledSouffle.h.
References i, souffle::tuple::rewind(), and souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::t.
{
             t.rewind();
             for (size_t i = 0; i < Arity; i++) {
                 t[i] = (*it)[i];
             }
             return t;
         }
template<uint32_t id, class RelType , class TupleType , size_t Arity, bool IsInputRel, bool IsOutputRel> void souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::operator++ () inline override
Definition at line 88 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::it.
{
             ++it;
         }
Field Documentation
template<uint32_t id, class RelType , class TupleType , size_t Arity, bool IsInputRel, bool IsOutputRel> RelType::iterator souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::it private
Definition at line 81 of file CompiledSouffle.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::equal(), and souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::operator++().
template<uint32_t id, class RelType , class TupleType , size_t Arity, bool IsInputRel, bool IsOutputRel> const Relation* souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::relation private
Definition at line 82 of file CompiledSouffle.h.
template<uint32_t id, class RelType , class TupleType , size_t Arity, bool IsInputRel, bool IsOutputRel> tuple souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::t private
Definition at line 83 of file CompiledSouffle.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity, IsInputRel, IsOutputRel >::iterator_wrapper::operator*().
The documentation for this class was generated from the following file:
CompiledSouffle.h