souffle: souffle::BinaryRelation< TupleType > Class Template Reference
souffle::BinaryRelation< TupleType > Class Template Reference
#include <BinaryRelation.h>
Data Structures
class iterator
struct operation_hints
TODO: implement this operation_hint class A collection of operation hints speeding up some of the involved operations by exploiting temporal locality.
Public Member Functions
iterator begin () const
iterator pointing to the beginning of the tuples, with no restrictions
void clear ()
iterator closure (DomainInt rep) const
Begin an iterator over all pairs within a single disjoint set.
bool contains (DomainInt x, DomainInt y) const
Returns whether there exists a pair with these two nodes.
iterator end () const
iterator pointing to the end of the tuples
void extend (const BinaryRelation< TupleType > &other)
iterator find (const TupleType &start) const
Begin an iterator at the requested point.
iterator findBetween (const TupleType &start, const TupleType &end) const
Begin an iterator at/after the requested point, and mark it to finish at/before the specified one.
iterator frontProduct (std::list< DomainInt > start) const
Begin an iterator which generates all pairs (X, Y) s.t.
template<unsigned levels>
range< iterator > getBoundaries (const operation_hints &entry) const
Obtains a range of elements matching the prefix of the given entry up to levels elements.
template<unsigned levels>
range< iterator > getBoundaries (const TupleType &entry, operation_hints &ctxt) const
Obtains a range of elements matching the prefix of the given entry up to levels elements.
bool insert (DomainInt x, DomainInt y)
Insert the two values symbolically as a binary relation.
bool insert (DomainInt x, DomainInt y, operation_hints z)
Insert the two values symbolically as a binary relation.
void insertAll (const BinaryRelation< TupleType > &other)
inserts all nodes from the other relation into this one
BinaryRelation & operator= (const BinaryRelation &old)
std::vector< souffle::range
< iterator > > partition (size_t chunks) const
Generate an approximate number of iterators for parallel iteration The iterators returned are not necessarily equal in size, but in practise are approximately similarly sized Depending on the structure of the data, there can be more or less partitions returned than requested.
size_t size () const
Size of relation.
Protected Member Functions
bool containsElement (DomainInt e) const
Private Types
enum { arity = TupleType::arity }
using DomainInt = typename TupleType::value_type
Private Member Functions
std::shared_ptr< souffle::Trie< 1 > > generateTrieIfNone (DomainInt val) const
Create a trie which contains the disjoint set which contains this value.
Private Attributes
std::unordered_map< DomainInt,
std::shared_ptr< souffle::Trie< 1 > > > orderedStates
SparseDisjointSet< DomainInt > sds
souffle::shared_mutex statesLock
Detailed Description
template<typename TupleType>
class souffle::BinaryRelation< TupleType >
Definition at line 26 of file BinaryRelation.h.
Member Typedef Documentation
template<typename TupleType> using souffle::BinaryRelation< TupleType >::DomainInt = typename TupleType::value_type private
Definition at line 27 of file BinaryRelation.h.
Member Enumeration Documentation
template<typename TupleType> anonymous enum private
Enumerator
arity
Definition at line 28 of file BinaryRelation.h.
 { arity = TupleType::arity };
Member Function Documentation
template<typename TupleType> iterator souffle::BinaryRelation< TupleType >::begin () const inline
iterator pointing to the beginning of the tuples, with no restrictions
Returns
the iterator that corresponds to the beginning of the binary relation
Definition at line 595 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::getBoundaries(), and souffle::BinaryRelation< tuple_type >::partition().
{
         // generate tries for all disjoint sets
         for (auto rep = sds.beginReps(); rep != sds.endReps(); ++rep) {
             generateTrieIfNone(*rep);
         }
         return iterator(this);
     }
template<typename TupleType> void souffle::BinaryRelation< TupleType >::clear () inline
Definition at line 148 of file BinaryRelation.h.
                  {
         statesLock.lock();
         // we should be able to clear this prior, as it requires a lock on its own
         sds.clear();
         orderedStates.clear();
         statesLock.unlock();
     }
template<typename TupleType> iterator souffle::BinaryRelation< TupleType >::closure (DomainInt rep) const inline
Begin an iterator over all pairs within a single disjoint set.
Parameters
rep the representative of (or element within) a disjoint set of which to generate all pairs
Returns
an iterator that will generate all pairs within the disjoint set
Definition at line 741 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::partition().
{
         // the trie that contains this rep
         auto trie = generateTrieIfNone(rep);
         return iterator(this, rep, trie);
     }
template<typename TupleType> bool souffle::BinaryRelation< TupleType >::contains (DomainInt x, DomainInt y) const inline
Returns whether there exists a pair with these two nodes.
Parameters
x front of pair
y back of pair
Definition at line 144 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::insert().
{
         return sds.contains(x, y);
     }
template<typename TupleType> bool souffle::BinaryRelation< TupleType >::containsElement (DomainInt e) const inline protected
Definition at line 134 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::extend().
{
         return this->sds.nodeExists(e);
     }
template<typename TupleType> iterator souffle::BinaryRelation< TupleType >::end () const inline
iterator pointing to the end of the tuples
Returns
the iterator which represents the end of the binary rel
Definition at line 608 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::getBoundaries(), and souffle::BinaryRelation< tuple_type >::partition().
{
         return iterator(true, this);
     }
template<typename TupleType> void souffle::BinaryRelation< TupleType >::extend (const BinaryRelation< TupleType > & other) inline
Definition at line 111 of file BinaryRelation.h.
{
         // iterate over all elements for each dj set in this BinRel
         for (auto it = sds.beginReps(); it != sds.endReps(); ++it) {
             DomainInt rep = *it;
             // check if any of the elements in this disjoint set exists in the other's domain
             for (auto setIt = sds.begin(rep); setIt != sds.end(rep); ++setIt) {
                 DomainInt el = *setIt;
                 // TODO: union the two DJ sets
                 if (other.containsElement(el)) {
                     DomainInt otherRep = other.sds.readOnlyFindNode(el);
                     for (auto otherIt = other.sds.begin(otherRep); otherIt != other.sds.end(otherRep);
                             ++otherIt) {
                         this->insert(el, *otherIt);
                     }
                     break;
                 }
             }
         }
     }
template<typename TupleType> iterator souffle::BinaryRelation< TupleType >::find (const TupleType & start) const inline
Begin an iterator at the requested point.
Parameters
start where the returned iterator should start from
Returns
the iterator which starts at the requested element
Definition at line 617 of file BinaryRelation.h.
{
         // generate tries for all disjoint sets
         // std::for_each(sds.beginReps(), sds.endReps(), [&](DomainInt r) { generateTrieIfNone(r); });
         for (auto rep = sds.beginReps(); rep != sds.endReps(); ++rep) {
             generateTrieIfNone(*rep);
         }
         return iterator(this, start);
     }
template<typename TupleType> iterator souffle::BinaryRelation< TupleType >::findBetween (const TupleType & start, const TupleType & end) const inline
Begin an iterator at/after the requested point, and mark it to finish at/before the specified one.
Parameters
start the requested beginning to iterate from
end the requested end to iterate until
Returns
the resulting iterator that satisfies this
Definition at line 695 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::getBoundaries().
{
         // generate tries for all disjoint sets
         std::for_each(sds.beginReps(), sds.endReps(), [&](DomainInt r) { generateTrieIfNone(r); });
         return iterator(this, start, end);
     }
template<typename TupleType> iterator souffle::BinaryRelation< TupleType >::frontProduct (std::list< DomainInt > start) const inline
Begin an iterator which generates all pairs (X, Y) s.t.
X in start & Y in DjSet(X) If that wasn't clear, so let's say there's an element e in start The iterator will generate the pairs (e, a), (e, b), ... (e, n) - assuming the elements a,b...n are in e's disjoint set Requires that all elements in start are within the same disjoint set (and in order) Changing this requires extensive changes to the underlying iterator(BinaryRelation*, std::vector<>) ctor
Parameters
start a list of front elements that must exist at the front pairing generated
Returns
the resulting iterator that satisfies this
Definition at line 713 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::getBoundaries(), and souffle::BinaryRelation< tuple_type >::partition().
{
         if (start.size() == 0) throw "invalid sized vector for front product";
         auto rep = sds.readOnlyFindNode(start.front());
         if (std::any_of(start.begin(), start.end(),
                     [&](DomainInt i) { return sds.readOnlyFindNode(i) != rep; })) {
             throw "elements not within same disjoint set";
         }
         if (!std::is_sorted(start.begin(), start.end())) {
             for (auto x : start) {
                 std::cout << x << '\t';
             }
             std::cout << std::endl;
             throw "elements are not sorted";
         }
         // the trie that contains every value in start
         auto trie = generateTrieIfNone(rep);
         return iterator(this, start, trie);
     }
template<typename TupleType> std::shared_ptr<souffle::Trie<1> > souffle::BinaryRelation< TupleType >::generateTrieIfNone (DomainInt val) const inline private
Create a trie which contains the disjoint set which contains this value.
Parameters
val the value whose disjoint set will be constructed into a trie
Returns
a reference to the newly created trie
Definition at line 183 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::begin(), souffle::BinaryRelation< tuple_type >::closure(), souffle::BinaryRelation< tuple_type >::find(), souffle::BinaryRelation< tuple_type >::findBetween(), souffle::BinaryRelation< tuple_type >::frontProduct(), and souffle::BinaryRelation< tuple_type >::partition().
{
         if (!sds.nodeExists(val)) throw "cannot generate trie for non-existent node";
         statesLock.lock_shared();
         DomainInt rep = sds.readOnlyFindNode(val);
         // return if already created
         if (this->orderedStates.find(rep) != this->orderedStates.end()) {
             auto retptr = this->orderedStates.at(rep);
             statesLock.unlock_shared();
             return retptr;
         }
         statesLock.unlock_shared();
         statesLock.lock();
         // return if already created (other write thread may have been called simultaneously)
         if (this->orderedStates.find(rep) != this->orderedStates.end()) {
             auto retptr = this->orderedStates.at(rep);
             statesLock.unlock();
             return retptr;
         }
         this->orderedStates[rep] = std::shared_ptr<souffle::Trie<1>>(new souffle::Trie<1>);
         // populate the trie
         for (auto it = sds.begin(rep); it != sds.end(rep); ++it) {
             // add the current value of the iterator to the trie
             this->orderedStates.at(rep)->insert(*it);
         }
         auto retptr = this->orderedStates.at(rep);
         statesLock.unlock();
         return retptr;
     }
template<typename TupleType> template<unsigned levels> range<iterator> souffle::BinaryRelation< TupleType >::getBoundaries (const operation_hints & entry) const inline
Obtains a range of elements matching the prefix of the given entry up to levels elements.
Template Parameters
levels the length of the requested matching prefix
Parameters
entry the entry to be looking for
Returns
the corresponding range of matching elements
Definition at line 637 of file BinaryRelation.h.
{
         operation_hints ctxt;
         return getBoundaries<levels>(entry, ctxt);
     }
template<typename TupleType> template<unsigned levels> range<iterator> souffle::BinaryRelation< TupleType >::getBoundaries (const TupleType & entry, operation_hints & ctxt) const inline
Obtains a range of elements matching the prefix of the given entry up to levels elements.
A operation context may be provided to exploit temporal locality.
Template Parameters
levels the length of the requested matching prefix
Parameters
entry the entry to be looking for
ctxt the operation context to be utilized
Returns
the corresponding range of matching elements
Definition at line 653 of file BinaryRelation.h.
{
         // TODO: use ctxt to exploit locality - does this really matter
         // if nothing is bound => just use begin and end
         if (levels == 0) return make_range(begin(), end());
         // as disjoint set is exactly two args (equiv relation)
         // we only need to handle these cases
         if (levels == 1) {
             // need to test if the entry actually exists
             if (!sds.nodeExists(entry[0])) return make_range(end(), end());
             std::list<DomainInt> x;
             x.push_back(entry[0]);
             // if so return an iterator starting from the (entry[0], smallest) -> (entry[0], biggest)
             return make_range(frontProduct(x), end());
         }
         if (levels == 2) {
             // need to test if the entry actually exists
             if (!sds.contains(entry[0], entry[1])) return make_range(end(), end());
             // if so return an iterator containing exactly that node
             return make_range(findBetween(entry, entry), end());
         }
         std::cerr << "invalid state, cannot search for >2 arg start point in getBoundaries, in 2 arg tuple "
                      "store\n";
         assert(false &&
                 "invalid state, cannot search for >2 arg start point in getBoundaries, in 2 arg tuple store");
         return make_range(end(), end());
     }
template<typename TupleType> bool souffle::BinaryRelation< TupleType >::insert (DomainInt x, DomainInt y) inline
Insert the two values symbolically as a binary relation.
Parameters
x node to be added/paired
y node to be added/paired
Returns
true if the pair is new to the data structure
Definition at line 68 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::extend(), souffle::BinaryRelation< tuple_type >::insert(), and souffle::BinaryRelation< tuple_type >::insertAll().
{
         operation_hints z;
         return insert(x, y, z);
     };
template<typename TupleType> bool souffle::BinaryRelation< TupleType >::insert (DomainInt x, DomainInt y, operation_hints z) inline
Insert the two values symbolically as a binary relation.
Parameters
x node to be added/paired
y node to be added/paired
z the hints to where the pair should be inserted (not applicable atm)
Returns
true if the pair is new to the data structure
Definition at line 80 of file BinaryRelation.h.
{
         // uncomment if race conditions ever present themselves
         // this should only be the case if the tries are generated during insertion
         // and this is not normal souffle behaviour
         // statesLock.lock_shared();
         orderedStates.erase(sds.readOnlyFindNode(x));
         orderedStates.erase(sds.readOnlyFindNode(y));
         sds.unionNodes(x, y);
         bool retval = contains(x, y);
         // statesLock.unlock_shared();
         return retval;
     }
template<typename TupleType> void souffle::BinaryRelation< TupleType >::insertAll (const BinaryRelation< TupleType > & other) inline
inserts all nodes from the other relation into this one
Parameters
other the binary relation from which to add nodes from
Definition at line 101 of file BinaryRelation.h.
{
         // for each representative
         for (auto rep = other.sds.beginReps(); rep != other.sds.endReps(); ++rep) {
             // insert the pairing between the representative and its
             for (auto subrep = other.sds.begin(*rep); subrep != other.sds.end(*rep); ++subrep) {
                 this->insert(*rep, *subrep);
             }
         }
     }
template<typename TupleType> BinaryRelation& souffle::BinaryRelation< TupleType >::operator= (const BinaryRelation< TupleType > & old) inline
Definition at line 43 of file BinaryRelation.h.
{
         if (this == &old) return *this;
         sds = old.sds;
         orderedStates.clear();
         return *this;
     }
template<typename TupleType> std::vector<souffle::range<iterator> > souffle::BinaryRelation< TupleType >::partition (size_t chunks) const inline
Generate an approximate number of iterators for parallel iteration The iterators returned are not necessarily equal in size, but in practise are approximately similarly sized Depending on the structure of the data, there can be more or less partitions returned than requested.
Parameters
chunks the number of requested partitions
Returns
a list of the iterators as ranges
Definition at line 756 of file BinaryRelation.h.
{
         std::vector<souffle::range<iterator>> ret;
         for (auto rep = sds.beginReps(); rep != sds.endReps(); ++rep) {
             generateTrieIfNone(*rep);
         }
         // num pairs
         const size_t sz = this->size();
         // 0 or 1 chunks
         if (chunks <= 1 || sz == 0) return {souffle::make_range(begin(), end())};
         // how many pairs can we fit within each iterator? (integer ceil division)
         const size_t chunkSize = (sz + (chunks - 1)) / chunks;
         for (auto djSet = sds.beginReps(); djSet != sds.endReps(); ++djSet) {
             const DomainInt rep = *djSet;
             const size_t djSetSize = sds.sizeOfRepresentativeSet(rep);
             size_t cSize = 0;
             // will the entire djSet's pairs fit within a single iterator?
             if (djSetSize * djSetSize <= chunkSize) {
                 // fit all pairs within this disjoint set into a single iterator
                 ret.push_back(souffle::make_range(closure(rep), end()));
             } else {
                 // add as many of this djSet closures into each iterator
                 std::list<DomainInt> fronts;
                 for (auto el = sds.begin(rep); el != sds.end(rep); ++el) {
                     fronts.push_back(*el);
                     cSize += djSetSize;
                     // iterator is full now? push this iterator set onto the return val
                     if (cSize >= chunkSize) {
                         fronts.sort();
                         ret.push_back(souffle::make_range(frontProduct(fronts), end()));
                         fronts.clear();
                         cSize = 0;
                     }
                 }
                 // if there's any remainder still
                 if (cSize != 0) ret.push_back(souffle::make_range(frontProduct(fronts), end()));
             }
         }
         return ret;
     }
template<typename TupleType> size_t souffle::BinaryRelation< TupleType >::size () const inline
Size of relation.
Returns
the sum of the number of pairs per disjoint set
Definition at line 162 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::partition().
{
         statesLock.lock_shared();
         size_t retval = 0;
         // sum (n^2)
         for (auto x = sds.beginReps(); x != sds.endReps(); ++x) {
             const size_t sz = sds.sizeOfRepresentativeSet(*x);
             retval += sz * sz;
         }
         statesLock.unlock_shared();
         return retval;
     }
Field Documentation
template<typename TupleType> std::unordered_map<DomainInt, std::shared_ptr<souffle::Trie<1> > > souffle::BinaryRelation< TupleType >::orderedStates mutable private
Definition at line 40 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::clear(), souffle::BinaryRelation< tuple_type >::generateTrieIfNone(), souffle::BinaryRelation< TupleType >::iterator::initIterators(), souffle::BinaryRelation< tuple_type >::insert(), and souffle::BinaryRelation< tuple_type >::operator=().
template<typename TupleType> SparseDisjointSet<DomainInt> souffle::BinaryRelation< TupleType >::sds mutable private
Definition at line 34 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::begin(), souffle::BinaryRelation< tuple_type >::clear(), souffle::BinaryRelation< tuple_type >::contains(), souffle::BinaryRelation< tuple_type >::containsElement(), souffle::BinaryRelation< tuple_type >::extend(), souffle::BinaryRelation< tuple_type >::find(), souffle::BinaryRelation< tuple_type >::findBetween(), souffle::BinaryRelation< tuple_type >::frontProduct(), souffle::BinaryRelation< tuple_type >::generateTrieIfNone(), souffle::BinaryRelation< tuple_type >::getBoundaries(), souffle::BinaryRelation< tuple_type >::insert(), souffle::BinaryRelation< tuple_type >::insertAll(), souffle::BinaryRelation< TupleType >::iterator::iterator(), souffle::BinaryRelation< tuple_type >::operator=(), souffle::BinaryRelation< tuple_type >::partition(), and souffle::BinaryRelation< tuple_type >::size().
template<typename TupleType> souffle::shared_mutex souffle::BinaryRelation< TupleType >::statesLock mutable private
Definition at line 37 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< tuple_type >::clear(), souffle::BinaryRelation< tuple_type >::generateTrieIfNone(), and souffle::BinaryRelation< tuple_type >::size().
The documentation for this class was generated from the following file:
BinaryRelation.h