souffle: souffle::MagicSetTransformer Class Reference
souffle::MagicSetTransformer Class Reference
Magic Set Transformation.
#include <AstTransforms.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Magic Set Transformation.
Definition at line 311 of file AstTransforms.h.
Member Function Documentation
std::string souffle::MagicSetTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 316 of file AstTransforms.h.
{
         return "MagicSetTransformer";
     }
bool souffle::MagicSetTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 1076 of file MagicSet.cpp.
References souffle::AstAtom::addArgument(), souffle::AstRelation::addAttribute(), souffle::AstRelation::addClause(), souffle::AstRelation::addIODirectives(), souffle::AstClause::addToBody(), souffle::AstProgram::appendClause(), souffle::AstProgram::appendRelation(), souffle::AstClause::clone(), souffle::contains(), souffle::createAdornedIdentifier(), souffle::createMagicIdentifier(), souffle::createMagicRelation(), souffle::createNewRelation(), souffle::createSubIdentifier(), souffle::EQ, souffle::extractConstant(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstAtom::getArguments(), souffle::AstRelation::getArity(), souffle::AstAtom::getAtom(), souffle::AstClause::getAtoms(), souffle::AstRelation::getAttributes(), souffle::AstClause::getBodyLiterals(), souffle::getEndpoint(), souffle::AstClause::getHead(), souffle::AstRelation::getIODirectives(), souffle::IODirectives::getIOType(), souffle::AstAtom::getName(), souffle::AstRelationIdentifier::getNames(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelation(), souffle::AstNode::getSrcLoc(), souffle::getString(), souffle::AstTranslationUnit::getSymbolTable(), souffle::IODirectives::has(), souffle::hasPrefix(), i, souffle::isAggRel(), souffle::AstRelation::isInput(), souffle::AstRelation::isOutput(), souffle::AstRelation::isPrintSize(), j, k, souffle::nextSrcLoc(), relation, souffle::AstProgram::removeRelation(), souffle::reorderAdornment(), souffle::AstClause::reorderAtoms(), souffle::reorderOrdering(), souffle::replaceUnderscores(), souffle::separateDBs(), souffle::IODirectives::set(), souffle::IODirectives::setIOType(), souffle::AstAtom::setName(), souffle::AstRelation::setName(), souffle::IODirectives::setRelationName(), souffle::AstNode::setSrcLoc(), souffle::updateQualifier(), and souffle::visitDepthFirst().
{
     AstProgram* program = translationUnit.getProgram();
     separateDBs(program);  // make EDB int IDB = empty
     auto* adornment = translationUnit.getAnalysis<Adornment>();  // perform adornment
     const BindingStore& compositeBindings = adornment->getBindings();
     // edb/idb handling
     std::vector<std::vector<AdornedClause>> allAdornedClauses = adornment->getAdornedClauses();
     std::set<AstRelationIdentifier> negatedAtoms = adornment->getNegatedAtoms();
     std::set<AstRelationIdentifier> ignoredAtoms = adornment->getIgnoredAtoms();
     std::set<AstRelationIdentifier> oldIdb = adornment->getIDB();
     std::set<AstRelationIdentifier> newIdb;
     // additions
     std::vector<AstRelationIdentifier> newQueryNames;
     std::vector<AstClause*> newClauses;
     // output handling
     std::vector<AstRelationIdentifier> outputQueries = adornment->getRelations();
     std::set<AstRelationIdentifier> addAsOutput;
     std::set<AstRelationIdentifier> addAsPrintSize;
     std::map<AstRelationIdentifier, std::vector<AstIODirective*>> outputDirectives;
     // ignore negated atoms
     for (AstRelationIdentifier relation : negatedAtoms) {
         ignoredAtoms.insert(relation);
     }
     // perform magic set algorithm for each output
     for (size_t querynum = 0; querynum < outputQueries.size(); querynum++) {
         AstRelationIdentifier outputQuery = outputQueries[querynum];
         std::vector<AdornedClause> adornedClauses = allAdornedClauses[querynum];
         AstRelation* originalOutputRelation = program->getRelation(outputQuery);
         // add a relation for the output query
         // mN_outputname_ff...f()
         auto* magicOutputRelation = new AstRelation();
         std::string frepeat = std::string(originalOutputRelation->getArity(), 'f');
         AstRelationIdentifier magicOutputName =
                 createMagicIdentifier(createAdornedIdentifier(outputQuery, frepeat), querynum);
         magicOutputRelation->setName(magicOutputName);
         newQueryNames.push_back(magicOutputName);
         // add the new relation to the program
         program->appendRelation(std::unique_ptr<AstRelation>(magicOutputRelation));
         // add an empty fact to the program
         // i.e. mN_outputname_ff...f().
         auto* outputFact = new AstClause();
         outputFact->setSrcLoc(nextSrcLoc(originalOutputRelation->getSrcLoc()));
         outputFact->setHead(std::make_unique<AstAtom>(magicOutputName));
         program->appendClause(std::unique_ptr<AstClause>(outputFact));
         // perform the magic transformation based on the adornment for this output query
         for (AdornedClause adornedClause : adornedClauses) {
             AstClause* clause = adornedClause.getClause();
             AstRelationIdentifier originalName = clause->getHead()->getName();
             // dont perform the magic transformation on ignored relations
             if (contains(ignoredAtoms, originalName)) {
                 continue;
             }
             // find the adorned version of this relation
             std::string headAdornment = adornedClause.getHeadAdornment();
             AstRelationIdentifier newRelName = createAdornedIdentifier(originalName, headAdornment);
             AstRelation* adornedRelation = program->getRelation(newRelName);
             // check if adorned relation already created previously
             if (adornedRelation == nullptr) {
                 // adorned relation not created yet, so
                 // create the relation with the new adornment
                 AstRelation* originalRelation = program->getRelation(originalName);
                 AstRelation* newRelation = createNewRelation(originalRelation, newRelName);
                 // copy over input directives to new adorned relation
                 // also - update input directives to correctly use default fact file names
                 if (originalRelation->isInput()) {
                     IODirectives inputDirectives;  // to more easily work with the directive
                     auto* newDirective = new AstIODirective();
                     inputDirectives.setRelationName(newRelName.getNames()[0]);
                     newDirective->addName(newRelName);
                     newDirective->setAsInput();
                     for (AstIODirective* current : originalRelation->getIODirectives()) {
                         if (current->isInput()) {
                             for (const auto& currentPair : current->getIODirectiveMap()) {
                                 newDirective->addKVP(currentPair.first, currentPair.second);
                                 inputDirectives.set(currentPair.first, currentPair.second);
                             }
                         }
                     }
                     if (!inputDirectives.has("IO")) {
                         inputDirectives.setIOType("file");
                         newDirective->addKVP("IO", "file");
                     }
                     if (inputDirectives.getIOType() == "file" && !inputDirectives.has("filename")) {
                         newDirective->addKVP("filename", originalName.getNames()[0] + ".facts");
                     }
                     newRelation->addIODirectives(std::unique_ptr<AstIODirective>(newDirective));
                 }
                 // add the created adorned relation to the program
                 program->appendRelation(std::unique_ptr<AstRelation>(newRelation));
                 adornedRelation = newRelation;
             }
             // create the adorned version of this clause
             AstClause* newClause = clause->clone();
             newClause->getHead()->setName(newRelName);
             // reorder atoms based on SIPS ordering
             newClause->reorderAtoms(reorderOrdering(adornedClause.getOrdering()));
             // get corresponding adornments for each body atom
             std::vector<std::string> bodyAdornment =
                     reorderAdornment(adornedClause.getBodyAdornment(), adornedClause.getOrdering());
             // set the name of each IDB pred in the clause to be the adorned version
             int atomsSeen = 0;
             for (AstLiteral* lit : newClause->getBodyLiterals()) {
                 if (dynamic_cast<AstAtom*>(lit)) {
                     auto* bodyAtom = dynamic_cast<AstAtom*>(lit);
                     AstRelationIdentifier atomName = bodyAtom->getName();
                     // note that all atoms in the original clause were adorned,
                     // but only the IDB atom adornments should be added here
                     if (contains(oldIdb, atomName)) {
                         if (!contains(ignoredAtoms, atomName)) {
                             // ignored atoms should not be changed
                             AstRelationIdentifier newAtomName =
                                     createAdornedIdentifier(atomName, bodyAdornment[atomsSeen]);
                             bodyAtom->setName(newAtomName);
                             newIdb.insert(newAtomName);
                         } else {
                             newIdb.insert(atomName);
                         }
                     }
                     atomsSeen++;
                 }
             }
             // Add the set of magic rules for this clause C = A^a :- A1^a1, A2^a2, ..., An^an
             // -- For each clause C = A^a :- A1^a1, A2^a2, ..., An^an
             // -- -- For each IDB literal A_i in the body of C
             // -- -- -- Add mag(Ai^ai) :- mag(A^a), A1^a1, ..., Ai-1^ai-1 to the program
             std::vector<AstLiteral*> body = newClause->getBodyLiterals();
             for (size_t i = 0; i < body.size(); i++) {
                 AstLiteral* currentLiteral = body[i];
                 // only care about atoms in the body
                 if (dynamic_cast<AstAtom*>(currentLiteral)) {
                     auto* atom = dynamic_cast<AstAtom*>(currentLiteral);
                     AstRelationIdentifier atomName = atom->getName();
                     // only IDB atoms that are not being ignored matter
                     if (contains(newIdb, atomName) && !contains(ignoredAtoms, atomName)) {
                         std::string currAdornment = bodyAdornment[i];
                         // generate the name of the magic version of this adorned literal
                         AstRelationIdentifier newAtomName = createMagicIdentifier(atomName, querynum);
                         // if the magic version does not exist, create it
                         if (program->getRelation(newAtomName) == nullptr) {
                             auto* magicRelation = new AstRelation();
                             magicRelation->setName(newAtomName);
                             // find out the original name of the relation (pre-adornment)
                             std::string baseAtomName = atomName.getNames()[0];
                             int endpt = getEndpoint(baseAtomName);
                             AstRelationIdentifier originalRelationName = createSubIdentifier(
                                     atomName, 0, endpt - 1);  // get rid of the extra + at the end
                             AstRelation* originalRelation = program->getRelation(originalRelationName);
                             // copy over the (bound) attributes from the original relation
                             int argcount = 0;
                             for (AstAttribute* attr : originalRelation->getAttributes()) {
                                 if (currAdornment[argcount] == 'b') {
                                     magicRelation->addAttribute(std::unique_ptr<AstAttribute>(attr->clone()));
                                 }
                                 argcount++;
                             }
                             // add in relevant qualifiers from original relation
                             updateQualifier(originalRelation, magicRelation);
                             // add the new magic relation to the program
                             program->appendRelation(std::unique_ptr<AstRelation>(magicRelation));
                         }
                         // start setting up the magic rule
                         auto* magicClause = new AstClause();
                         magicClause->setSrcLoc(nextSrcLoc(atom->getSrcLoc()));
                         // create the head of the magic rule
                         AstAtom* magicHead = new AstAtom(newAtomName);
                         // copy over (bound) arguments from the original atom
                         int argCount = 0;
                         for (AstArgument* arg : atom->getArguments()) {
                             if (currAdornment[argCount] == 'b') {
                                 magicHead->addArgument(std::unique_ptr<AstArgument>(arg->clone()));
                             }
                             argCount++;
                         }
                         // head complete!
                         magicClause->setHead(std::unique_ptr<AstAtom>(magicHead));
                         // -- create the body --
                         // create the first body argument (mag(origClauseHead^adornment))
                         AstRelationIdentifier magPredName =
                                 createMagicIdentifier(newClause->getHead()->getName(), querynum);
                         AstAtom* addedMagicPred = new AstAtom(magPredName);
                         // create the relation if it does not exist
                         if (program->getRelation(magPredName) == nullptr) {
                             AstRelation* originalRelation =
                                     program->getRelation(newClause->getHead()->getName());
                             AstRelation* newMagicRelation =
                                     createMagicRelation(originalRelation, magPredName);
                             // add the new relation to the prgoram
                             program->appendRelation(std::unique_ptr<AstRelation>(newMagicRelation));
                         }
                         // add (bound) arguments to the magic predicate from the clause head
                         argCount = 0;
                         for (AstArgument* arg : newClause->getHead()->getArguments()) {
                             if (headAdornment[argCount] == 'b') {
                                 addedMagicPred->addArgument(std::unique_ptr<AstArgument>(arg->clone()));
                             }
                             argCount++;
                         }
                         // first argument complete!
                         magicClause->addToBody(std::unique_ptr<AstAtom>(addedMagicPred));
                         // add the rest of the necessary arguments
                         for (size_t j = 0; j < i; j++) {
                             magicClause->addToBody(std::unique_ptr<AstLiteral>(body[j]->clone()));
                         }
                         // restore memorised bindings for all composite arguments
                         std::vector<const AstArgument*> compositeArguments;
                         visitDepthFirst(*magicClause, [&](const AstArgument& argument) {
                             std::string argName = getString(&argument);
                             if (hasPrefix(argName, "+functor") || hasPrefix(argName, "+record")) {
                                 compositeArguments.push_back(&argument);
                             }
                         });
                         for (const AstArgument* compositeArgument : compositeArguments) {
                             std::string argName = getString(compositeArgument);
                             // if the composite argument was bound only because all
                             // of its constituent variables were bound, then bind
                             // the composite variable to the original argument
                             if (compositeBindings.isVariableBoundComposite(argName)) {
                                 AstArgument* originalArgument =
                                         compositeBindings.cloneOriginalArgument(argName);
                                 magicClause->addToBody(
                                         std::make_unique<AstBinaryConstraint>(BinaryConstraintOp::EQ,
                                                 std::unique_ptr<AstArgument>(compositeArgument->clone()),
                                                 std::unique_ptr<AstArgument>(originalArgument)));
                             }
                         }
                         // restore bindings for normalised constants
                         std::vector<const AstVariable*> clauseVariables;
                         visitDepthFirst(*magicClause,
                                 [&](const AstVariable& variable) { clauseVariables.push_back(&variable); });
                         for (const AstVariable* var : clauseVariables) {
                             std::string varName = getString(var);
                             // all normalised constants begin with "+abdul" (see AstTransforms.cpp)
                             // +abdulX_variablevalue_Y
                             if (hasPrefix(varName, "+abdul")) {
                                 AstArgument* embeddedConstant =
                                         extractConstant(translationUnit.getSymbolTable(), varName);
                                 // add the constraint to the body of the clause
                                 magicClause->addToBody(std::make_unique<AstBinaryConstraint>(
                                         BinaryConstraintOp::EQ, std::unique_ptr<AstArgument>(var->clone()),
                                         std::unique_ptr<AstArgument>(embeddedConstant)));
                             }
                         }
                         // magic rule done! add it to the program
                         program->appendClause(std::unique_ptr<AstClause>(magicClause));
                     }
                 }
             }
             // -- replace with H :- mag(H), T --
             size_t originalNumAtoms = newClause->getAtoms().size();
             // create the first argument of this new clause
             const AstAtom* newClauseHead = newClause->getHead()->getAtom();
             AstRelationIdentifier newMag = createMagicIdentifier(newClauseHead->getName(), querynum);
             AstAtom* newMagAtom = new AstAtom(newMag);
             // copy over the bound arguments from the head
             std::vector<AstArgument*> args = newClauseHead->getArguments();
             for (size_t k = 0; k < args.size(); k++) {
                 if (headAdornment[k] == 'b') {
                     newMagAtom->addArgument(std::unique_ptr<AstArgument>(args[k]->clone()));
                 }
             }
             // add it to the end of the clause
             newClause->addToBody(std::unique_ptr<AstAtom>(newMagAtom));
             // move the new magic argument to the front of the clause,
             // pushing all the rest up one position
             std::vector<unsigned int> newClauseOrder(originalNumAtoms + 1);
             for (size_t k = 0; k < originalNumAtoms; k++) {
                 newClauseOrder[k] = k + 1;
             }
             newClauseOrder[originalNumAtoms] = 0;
             newClause->reorderAtoms(reorderOrdering(newClauseOrder));
             // add the clause to the program and the set of new clauses
             newClause->setSrcLoc(nextSrcLoc(newClause->getSrcLoc()));
             newClauses.push_back(newClause);
             adornedRelation->addClause(std::unique_ptr<AstClause>(newClause));
         }
     }
     // remove all transformed old IDB relations, making sure to preserve input/output directives
     for (AstRelationIdentifier relationName : oldIdb) {
         AstRelation* relation = program->getRelation(relationName);
         // before deleting, store the directives of computed relations
         // for restoration later on
         if (relation->isOutput()) {
             addAsOutput.insert(relationName);
             std::vector<AstIODirective*> clonedDirectives;
             for (AstIODirective* iodir : relation->getIODirectives()) {
                 clonedDirectives.push_back(iodir->clone());
             }
             outputDirectives[relationName] = clonedDirectives;
         } else if (relation->isPrintSize()) {
             addAsPrintSize.insert(relationName);
             std::vector<AstIODirective*> clonedDirectives;
             for (AstIODirective* iodir : relation->getIODirectives()) {
                 clonedDirectives.push_back(iodir->clone());
             }
             outputDirectives[relationName] = clonedDirectives;
         }
         // do not delete negated atoms, ignored atoms, or atoms added by aggregate relations
         if (!(contains(ignoredAtoms, relationName) || contains(negatedAtoms, relationName) ||
                     isAggRel(relationName))) {
             program->removeRelation(relationName);
         }
     }
     // add the new output relations
     // in particular, need to rename the adorned output back to the original name
     for (size_t i = 0; i < outputQueries.size(); i++) {
         AstRelationIdentifier oldName = outputQueries[i];
         AstRelationIdentifier newName = newQueryNames[i];
         // get the original adorned relation
         std::string newBaseName = newName.getNames()[0];
         size_t prefixpoint = newBaseName.find("_");
         AstRelationIdentifier newRelationName =
                 createSubIdentifier(newName, prefixpoint + 1, newBaseName.size() - (prefixpoint + 1));
         AstRelation* adornedRelation = program->getRelation(newRelationName);
         if (adornedRelation == nullptr) {
             continue;
         }
         AstRelation* outputRelation = program->getRelation(oldName);
         // if the corresponding output relation does not exist yet, create it
         if (outputRelation == nullptr) {
             outputRelation = new AstRelation();
             outputRelation->setSrcLoc(nextSrcLoc(adornedRelation->getSrcLoc()));
             // copy over the attributes from the existing adorned version
             for (AstAttribute* attr : adornedRelation->getAttributes()) {
                 outputRelation->addAttribute(std::unique_ptr<AstAttribute>(attr->clone()));
             }
             // rename it back to its original name
             outputRelation->setName(oldName);
             // set as output relation
             auto* newdir = new AstIODirective();
             if (addAsOutput.find(oldName) != addAsOutput.end()) {
                 newdir->setAsOutput();
             } else {
                 newdir->setAsPrintSize();
             }
             outputRelation->addIODirectives(std::unique_ptr<AstIODirective>(newdir));
             // add the new output to the program
             program->appendRelation(std::unique_ptr<AstRelation>(outputRelation));
         }
         // rules need to be the same
         // easy fix:
         //    oldname(arg1...argn) :- newname(arg1...argn)
         AstAtom* headatom = new AstAtom(oldName);
         AstAtom* bodyatom = new AstAtom(newRelationName);
         for (size_t j = 0; j < adornedRelation->getArity(); j++) {
             std::stringstream argName;
             argName.str("");
             argName << "arg" << j;
             headatom->addArgument(std::make_unique<AstVariable>(argName.str()));
             bodyatom->addArgument(std::make_unique<AstVariable>(argName.str()));
         }
         // add the clause to the program
         auto* referringClause = new AstClause();
         referringClause->setSrcLoc(nextSrcLoc(outputRelation->getSrcLoc()));
         referringClause->setHead(std::unique_ptr<AstAtom>(headatom));
         referringClause->addToBody(std::unique_ptr<AstAtom>(bodyatom));
         program->appendClause(std::unique_ptr<AstClause>(referringClause));
     }
     // add in all the output directives to their corresponding relations
     for (std::pair<AstRelationIdentifier, std::vector<AstIODirective*>> iopair : outputDirectives) {
         for (AstIODirective* iodir : iopair.second) {
             program->getRelation(iopair.first)->addIODirectives(std::unique_ptr<AstIODirective>(iodir));
         }
     }
     // replace all "+underscoreX" variables with actual underscores
     replaceUnderscores(program);
     // done!
     return true;
 }
The documentation for this class was generated from the following files:
AstTransforms.h
MagicSet.cpp