souffle: souffle::RamScan Class Reference
souffle::RamScan Class Reference
Relation Scan.
#include <RamOperation.h>
Public Member Functions
void addCondition (std::unique_ptr< RamCondition > c, const RamOperation &root) override
Add condition.
void apply (const RamNodeMapper &map) override
Apply mapper.
RamScan * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
std::vector< RamValue * > getRangePattern () const
Get range pattern.
const SearchColumns & getRangeQueryColumns () const
Get indexable columns of scan.
const RamRelation & getRelation () const
Get search relation.
bool isPureExistenceCheck () const
Check for pure existence check.
void print (std::ostream &os, int tabpos) const override
Print.
RamScan (std::unique_ptr< RamRelation > r, std::unique_ptr< RamOperation > nested, bool pureExistenceCheck, std::string profileText="")
Public Member Functions inherited from souffle::RamSearch
size_t getDepth () const override
Get depth of query.
RamOperation * getNestedOperation () const
get nested operation
const RamOperation & getOperation () const
get nested operation
const std::string & getProfileText () const
get profile text
RamSearch (RamNodeType type, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
void addCondition (std::unique_ptr< RamCondition > c)
Add condition.
RamCondition * getCondition () const
Get condition.
size_t getLevel () const
Get level.
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type, size_t l)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
SearchColumns keys
Indexable columns for a range query.
bool pureExistenceCheck
Determines whether this scan operation is merely verifying the existence of a value (e.g.
std::vector< std::unique_ptr
< RamValue > > queryPattern
Values of index per column of table (if indexable)
std::unique_ptr< RamRelation > relation
Search relation.
Protected Attributes inherited from souffle::RamOperation
std::unique_ptr< RamCondition > condition
condition that is checked for each obtained tuple
size_t level
the nesting level of this operation
Detailed Description
Relation Scan.
Iterate all tuples of a relation and filter them via a condition
Definition at line 181 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamScan::RamScan (std::unique_ptr< RamRelation > r, std::unique_ptr< RamOperation > nested, bool pureExistenceCheck, std::string profileText = "") inline
Definition at line 202 of file RamOperation.h.
Referenced by clone().
             : RamSearch(RN_Scan, std::move(nested), std::move(profileText)), relation(std::move(r)),
               queryPattern(relation->getArity()), keys(0), pureExistenceCheck(pureExistenceCheck) {}
Member Function Documentation
void souffle::RamScan::addCondition (std::unique_ptr< RamCondition > c, const RamOperation & root) override virtual
Add condition.
add condition
Reimplemented from souffle::RamSearch.
Definition at line 81 of file RamOperation.cpp.
References souffle::RamSearch::addCondition(), souffle::EQ, keys, souffle::RamOperation::level, and queryPattern.
{
     // use condition to narrow scan if possible
     if (c->getLevel() == level) {
         size_t element = 0;
         if (std::unique_ptr<RamValue> value = getIndexElement(c.get(), element, level)) {
             keys |= (1 << element);
             if (queryPattern[element] == nullptr) {
                 queryPattern[element] = std::move(value);
             } else {
                 std::unique_ptr<RamValue> field = std::make_unique<RamElementAccess>(level, element);
                 RamSearch::addCondition(std::make_unique<RamBinaryRelation>(
                                                 BinaryConstraintOp::EQ, std::move(field), std::move(value)),
                         root);
             }
             return;
         }
     }
     // otherwise: use default handling
     RamSearch::addCondition(std::move(c), root);
 }
void souffle::RamScan::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Reimplemented from souffle::RamSearch.
Definition at line 260 of file RamOperation.h.
References souffle::RamSearch::apply(), map, and queryPattern.
{
         RamSearch::apply(map);
         for (auto& cur : queryPattern) {
             if (cur) {
                 cur = map(std::move(cur));
             }
         }
     }
RamScan* souffle::RamScan::clone () const inline override virtual
Create clone.
Implements souffle::RamOperation.
Definition at line 246 of file RamOperation.h.
References souffle::RamOperation::clone(), souffle::RamOperation::condition, souffle::RamSearch::getNestedOperation(), keys, pureExistenceCheck, queryPattern, RamScan(), and relation.
{
         RamScan* res = new RamScan(std::unique_ptr<RamRelation>(relation->clone()),
                 std::unique_ptr<RamOperation>(getNestedOperation()->clone()), pureExistenceCheck);
         res->condition = std::unique_ptr<RamCondition>(condition->clone());
         res->keys = keys;
         for (auto& cur : queryPattern) {
             if (cur) {
                 res->queryPattern.push_back(std::unique_ptr<RamValue>(cur->clone()));
             }
         }
         return res;
     }
bool souffle::RamScan::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamSearch.
Definition at line 271 of file RamOperation.h.
References souffle::RamSearch::equal(), souffle::equal_targets(), getRelation(), keys, pureExistenceCheck, and queryPattern.
{
         assert(nullptr != dynamic_cast<const RamScan*>(&node));
         const auto& other = static_cast<const RamScan&>(node);
         return RamSearch::equal(other) && getRelation() == other.getRelation() &&
                equal_targets(queryPattern, other.queryPattern) && keys == other.keys &&
                pureExistenceCheck == other.pureExistenceCheck;
     }
std::vector<const RamNode*> souffle::RamScan::getChildNodes () const inline override virtual
Obtain list of child nodes.
Reimplemented from souffle::RamSearch.
Definition at line 235 of file RamOperation.h.
References souffle::RamSearch::getChildNodes(), and queryPattern.
{
         auto res = RamSearch::getChildNodes();
         for (auto& cur : queryPattern) {
             if (cur) {
                 res.push_back(cur.get());
             }
         }
         return res;
     }
std::vector<RamValue*> souffle::RamScan::getRangePattern () const inline
Get range pattern.
Definition at line 218 of file RamOperation.h.
References queryPattern, and souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalOp().
{
         return toPtrVector(queryPattern);
     }
const SearchColumns& souffle::RamScan::getRangeQueryColumns () const inline
Get indexable columns of scan.
Definition at line 213 of file RamOperation.h.
References keys.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalOp().
{
         return keys;
     }
const RamRelation& souffle::RamScan::getRelation () const inline
Get search relation.
Definition at line 208 of file RamOperation.h.
References relation.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalOp().
{
         return *relation;
     }
bool souffle::RamScan::isPureExistenceCheck () const inline
Check for pure existence check.
Definition at line 224 of file RamOperation.h.
References pureExistenceCheck.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalOp(), and print().
{
         return pureExistenceCheck;
     }
void souffle::RamScan::print (std::ostream & os, int tabpos) const override virtual
Print.
Implements souffle::RamOperation.
Definition at line 103 of file RamOperation.cpp.
References souffle::RamOperation::condition, souffle::RamOperation::getCondition(), souffle::RamSearch::getNestedOperation(), i, isPureExistenceCheck(), keys, souffle::RamOperation::level, souffle::RamOperation::print(), queryPattern, relation, and souffle::times().
{
     os << times('\t', tabpos);
     if (isPureExistenceCheck()) {
         os << "IF  t" << level << "  " << relation->getName() << " ";
         if (keys != 0) {
             os << "WITH ";
             bool first = true;
             for (size_t i = 0; i < relation->getArity(); i++) {
                 if (queryPattern[i] != nullptr) {
                     if (first) {
                         first = false;
                     } else {
                         os << "and ";
                     }
                     os << "t" << level << "." << relation->getArg(i) << "=";
                     queryPattern[i]->print(os);
                     os << " ";
                 }
             }
         }
     } else {
         if (keys == 0) {
             os << "SCAN " << relation->getName() << " AS t" << level << " ";
         } else {
             // Keys indicates index search?
             os << "SEARCH " << relation->getName() << " AS t" << level;
             os << " ON INDEX ";
             bool first = true;
             for (size_t i = 0; i < relation->getArity(); i++) {
                 if (queryPattern[i] != nullptr) {
                     if (first) {
                         first = false;
                     } else {
                         os << "and ";
                     }
                     os << "t" << level << "." << relation->getArg(i) << "=";
                     queryPattern[i]->print(os);
                     os << " ";
                 }
             }
         }
     }
     if (auto condition = getCondition()) {
         os << "WHERE ";
         condition->print(os);
     }
     os << "\n";
     if (getNestedOperation() != nullptr) {
         getNestedOperation()->print(os, tabpos + 1);
     }
 }
Field Documentation
SearchColumns souffle::RamScan::keys protected
Indexable columns for a range query.
Definition at line 190 of file RamOperation.h.
Referenced by addCondition(), clone(), equal(), getRangeQueryColumns(), and print().
bool souffle::RamScan::pureExistenceCheck protected
Determines whether this scan operation is merely verifying the existence of a value (e.g.
rel(_,_), rel(1,2), rel(1,_) or rel(X,Y) where X and Y are bound) or actually contributing new variable bindings (X or Y are not bound).
The exists-only can be check much more efficient than the other case.
Definition at line 199 of file RamOperation.h.
Referenced by clone(), equal(), and isPureExistenceCheck().
std::vector<std::unique_ptr<RamValue> > souffle::RamScan::queryPattern protected
Values of index per column of table (if indexable)
Definition at line 187 of file RamOperation.h.
Referenced by addCondition(), apply(), clone(), equal(), getChildNodes(), getRangePattern(), and print().
std::unique_ptr<RamRelation> souffle::RamScan::relation protected
Search relation.
Definition at line 184 of file RamOperation.h.
Referenced by clone(), getRelation(), and print().
The documentation for this class was generated from the following files:
RamOperation.h
RamOperation.cpp