souffle: souffle::LogicbloxConverter Class Reference
souffle::LogicbloxConverter Class Reference
Public Member Functions
void convert (std::ostream &out, const AstProgram &program)
LogicbloxConverter (std::ostream &imOut, std::ostream &exOut, std::ostream &decOut)
Private Member Functions
AstTypeIdentifier convertTypeName (const AstTypeIdentifier &name)
void visitAtom (const AstAtom &atom, std::ostream &out) override
void visitBinaryConstraint (const AstBinaryConstraint &cnstr, std::ostream &out) override
void visitClause (const AstClause &clause, std::ostream &out) override
Converting a clause.
void visitFunctor (const AstFunctor &fun, std::ostream &out) override
void visitNegation (const AstNegation &neg, std::ostream &out) override
void visitNode (const AstNode &node, std::ostream &) override
void visitNumberConstant (const AstNumberConstant &num, std::ostream &out) override
void visitProgram (const AstProgram &program, std::ostream &out) override
The entry point for the conversion of a program, converting the basic top-level structure.
void visitRelation (const AstRelation &rel, std::ostream &) override
Converting a relation by creating its declaration.
void visitRelationIdentifier (const AstRelationIdentifier &id, std::ostream &out)
void visitStringConstant (const AstStringConstant &str, std::ostream &out) override
void visitTypeCast (const AstTypeCast &cast, std::ostream &out) override
void visitUnnamedVariable (const AstUnnamedVariable &var, std::ostream &out) override
void visitVariable (const AstVariable &var, std::ostream &out) override
Private Member Functions inherited from souffle::AstVisitor< void, std::ostream & >
void operator() (const AstNode &node, Params...args)
The main entry for the user allowing visitors to be utilized as functions.
virtual void visit (const AstNode &node, Params...args)
The main entry for a visit process conducting the dispatching of a visit to the various sub-types of AstNodes.
virtual ~AstVisitor ()=default
A virtual destructor.
LINK (PrimitiveType, Type)
LINK (RecordType, Type)
LINK (UnionType, Type)
LINK (Type, Node)
LINK (Argument, Node)
LINK (Literal, Node)
LINK (ComponentType, Node)
LINK (ComponentInit, Node)
LINK (Component, Node)
LINK (Program, Node)
LINK (Attribute, Node)
LINK (Clause, Node)
LINK (IODirective, Node)
LINK (Relation, Node)
LINK (Pragma, Node)
virtual void visitNode (const AstNode &, Params...)
The base case for all visitors – if no more specific overload was defined.
Private Attributes
std::ostream & dout
std::ostream & eout
std::vector< std::string > extra_literals
std::ostream & iout
Detailed Description
Definition at line 75 of file souffle2lb.cpp.
Constructor & Destructor Documentation
souffle::LogicbloxConverter::LogicbloxConverter (std::ostream & imOut, std::ostream & exOut, std::ostream & decOut) inline
Definition at line 83 of file souffle2lb.cpp.
References eout, and iout.
             : iout(imOut), eout(exOut), dout(decOut) {
         iout << "option,delimiter,\"\\t\"\n";
         iout << "option,hasColumnNames,false\n";
         iout << "\n";
         iout << "\n";
         eout << "option,delimiter,\"\\t\"\n";
         eout << "option,hasColumnNames,false\n";
         eout << "\n";
         eout << "\n";
     }
Member Function Documentation
void souffle::LogicbloxConverter::convert (std::ostream & out, const AstProgram & program) inline
Definition at line 96 of file souffle2lb.cpp.
References souffle::AstVisitor< void, std::ostream & >::visit().
Referenced by souffle::toLogicblox().
{
         visit(program, out);
     }
AstTypeIdentifier souffle::LogicbloxConverter::convertTypeName (const AstTypeIdentifier & name) inline private
Definition at line 101 of file souffle2lb.cpp.
Referenced by visitRelation().
{
         if (name == "number") {
             return AstTypeIdentifier("int[32]");
         } else if (name == "String") {
             return AstTypeIdentifier("string");
         } else
             return AstTypeIdentifier("string");
     }
void souffle::LogicbloxConverter::visitAtom (const AstAtom & atom, std::ostream & out) inline override private
Definition at line 216 of file souffle2lb.cpp.
References souffle::AstAtom::getArguments(), souffle::AstAtom::getName(), souffle::join(), souffle::AstVisitor< void, std::ostream & >::visit(), and visitRelationIdentifier().
{
         visitRelationIdentifier(atom.getName(), out);
         // since no nullary-relations are allowed, we add a dummy value
         if (atom.getArguments().empty()) {
             out << "(0)";
             return;
         }
         out << "(";
         out << join(atom.getArguments(), ",", [&](std::ostream& os, AstArgument* cur) { visit(*cur, os); });
         out << ")";
     }
void souffle::LogicbloxConverter::visitBinaryConstraint (const AstBinaryConstraint & cnstr, std::ostream & out) inline override private
Definition at line 235 of file souffle2lb.cpp.
References souffle::AstBinaryConstraint::getLHS(), souffle::AstBinaryConstraint::getOperator(), souffle::AstBinaryConstraint::getRHS(), souffle::toBinaryConstraintSymbol(), and souffle::AstVisitor< void, std::ostream & >::visit().
{
         visit(*cnstr.getLHS(), out);
         out << toBinaryConstraintSymbol(cnstr.getOperator());
         visit(*cnstr.getRHS(), out);
     }
void souffle::LogicbloxConverter::visitClause (const AstClause & clause, std::ostream & out) inline override private
Converting a clause.
Definition at line 188 of file souffle2lb.cpp.
References extra_literals, souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), souffle::AstClause::isFact(), souffle::join(), souffle::toString(), and souffle::AstVisitor< void, std::ostream & >::visit().
{
         visit(*clause.getHead(), out);
         // if it is a fact, that's it
         if (clause.isFact()) {
             // there must not be any additons
             if (!extra_literals.empty()) {
                 throw UnsupportedConstructException("Unsupported fact: " + toString(clause));
             }
             out << ".\n";
             return;
         }
         // convert the body
         out << " <- ";
         out << join(
                 clause.getBodyLiterals(), ",", [&](std::ostream& os, AstLiteral* cur) { visit(*cur, os); });
         // add extra_literals
         for (const auto& cur : extra_literals) {
             out << "," << cur;
         }
         extra_literals.clear();
         // done
         out << ".\n";
     }
void souffle::LogicbloxConverter::visitFunctor (const AstFunctor & fun, std::ostream & out) inline override private
Definition at line 253 of file souffle2lb.cpp.
References souffle::getSymbolForBinaryOp(), souffle::toString(), and souffle::AstVisitor< void, std::ostream & >::visit().
{
         // process unary operators
         if (dynamic_cast<const AstUnaryFunctor*>(&fun)) {
             throw UnsupportedConstructException("Unsupported function: " + toString(fun));
         } else if (const auto* binary = dynamic_cast<const AstBinaryFunctor*>(&fun)) {
             std::string sym = getSymbolForBinaryOp(binary->getFunction());
             out << "(";
             visit(*binary->getLHS(), out);
             out << sym;
             visit(*binary->getRHS(), out);
             out << ")";
         } else {
             assert(false && "Unsupported functor!");
         }
     }
void souffle::LogicbloxConverter::visitNegation (const AstNegation & neg, std::ostream & out) inline override private
Definition at line 230 of file souffle2lb.cpp.
References souffle::AstNegation::getAtom(), and souffle::AstVisitor< void, std::ostream & >::visit().
{
         out << "!";
         visit(*neg.getAtom(), out);
     }
void souffle::LogicbloxConverter::visitNode (const AstNode & node, std::ostream &) inline override private
Definition at line 281 of file souffle2lb.cpp.
References souffle::toString().
{
         throw UnsupportedConstructException(
                 "Unable to convert the following language construct into bddbddb format: " + toString(node));
     }
void souffle::LogicbloxConverter::visitNumberConstant (const AstNumberConstant & num, std::ostream & out) inline override private
Definition at line 245 of file souffle2lb.cpp.
{
         out << num;
     }
void souffle::LogicbloxConverter::visitProgram (const AstProgram & program, std::ostream & out) inline override private
The entry point for the conversion of a program, converting the basic top-level structure.
Definition at line 113 of file souffle2lb.cpp.
References souffle::AstProgram::getRelations(), rel(), and souffle::AstVisitor< void, std::ostream & >::visit().
{
         // declarations
         for (const auto& rel : program.getRelations()) {
             // process the relation declaration
             visit(*rel, out);
         }
         out << "\n";
         // rules
         for (const auto& rel : program.getRelations()) {
             for (const auto& clause : rel->getClauses()) {
                 visit(*clause, out);
             }
         }
         out << "\n";
     }
void souffle::LogicbloxConverter::visitRelation (const AstRelation & rel, std::ostream &) inline override private
Converting a relation by creating its declaration.
Definition at line 133 of file souffle2lb.cpp.
References convertTypeName(), dout, eout, souffle::AstRelation::getAttributes(), souffle::AstRelation::getName(), i, iout, souffle::AstRelation::isInput(), souffle::AstRelation::isOutput(), souffle::AstRelation::isPrintSize(), souffle::join(), and visitRelationIdentifier().
{
         visitRelationIdentifier(rel.getName(), dout);
         // make nullary relations single-element relations
         dout << "(";
         dout << join(rel.getAttributes(), ",",
                 [&](std::ostream& os, AstAttribute* cur) { os << cur->getAttributeName(); });
         dout << ") -> ";
         dout << join(rel.getAttributes(), ",", [&](std::ostream& os, AstAttribute* cur) {
             os << convertTypeName(cur->getTypeName()) << "(" << cur->getAttributeName() << ")";
         });
         dout << ".";
         dout << "\n";
         if (rel.isInput()) {
             int i = 0;
             iout << "fromFile,"
                  << "\"" << rel.getName() << ".facts\",";
             iout << join(rel.getAttributes(), ",", [&](std::ostream& os, AstAttribute* cur) {
                 os << "column:" << (i) << "," << rel.getName() << ":" << (i);
                 i++;
             });
             iout << "\n";
             iout << "toPredicate," << rel.getName() << ",";
             i = 0;
             iout << join(rel.getAttributes(), ",", [&](std::ostream& os, AstAttribute* cur) {
                 os << rel.getName() << ":" << (i);
                 i++;
             });
             iout << "\n";
         }
         if (rel.isOutput() || rel.isPrintSize()) {
             int i = 0;
             eout << "fromPredicate," << rel.getName() << ",";
             eout << join(rel.getAttributes(), ",", [&](std::ostream& os, AstAttribute* cur) {
                 os << rel.getName() << ":" << (i);
                 i++;
             });
             eout << "\n";
             i = 0;
             eout << "toFile,"
                  << "\"" << rel.getName() << ".csv\",";
             eout << join(rel.getAttributes(), ",", [&](std::ostream& os, AstAttribute* cur) {
                 os << "column:" << (i) << "," << rel.getName() << ":" << (i);
                 i++;
             });
             eout << "\n";
         }
     }
void souffle::LogicbloxConverter::visitRelationIdentifier (const AstRelationIdentifier & id, std::ostream & out) inline private
Definition at line 277 of file souffle2lb.cpp.
References souffle::join().
Referenced by visitAtom(), and visitRelation().
{
         out << join(id.getNames(), "_");
     }
void souffle::LogicbloxConverter::visitStringConstant (const AstStringConstant & str, std::ostream & out) inline override private
Definition at line 241 of file souffle2lb.cpp.
References str.
{
         out << str;
     }
void souffle::LogicbloxConverter::visitTypeCast (const AstTypeCast & cast, std::ostream & out) inline override private
Definition at line 249 of file souffle2lb.cpp.
References souffle::AstTypeCast::getValue(), and souffle::AstVisitor< void, std::ostream & >::visit().
{
         visit(*cast.getValue(), out);
     }
void souffle::LogicbloxConverter::visitUnnamedVariable (const AstUnnamedVariable & var, std::ostream & out) inline override private
Definition at line 273 of file souffle2lb.cpp.
{
         out << "_";
     }
void souffle::LogicbloxConverter::visitVariable (const AstVariable & var, std::ostream & out) inline override private
Definition at line 269 of file souffle2lb.cpp.
{
         out << var;
     }
Field Documentation
std::ostream& souffle::LogicbloxConverter::dout private
Definition at line 80 of file souffle2lb.cpp.
Referenced by visitRelation().
std::ostream& souffle::LogicbloxConverter::eout private
Definition at line 79 of file souffle2lb.cpp.
Referenced by LogicbloxConverter(), and visitRelation().
std::vector<std::string> souffle::LogicbloxConverter::extra_literals private
Definition at line 77 of file souffle2lb.cpp.
Referenced by visitClause().
std::ostream& souffle::LogicbloxConverter::iout private
Definition at line 78 of file souffle2lb.cpp.
Referenced by LogicbloxConverter(), and visitRelation().
The documentation for this class was generated from the following file:
souffle2lb.cpp