souffle: souffle::RamSearch Class Reference
souffle::RamSearch Class Reference
Abstract class for relation scans and lookups.
#include <RamOperation.h>
Public Member Functions
void addCondition (std::unique_ptr< RamCondition > c, const RamOperation &root) override
Add condition.
void apply (const RamNodeMapper &map) override
Apply mapper.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getDepth () const override
Get depth of query.
RamOperation * getNestedOperation () const
get nested operation
const RamOperation & getOperation () const
get nested operation
const std::string & getProfileText () const
get profile text
RamSearch (RamNodeType type, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
void addCondition (std::unique_ptr< RamCondition > c)
Add condition.
RamOperation * clone () const override=0
Create clone.
RamCondition * getCondition () const
Get condition.
size_t getLevel () const
Get level.
virtual void print (std::ostream &os, int tabpos) const =0
Print.
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type, size_t l)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
std::string profileText
Additional Inherited Members
Protected Attributes inherited from souffle::RamOperation
std::unique_ptr< RamCondition > condition
condition that is checked for each obtained tuple
size_t level
the nesting level of this operation
Detailed Description
Abstract class for relation scans and lookups.
Definition at line 120 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamSearch::RamSearch (RamNodeType type, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 127 of file RamOperation.h.
             : RamOperation(type, nested->getLevel() - 1), nestedOperation(std::move(nested)),
               profileText(std::move(profileText)) {}
Member Function Documentation
void souffle::RamSearch::addCondition (std::unique_ptr< RamCondition > c, const RamOperation & root) override virtual
Add condition.
add condition
Reimplemented from souffle::RamOperation.
Reimplemented in souffle::RamAggregate, and souffle::RamScan.
Definition at line 42 of file RamOperation.cpp.
References souffle::RamOperation::addCondition(), getNestedOperation(), and souffle::RamOperation::level.
Referenced by souffle::RamScan::addCondition(), and souffle::RamAggregate::addCondition().
{
     assert(c->getLevel() >= level);
     if (c->getLevel() > level) {
         getNestedOperation()->addCondition(std::move(c), root);
         return;
     }
     // use base-class implementation
     RamOperation::addCondition(std::move(c), root);
 }
void souffle::RamSearch::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Reimplemented from souffle::RamOperation.
Reimplemented in souffle::RamAggregate, souffle::RamLookup, and souffle::RamScan.
Definition at line 162 of file RamOperation.h.
References souffle::RamOperation::apply(), map, and nestedOperation.
Referenced by souffle::RamScan::apply(), souffle::RamLookup::apply(), and souffle::RamAggregate::apply().
{
         RamOperation::apply(map);
         nestedOperation = map(std::move(nestedOperation));
     }
bool souffle::RamSearch::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamOperation.
Reimplemented in souffle::RamAggregate, souffle::RamLookup, and souffle::RamScan.
Definition at line 169 of file RamOperation.h.
References souffle::RamOperation::equal(), and getOperation().
Referenced by souffle::RamScan::equal(), souffle::RamLookup::equal(), and souffle::RamAggregate::equal().
{
         assert(nullptr != dynamic_cast<const RamSearch*>(&node));
         const auto& other = static_cast<const RamSearch&>(node);
         return RamOperation::equal(other) && getOperation() == other.getOperation();
     }
std::vector<const RamNode*> souffle::RamSearch::getChildNodes () const inline override virtual
Obtain list of child nodes.
Reimplemented from souffle::RamOperation.
Reimplemented in souffle::RamScan.
Definition at line 155 of file RamOperation.h.
References souffle::RamOperation::getChildNodes(), and nestedOperation.
Referenced by souffle::RamScan::getChildNodes().
{
         auto res = RamOperation::getChildNodes();
         res.push_back(nestedOperation.get());
         return res;
     }
size_t souffle::RamSearch::getDepth () const inline override virtual
Get depth of query.
Implements souffle::RamOperation.
Definition at line 150 of file RamOperation.h.
References nestedOperation.
{
         return 1 + nestedOperation->getDepth();
     }
RamOperation* souffle::RamSearch::getNestedOperation () const inline
get nested operation
Definition at line 132 of file RamOperation.h.
References nestedOperation.
Referenced by addCondition(), souffle::RamScan::clone(), souffle::RamLookup::clone(), souffle::RamAggregate::clone(), souffle::Synthesiser::emitCode(), souffle::Interpreter::evalOp(), souffle::RamScan::print(), souffle::RamLookup::print(), and souffle::RamAggregate::print().
{
         return nestedOperation.get();
     }
const RamOperation& souffle::RamSearch::getOperation () const inline
get nested operation
Definition at line 136 of file RamOperation.h.
References nestedOperation.
Referenced by equal().
{
         assert(nestedOperation);
         return *nestedOperation;
     }
const std::string& souffle::RamSearch::getProfileText () const inline
get profile text
Definition at line 142 of file RamOperation.h.
References profileText.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalOp(), and souffle::Interpreter::executeMain().
{
         return profileText;
     }
Field Documentation
std::unique_ptr<RamOperation> souffle::RamSearch::nestedOperation private
Nested operation.
Definition at line 122 of file RamOperation.h.
Referenced by apply(), getChildNodes(), getDepth(), getNestedOperation(), and getOperation().
std::string souffle::RamSearch::profileText private
Definition at line 124 of file RamOperation.h.
Referenced by getProfileText().
The documentation for this class was generated from the following files:
RamOperation.h
RamOperation.cpp