souffle: souffle::RamSequence Class Reference
souffle::RamSequence Class Reference
Sequence of RAM statements.
#include <RamStatement.h>
Public Member Functions
void add (std::unique_ptr< RamStatement > stmt)
Add new statement to the end of ordered list.
void apply (const RamNodeMapper &map) override
Apply mapper.
RamSequence * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
std::vector< RamStatement * > getStatements () const
Get RAM statements from ordered list.
template<typename T >
void moveSubprograms (std::vector< std::unique_ptr< T >> &destination)
TODO (#541): what's that for ??
void print (std::ostream &os, int tabpos) const override
Pretty print.
RamSequence ()
template<typename... Stmts>
RamSequence (std::unique_ptr< Stmts > &&...stmts)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::vector< std::unique_ptr
< RamStatement > > statements
ordered list of RAM statements
Detailed Description
Sequence of RAM statements.
Execute statement one by one from an ordered list of statements.
Definition at line 464 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamSequence::RamSequence () inline
Definition at line 470 of file RamStatement.h.
Referenced by clone().
 : RamStatement(RN_Sequence) {}
template<typename... Stmts> souffle::RamSequence::RamSequence (std::unique_ptr< Stmts > &&... stmts) inline
Definition at line 473 of file RamStatement.h.
References statements.
                                                  : RamStatement(RN_Sequence) {
         // move all the given statements into the vector (not so simple)
         std::unique_ptr<RamStatement> tmp[] = {std::move(stmts)...};
         for (auto& cur : tmp) {
             statements.emplace_back(std::move(cur));
         }
         for (const auto& cur : statements) {
             (void)cur;
             assert(cur);
         }
     }
Member Function Documentation
void souffle::RamSequence::add (std::unique_ptr< RamStatement > stmt) inline
Add new statement to the end of ordered list.
Definition at line 486 of file RamStatement.h.
References statements.
Referenced by souffle::appendStmt().
{
         if (stmt) {
             statements.push_back(std::move(stmt));
         }
     }
void souffle::RamSequence::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 529 of file RamStatement.h.
References map, and statements.
{
         for (auto& stmt : statements) {
             stmt = map(std::move(stmt));
         }
     }
RamSequence* souffle::RamSequence::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 520 of file RamStatement.h.
References RamSequence(), and statements.
{
         auto* res = new RamSequence();
         for (auto& cur : statements) {
             res->add(std::unique_ptr<RamStatement>(cur->clone()));
         }
         return res;
     }
bool souffle::RamSequence::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 537 of file RamStatement.h.
References souffle::equal_targets(), and statements.
{
         assert(nullptr != dynamic_cast<const RamSequence*>(&node));
         const auto& other = static_cast<const RamSequence&>(node);
         return equal_targets(statements, other.statements);
     }
std::vector<const RamNode*> souffle::RamSequence::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 511 of file RamStatement.h.
References statements.
{
         std::vector<const RamNode*> res;
         for (const auto& cur : statements) {
             res.push_back(cur.get());
         }
         return res;
     }
std::vector<RamStatement*> souffle::RamSequence::getStatements () const inline
Get RAM statements from ordered list.
Definition at line 493 of file RamStatement.h.
References statements, and souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalStmt().
{
         return toPtrVector(statements);
     }
template<typename T > void souffle::RamSequence::moveSubprograms (std::vector< std::unique_ptr< T >> & destination) inline
TODO (#541): what's that for ??
Definition at line 499 of file RamStatement.h.
References souffle::movePtrVector(), and statements.
{
         movePtrVector(statements, destination);
     }
void souffle::RamSequence::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print.
Implements souffle::RamStatement.
Definition at line 504 of file RamStatement.h.
References souffle::join(), and statements.
{
         os << join(statements, ";\n", [&](std::ostream& os, const std::unique_ptr<RamStatement>& stmt) {
             stmt->print(os, tabpos);
         });
     }
Field Documentation
std::vector<std::unique_ptr<RamStatement> > souffle::RamSequence::statements protected
ordered list of RAM statements
Definition at line 467 of file RamStatement.h.
Referenced by add(), apply(), clone(), equal(), getChildNodes(), getStatements(), moveSubprograms(), print(), and RamSequence().
The documentation for this class was generated from the following file:
RamStatement.h