souffle: souffle::AstClause Class Reference
souffle::AstClause Class Reference
Intermediate representation of a datalog clause.
#include <AstClause.h>
Public Member Functions
void addToBody (std::unique_ptr< AstLiteral > l)
Add a Literal to the body of the clause.
void apply (const AstNodeMapper &map) override
Mutates this node.
AstClause ()
Construct an empty clause with empty list of literals and its head set to NULL.
void clearExecutionPlan ()
Resets the execution plan.
AstClause * clone () const override
Creates a clone of this AST sub-structure.
AstClause * cloneHead () const
clone head generates a new clause with the same head but empty body
std::vector< AstAtom * > getAtoms () const
Obtains a list of contained body-atoms.
std::vector
< AstBinaryConstraint * > getBinaryConstraints () const
Obtains a list of binary constraints.
AstLiteral * getBodyLiteral (size_t idx) const
Return the i-th Literal in body of the clause.
std::vector< AstLiteral * > getBodyLiterals () const
Obtains a copy of the internally maintained body literals.
size_t getBodySize () const
Return the number of elements in the body of the Clause.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
size_t getClauseNum () const
Gets the clause number.
std::vector< AstConstraint * > getConstraints () const
Obtains a list of constraints.
const AstExecutionPlan * getExecutionPlan () const
Obtains the execution plan associated to this clause or null if there is none.
AstAtom * getHead () const
Return the atom that represents the head of the clause.
std::vector< AstNegation * > getNegations () const
Obtains a list of contained negations.
bool hasFixedExecutionPlan () const
Determines whether the execution order plan is fixed.
bool isFact () const
Return true if the clause is a fact.
bool isGenerated () const
Determines whether this is a internally generated clause.
bool isRule () const
Return true if the clause is a rule.
void print (std::ostream &os) const override
Print this clause to a given stream.
void reorderAtoms (const std::vector< unsigned int > &newOrder)
Re-orders atoms to be in the given order.
void setClauseNum (size_t num)
Sets the clause number.
void setExecutionPlan (std::unique_ptr< AstExecutionPlan > plan)
Updates the execution plan associated to this clause.
void setFixedExecutionPlan (bool value=true)
Updates the fixed execution order flag.
void setGenerated (bool value=true)
Updates the generated flag.
void setHead (std::unique_ptr< AstAtom > h)
Set the head of clause to h.
~AstClause () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
std::vector< std::unique_ptr
< AstAtom > > atoms
The atoms in the body of this clause.
size_t clauseNum = 0
Stores a unique number for each clause in a relation.
std::vector< std::unique_ptr
< AstConstraint > > constraints
The constraints in the body of this clause.
bool fixedPlan = false
Determines whether the given execution order should be enforced.
bool generated = false
Determines whether this is an internally generated clause resulting from resolving syntactic sugar.
std::unique_ptr< AstAtom > head
The head of the clause.
std::vector< std::unique_ptr
< AstNegation > > negations
The negations in the body of this clause.
std::unique_ptr< AstExecutionPlan > plan
The user defined execution plan – if any.
std::vector< std::unique_ptr
< AstProvenanceNegation > > provNegations
The provenance negations in the body of this clause.
Detailed Description
Intermediate representation of a datalog clause.
A clause can either be:
a fact - a clause with no body (e.g., X(a,b))
a rule - a clause with a head and a body (e.g., Y(a,b) -: X(a,b))
TODO: Currently Clause object is used to represent 2 different types of datalog clauses, such as rules, queries and facts. This solution was to quickly overcome issues related to bottom-up construction of IR. In future, Clause should be made abstract and have 2 subclasses: Rule and Fact.
Definition at line 246 of file AstClause.h.
Constructor & Destructor Documentation
souffle::AstClause::AstClause () inline
Construct an empty clause with empty list of literals and its head set to NULL.
Definition at line 278 of file AstClause.h.
Referenced by clone(), and cloneHead().
 : head(nullptr), plan(nullptr) {}
souffle::AstClause::~AstClause () override default
Member Function Documentation
void souffle::AstClause::addToBody (std::unique_ptr< AstLiteral > l)
Add a Literal to the body of the clause.
Definition at line 32 of file AstClause.cpp.
References atoms, constraints, negations, and provNegations.
Referenced by souffle::getInlinedClause(), souffle::ResolveAliasesTransformer::removeComplexTermsInAtoms(), souffle::RuleBody::toClauseBodies(), and souffle::MagicSetTransformer::transform().
{
     if (dynamic_cast<AstAtom*>(l.get())) {
         atoms.push_back(std::unique_ptr<AstAtom>(static_cast<AstAtom*>(l.release())));
     } else if (dynamic_cast<AstNegation*>(l.get())) {
         negations.push_back(std::unique_ptr<AstNegation>(static_cast<AstNegation*>(l.release())));
     } else if (dynamic_cast<AstProvenanceNegation*>(l.get())) {
         provNegations.push_back(
                 std::unique_ptr<AstProvenanceNegation>(static_cast<AstProvenanceNegation*>(l.release())));
     } else if (dynamic_cast<AstConstraint*>(l.get())) {
         constraints.push_back(std::unique_ptr<AstConstraint>(static_cast<AstConstraint*>(l.release())));
     } else {
         assert(false && "Unsupported literal type!");
     }
 }
void souffle::AstClause::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 415 of file AstClause.h.
References atoms, constraints, head, map, negations, and provNegations.
Referenced by souffle::createAnnotatedClause(), and souffle::inlineBodyLiterals().
{
         head = map(std::move(head));
         for (auto& lit : atoms) {
             lit = map(std::move(lit));
         }
         for (auto& lit : negations) {
             lit = map(std::move(lit));
         }
         for (auto& lit : provNegations) {
             lit = map(std::move(lit));
         }
         for (auto& lit : constraints) {
             lit = map(std::move(lit));
         }
     }
void souffle::AstClause::clearExecutionPlan () inline
Resets the execution plan.
Definition at line 362 of file AstClause.h.
References plan.
{
         plan = nullptr;
     }
AstClause* souffle::AstClause::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstNode.
Definition at line 390 of file AstClause.h.
References AstClause(), atoms, constraints, fixedPlan, generated, getExecutionPlan(), souffle::AstNode::getSrcLoc(), head, negations, plan, and provNegations.
Referenced by cloneHead(), souffle::createAnnotatedClause(), souffle::getInlinedClause(), souffle::inlineBodyLiterals(), souffle::isValidPermutation(), souffle::AstTranslator::makeSubproofSubroutine(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::separateDBs(), souffle::MagicSetTransformer::transform(), souffle::AstTranslator::translateClause(), and souffle::AstTranslator::translateRecursiveRelation().
{
         auto res = new AstClause();
         res->setSrcLoc(getSrcLoc());
         if (getExecutionPlan()) {
             res->setExecutionPlan(std::unique_ptr<AstExecutionPlan>(plan->clone()));
         }
         res->head = (head) ? std::unique_ptr<AstAtom>(head->clone()) : nullptr;
         for (const auto& cur : atoms) {
             res->atoms.push_back(std::unique_ptr<AstAtom>(cur->clone()));
         }
         for (const auto& cur : negations) {
             res->negations.push_back(std::unique_ptr<AstNegation>(cur->clone()));
         }
         for (const auto& cur : provNegations) {
             res->provNegations.push_back(std::unique_ptr<AstProvenanceNegation>(cur->clone()));
         }
         for (const auto& cur : constraints) {
             res->constraints.push_back(std::unique_ptr<AstConstraint>(cur->clone()));
         }
         res->fixedPlan = fixedPlan;
         res->generated = generated;
         return res;
     }
AstClause* souffle::AstClause::cloneHead () const inline
clone head generates a new clause with the same head but empty body
Definition at line 432 of file AstClause.h.
References AstClause(), clone(), getExecutionPlan(), getHead(), souffle::AstNode::getSrcLoc(), hasFixedExecutionPlan(), setExecutionPlan(), setFixedExecutionPlan(), setHead(), and souffle::AstNode::setSrcLoc().
Referenced by souffle::getInlinedClause(), and souffle::ResolveAliasesTransformer::removeTrivialEquality().
{
         auto* clone = new AstClause();
         clone->setSrcLoc(getSrcLoc());
         clone->setHead(std::unique_ptr<AstAtom>(getHead()->clone()));
         if (getExecutionPlan()) {
             clone->setExecutionPlan(std::unique_ptr<AstExecutionPlan>(getExecutionPlan()->clone()));
         }
         clone->setFixedExecutionPlan(hasFixedExecutionPlan());
         return clone;
     }
bool souffle::AstClause::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 463 of file AstClause.h.
References atoms, constraints, souffle::equal_targets(), head, and negations.
{
         assert(nullptr != dynamic_cast<const AstClause*>(&node));
         const auto& other = static_cast<const AstClause&>(node);
         return *head == *other.head && equal_targets(atoms, other.atoms) &&
                equal_targets(negations, other.negations) && equal_targets(constraints, other.constraints);
     }
std::vector<AstAtom*> souffle::AstClause::getAtoms () const inline
Obtains a list of contained body-atoms.
Definition at line 308 of file AstClause.h.
References atoms, and souffle::toPtrVector().
Referenced by souffle::AstSemanticChecker::checkClause(), souffle::RecursiveClauses::computeIsRecursive(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::MagicSetTransformer::transform(), souffle::AstTranslator::translateClause(), and souffle::AstTranslator::translateRecursiveRelation().
{
         return toPtrVector(atoms);
     }
std::vector<AstBinaryConstraint*> souffle::AstClause::getBinaryConstraints () const inline
Obtains a list of binary constraints.
Definition at line 323 of file AstClause.h.
References constraints.
{
         std::vector<AstBinaryConstraint*> result;
         for (auto& constraint : constraints) {
             if (auto* br = dynamic_cast<AstBinaryConstraint*>(constraint.get())) {
                 result.push_back(br);
             }
         }
         return result;
     }
AstLiteral * souffle::AstClause::getBodyLiteral (size_t idx) const
Return the i-th Literal in body of the clause.
Definition at line 53 of file AstClause.cpp.
References atoms, constraints, negations, and provNegations.
Referenced by souffle::isValidMove().
{
     if (idx < atoms.size()) {
         return atoms[idx].get();
     }
     idx -= atoms.size();
     if (idx < negations.size()) {
         return negations[idx].get();
     }
     idx -= negations.size();
     if (idx < provNegations.size()) {
         return provNegations[idx].get();
     }
     idx -= provNegations.size();
     return constraints[idx].get();
 }
std::vector< AstLiteral * > souffle::AstClause::getBodyLiterals () const
Obtains a copy of the internally maintained body literals.
Definition at line 69 of file AstClause.cpp.
References atoms, constraints, negations, and provNegations.
Referenced by souffle::areBijectivelyEquivalent(), souffle::AstSemanticChecker::checkWitnessProblem(), souffle::getBodyRelations(), souffle::getInlinedClause(), souffle::inlineBodyLiterals(), souffle::isValidPermutation(), souffle::makeInfoRelation(), print(), souffle::ResolveAliasesTransformer::removeComplexTermsInAtoms(), souffle::ResolveAliasesTransformer::removeTrivialEquality(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::AstTranslator::translateClause(), souffle::AstTranslator::translateProgram(), souffle::BddBddBTranslator::visitClause(), and souffle::LogicbloxConverter::visitClause().
{
     std::vector<AstLiteral*> res;
     for (auto& cur : atoms) {
         res.push_back(cur.get());
     }
     for (auto& cur : negations) {
         res.push_back(cur.get());
     }
     for (auto& cur : provNegations) {
         res.push_back(cur.get());
     }
     for (auto& cur : constraints) {
         res.push_back(cur.get());
     }
     return res;
 }
size_t souffle::AstClause::getBodySize () const inline
Return the number of elements in the body of the Clause.
Definition at line 294 of file AstClause.h.
References atoms, constraints, negations, and provNegations.
Referenced by isFact(), print(), and souffle::RemoveRelationCopiesTransformer::removeRelationCopies().
{
         return atoms.size() + negations.size() + provNegations.size() + constraints.size();
     }
std::vector<const AstNode*> souffle::AstClause::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 444 of file AstClause.h.
References atoms, constraints, head, negations, and provNegations.
{
         std::vector<const AstNode*> res = {head.get()};
         for (auto& cur : atoms) {
             res.push_back(cur.get());
         }
         for (auto& cur : negations) {
             res.push_back(cur.get());
         }
         for (auto& cur : provNegations) {
             res.push_back(cur.get());
         }
         for (auto& cur : constraints) {
             res.push_back(cur.get());
         }
         return res;
     }
size_t souffle::AstClause::getClauseNum () const inline
Gets the clause number.
Definition at line 377 of file AstClause.h.
References clauseNum.
Referenced by souffle::makeInfoRelation(), and souffle::AstTranslator::translateProgram().
{
         return clauseNum;
     }
std::vector<AstConstraint*> souffle::AstClause::getConstraints () const inline
Obtains a list of constraints.
Definition at line 318 of file AstClause.h.
References constraints, and souffle::toPtrVector().
Referenced by souffle::AstSemanticChecker::checkClause().
{
         return toPtrVector(constraints);
     }
const AstExecutionPlan* souffle::AstClause::getExecutionPlan () const inline
Obtains the execution plan associated to this clause or null if there is none.
Definition at line 352 of file AstClause.h.
References plan.
Referenced by souffle::AstSemanticChecker::checkClause(), clone(), cloneHead(), print(), souffle::AstTranslator::translateClause(), and souffle::AstTranslator::translateRecursiveRelation().
{
         return plan.get();
     }
AstAtom* souffle::AstClause::getHead () const inline
Return the atom that represents the head of the clause.
Definition at line 289 of file AstClause.h.
References head.
Referenced by souffle::AstSemanticChecker::checkClause(), souffle::AstSemanticChecker::checkFact(), souffle::AstSemanticChecker::checkWitnessProblem(), cloneHead(), souffle::getBodyRelations(), souffle::getGroundedTerms(), souffle::getHeadRelation(), souffle::getInlinedClause(), souffle::inlineBodyLiterals(), souffle::isValidMove(), souffle::isValidPermutation(), souffle::makeInfoRelation(), souffle::AstProgram::removeClause(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::separateDBs(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::AstTranslator::translateClause(), souffle::AstTranslator::translateProgram(), souffle::AstTranslator::translateRecursiveRelation(), souffle::BddBddBTranslator::visitClause(), and souffle::LogicbloxConverter::visitClause().
{
         return head.get();
     }
std::vector<AstNegation*> souffle::AstClause::getNegations () const inline
Obtains a list of contained negations.
Definition at line 313 of file AstClause.h.
References negations, and souffle::toPtrVector().
Referenced by souffle::AstSemanticChecker::checkClause().
{
         return toPtrVector(negations);
     }
bool souffle::AstClause::hasFixedExecutionPlan () const inline
Determines whether the execution order plan is fixed.
Definition at line 347 of file AstClause.h.
References fixedPlan.
Referenced by cloneHead().
{
         return fixedPlan;
     }
bool souffle::AstClause::isFact () const
Return true if the clause is a fact.
Definition at line 86 of file AstClause.cpp.
References getBodySize(), head, and souffle::visitDepthFirst().
Referenced by souffle::AstSemanticChecker::checkClause(), souffle::AstSemanticChecker::checkFact(), souffle::AstSemanticChecker::checkProgram(), isRule(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::AstTranslator::translateClause(), souffle::BddBddBTranslator::visitClause(), and souffle::LogicbloxConverter::visitClause().
{
     // there must be a head
     if (head == nullptr) {
         return false;
     }
     // there must not be any body clauses
     if (getBodySize() != 0) {
         return false;
     }
     // and there are no aggregates
     bool hasAggregates = false;
     visitDepthFirst(*head, [&](const AstAggregator& cur) { hasAggregates = true; });
     return !hasAggregates;
 }
bool souffle::AstClause::isGenerated () const inline
Determines whether this is a internally generated clause.
Definition at line 367 of file AstClause.h.
References generated.
Referenced by souffle::AstSemanticChecker::checkClause().
{
         return generated;
     }
bool souffle::AstClause::isRule () const inline
Return true if the clause is a rule.
Definition at line 334 of file AstClause.h.
References head, and isFact().
Referenced by souffle::AstTranslator::translateClause().
{
         return head && !isFact();
     }
void souffle::AstClause::print (std::ostream & os) const override virtual
Print this clause to a given stream.
Implements souffle::AstNode.
Definition at line 101 of file AstClause.cpp.
References getBodyLiterals(), getBodySize(), getExecutionPlan(), head, souffle::join(), and souffle::AstExecutionPlan::print().
Referenced by souffle::makeInfoRelation().
{
     if (head != nullptr) {
         head->print(os);
     }
     if (getBodySize() > 0) {
         os << " :- \n   ";
         os << join(getBodyLiterals(), ",\n   ", print_deref<AstLiteral*>());
     }
     os << ".";
     if (getExecutionPlan()) {
         getExecutionPlan()->print(os);
     }
 }
void souffle::AstClause::reorderAtoms (const std::vector< unsigned int > & newOrder)
Re-orders atoms to be in the given order.
Definition at line 115 of file AstClause.cpp.
References atoms, and i.
Referenced by souffle::MagicSetTransformer::transform().
{
     // Validate given order
     assert(newOrder.size() == atoms.size());
     std::vector<unsigned int> nopOrder;
     for (unsigned int i = 0; i < atoms.size(); i++) {
         nopOrder.push_back(i);
     }
     assert(std::is_permutation(nopOrder.begin(), nopOrder.end(), newOrder.begin()));
     // Reorder atoms
     std::vector<std::unique_ptr<AstAtom>> oldAtoms(atoms.size());
     atoms.swap(oldAtoms);
     for (unsigned int i = 0; i < newOrder.size(); i++) {
         atoms[i].swap(oldAtoms[newOrder[i]]);
     }
 }
void souffle::AstClause::setClauseNum (size_t num) inline
Sets the clause number.
Definition at line 382 of file AstClause.h.
References clauseNum.
{
         clauseNum = num;
     }
void souffle::AstClause::setExecutionPlan (std::unique_ptr< AstExecutionPlan > plan) inline
Updates the execution plan associated to this clause.
Definition at line 357 of file AstClause.h.
Referenced by cloneHead().
{
         this->plan = std::move(plan);
     }
void souffle::AstClause::setFixedExecutionPlan (bool value = true) inline
Updates the fixed execution order flag.
Definition at line 342 of file AstClause.h.
References fixedPlan.
Referenced by cloneHead().
{
         fixedPlan = value;
     }
void souffle::AstClause::setGenerated (bool value = true) inline
Updates the generated flag.
Definition at line 372 of file AstClause.h.
References generated.
{
         generated = value;
     }
void souffle::AstClause::setHead (std::unique_ptr< AstAtom > h)
Set the head of clause to h.
Definition at line 48 of file AstClause.cpp.
References head.
Referenced by cloneHead().
{
     assert(!head && "Head is already set");
     head = std::move(h);
 }
Field Documentation
std::vector<std::unique_ptr<AstAtom> > souffle::AstClause::atoms protected
The atoms in the body of this clause.
Definition at line 252 of file AstClause.h.
Referenced by addToBody(), apply(), clone(), equal(), getAtoms(), getBodyLiteral(), getBodyLiterals(), getBodySize(), getChildNodes(), and reorderAtoms().
size_t souffle::AstClause::clauseNum = 0 protected
Stores a unique number for each clause in a relation.
Definition at line 273 of file AstClause.h.
Referenced by getClauseNum(), and setClauseNum().
std::vector<std::unique_ptr<AstConstraint> > souffle::AstClause::constraints protected
The constraints in the body of this clause.
Definition at line 261 of file AstClause.h.
Referenced by addToBody(), apply(), clone(), equal(), getBinaryConstraints(), getBodyLiteral(), getBodyLiterals(), getBodySize(), getChildNodes(), and getConstraints().
bool souffle::AstClause::fixedPlan = false protected
Determines whether the given execution order should be enforced.
Definition at line 264 of file AstClause.h.
Referenced by clone(), hasFixedExecutionPlan(), and setFixedExecutionPlan().
bool souffle::AstClause::generated = false protected
Determines whether this is an internally generated clause resulting from resolving syntactic sugar.
Definition at line 270 of file AstClause.h.
Referenced by clone(), isGenerated(), and setGenerated().
std::unique_ptr<AstAtom> souffle::AstClause::head protected
The head of the clause.
Definition at line 249 of file AstClause.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getHead(), isFact(), isRule(), print(), and setHead().
std::vector<std::unique_ptr<AstNegation> > souffle::AstClause::negations protected
The negations in the body of this clause.
Definition at line 255 of file AstClause.h.
Referenced by addToBody(), apply(), clone(), equal(), getBodyLiteral(), getBodyLiterals(), getBodySize(), getChildNodes(), and getNegations().
std::unique_ptr<AstExecutionPlan> souffle::AstClause::plan protected
The user defined execution plan – if any.
Definition at line 267 of file AstClause.h.
Referenced by clearExecutionPlan(), clone(), and getExecutionPlan().
std::vector<std::unique_ptr<AstProvenanceNegation> > souffle::AstClause::provNegations protected
The provenance negations in the body of this clause.
Definition at line 258 of file AstClause.h.
Referenced by addToBody(), apply(), clone(), getBodyLiteral(), getBodyLiterals(), getBodySize(), and getChildNodes().
The documentation for this class was generated from the following files:
AstClause.h
AstClause.cpp