souffle: souffle::BinaryRelation< TupleType >::iterator Class Reference
souffle::BinaryRelation< TupleType >::iterator Class Reference
#include <BinaryRelation.h>
Public Member Functions
void initCheckEnd ()
special fn to set endVal = true only set when the current iterator actually cannot iterate anymore should only be called in the constructor
iterator (bool truthy, const BinaryRelation *br)
iterator (const BinaryRelation *br)
iterator (const BinaryRelation *br, const TupleType &start)
iterator (const BinaryRelation *br, const TupleType &start, const TupleType &end)
iterator (const BinaryRelation *br, DomainInt rep, std::shared_ptr< souffle::Trie< 1 >> trie)
iterator (const BinaryRelation *br, std::list< DomainInt > fronts, std::shared_ptr< souffle::Trie< 1 >> trie)
iterator (const iterator &other)=default
iterator (iterator &&other)=default
bool operator!= (const iterator &other) const
const TupleType & operator* () const
iterator & operator++ ()
const TupleType * operator-> () const
iterator & operator= (const iterator &other)=default
bool operator== (const iterator &other) const
Private Types
enum IterType {
BASIC, STARTAT, BETWEEN, CLOSURE,
FRONTPROD
}
Private Member Functions
bool advanceFrontIter ()
Helper function to make the frontIter jump to the next valid Trie & update the current one.
void ffIterators (const TupleType &startVal)
Fast forward the iterators in iterList (and also frontIter and backIter) s.t.
void initIterator (std::shared_ptr< souffle::Trie< 1 >> trie)
Single Trie Version of initIterators Only initialise one trie iterator.
void initIterators ()
Adjust the iterators to point to the beginning of each trie.
bool isTrieEnd (souffle::Trie< 1 >::iterator iter)
Returns whether iter has reached the end of cTrie.
void setValue ()
yield the current iterator value to update to what the iterator is currently pointing at
Private Attributes
souffle::Trie< 1 >::iterator backIter
const BinaryRelation * br = nullptr
std::shared_ptr< souffle::Trie< 1 > > cTrie
std::unordered_map
< std::shared_ptr
< souffle::Trie
< 1 > >, souffle::Trie
< 1 >::iterator > cTrieEnds
TupleType endPoint
souffle::Trie< 1 >::iterator frontIter
std::list< DomainInt > fronts
bool isEndVal = false
std::list< std::pair
< std::shared_ptr
< souffle::Trie
< 1 > >, souffle::Trie
< 1 >::iterator > > iterList
IterType ityp
DomainInt rep
TupleType value
Detailed Description
template<typename TupleType>
class souffle::BinaryRelation< TupleType >::iterator
Definition at line 222 of file BinaryRelation.h.
Member Enumeration Documentation
template<typename TupleType> enum souffle::BinaryRelation::iterator::IterType private
Enumerator
BASIC
STARTAT
BETWEEN
CLOSURE
FRONTPROD
Definition at line 230 of file BinaryRelation.h.
 { BASIC, STARTAT, BETWEEN, CLOSURE, FRONTPROD };
Constructor & Destructor Documentation
template<typename TupleType> souffle::BinaryRelation< TupleType >::iterator::iterator (bool truthy, const BinaryRelation * br) inline
Definition at line 253 of file BinaryRelation.h.
 : isEndVal(true), br(br){};
template<typename TupleType> souffle::BinaryRelation< TupleType >::iterator::iterator (const BinaryRelation * br) inline
Definition at line 256 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::BASIC, souffle::BinaryRelation< TupleType >::iterator::initCheckEnd(), souffle::BinaryRelation< TupleType >::iterator::initIterators(), souffle::BinaryRelation< TupleType >::iterator::ityp, and souffle::BinaryRelation< TupleType >::iterator::setValue().
                                            : br(br) {
             ityp = BASIC;
             initIterators();
             initCheckEnd();
             setValue();
         }
template<typename TupleType> souffle::BinaryRelation< TupleType >::iterator::iterator (const BinaryRelation * br, const TupleType & start) inline
Definition at line 264 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::ffIterators(), souffle::BinaryRelation< TupleType >::iterator::initCheckEnd(), souffle::BinaryRelation< TupleType >::iterator::initIterators(), souffle::BinaryRelation< TupleType >::iterator::isEndVal, souffle::BinaryRelation< TupleType >::iterator::ityp, souffle::SparseDisjointSet< SparseDomain >::nodeExists(), souffle::BinaryRelation< TupleType >::sds, souffle::BinaryRelation< TupleType >::iterator::setValue(), and souffle::BinaryRelation< TupleType >::iterator::STARTAT.
                                                                    : br(br) {
             ityp = STARTAT;
             if (!br->sds.nodeExists(start[0]) || !br->sds.nodeExists(start[1])) {
                 isEndVal = true;
                 return;
             }
             initIterators();
             ffIterators(start);
             initCheckEnd();
             setValue();
         };
template<typename TupleType> souffle::BinaryRelation< TupleType >::iterator::iterator (const BinaryRelation * br, const TupleType & start, const TupleType & end) inline
Definition at line 279 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::BETWEEN, souffle::BinaryRelation< TupleType >::iterator::ffIterators(), souffle::BinaryRelation< TupleType >::iterator::initCheckEnd(), souffle::BinaryRelation< TupleType >::iterator::initIterators(), souffle::BinaryRelation< TupleType >::iterator::isEndVal, souffle::BinaryRelation< TupleType >::iterator::ityp, souffle::SparseDisjointSet< SparseDomain >::nodeExists(), souffle::BinaryRelation< TupleType >::sds, and souffle::BinaryRelation< TupleType >::iterator::setValue().
                 : br(br), endPoint(end) {
             ityp = BETWEEN;
             if (!br->sds.nodeExists(start[0]) || !br->sds.nodeExists(start[1])) {
                 isEndVal = true;
                 return;
             }
             initIterators();
             ffIterators(start);
             initCheckEnd();
             setValue();
         }
template<typename TupleType> souffle::BinaryRelation< TupleType >::iterator::iterator (const BinaryRelation * br, DomainInt rep, std::shared_ptr< souffle::Trie< 1 >> trie) inline
Definition at line 295 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::CLOSURE, souffle::BinaryRelation< TupleType >::iterator::initIterator(), souffle::BinaryRelation< TupleType >::iterator::isEndVal, souffle::BinaryRelation< TupleType >::iterator::ityp, souffle::SparseDisjointSet< SparseDomain >::nodeExists(), souffle::BinaryRelation< TupleType >::sds, and souffle::BinaryRelation< TupleType >::iterator::setValue().
                 : br(br), rep(rep) {
             ityp = CLOSURE;
             if (!br->sds.nodeExists(rep)) {
                 isEndVal = true;
                 return;
             }
             initIterator(trie);
             setValue();
         }
template<typename TupleType> souffle::BinaryRelation< TupleType >::iterator::iterator (const BinaryRelation * br, std::list< DomainInt > fronts, std::shared_ptr< souffle::Trie< 1 >> trie) inline
Definition at line 308 of file BinaryRelation.h.
References souffle::any_of(), souffle::BinaryRelation< TupleType >::iterator::frontIter, souffle::BinaryRelation< TupleType >::iterator::FRONTPROD, souffle::BinaryRelation< TupleType >::iterator::initIterator(), souffle::BinaryRelation< TupleType >::iterator::ityp, n, souffle::SparseDisjointSet< SparseDomain >::nodeExists(), souffle::BinaryRelation< TupleType >::sds, and souffle::BinaryRelation< TupleType >::iterator::setValue().
                 : br(br), fronts(fronts) {
             if (std::any_of(
                         fronts.begin(), fronts.end(), [&](DomainInt n) { return !br->sds.nodeExists(n); }))
                 throw "non-existent nodes provided";
             ityp = FRONTPROD;
             initIterator(trie);
             // fast forward iter to the first requirement
             auto f = this->fronts.front();
             this->fronts.pop_front();
             while ((*frontIter)[0] != f) ++frontIter;
             setValue();
         }
template<typename TupleType> souffle::BinaryRelation< TupleType >::iterator::iterator (const iterator & other) default
template<typename TupleType> souffle::BinaryRelation< TupleType >::iterator::iterator (iterator && other) default
Member Function Documentation
template<typename TupleType> bool souffle::BinaryRelation< TupleType >::iterator::advanceFrontIter () inline private
Helper function to make the frontIter jump to the next valid Trie & update the current one.
Returns
whether we've reached end() or not
Definition at line 399 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::backIter, souffle::BinaryRelation< TupleType >::iterator::CLOSURE, souffle::BinaryRelation< TupleType >::iterator::cTrie, souffle::BinaryRelation< TupleType >::iterator::frontIter, souffle::BinaryRelation< TupleType >::iterator::FRONTPROD, souffle::BinaryRelation< TupleType >::iterator::fronts, souffle::BinaryRelation< TupleType >::iterator::isEndVal, souffle::BinaryRelation< TupleType >::iterator::iterList, souffle::BinaryRelation< TupleType >::iterator::ityp, and x.
Referenced by souffle::BinaryRelation< TupleType >::iterator::operator++().
{
             // if we're at the end of this current Trie
             if (frontIter == cTrie->end() || ++souffle::Trie<1>::iterator(frontIter) == cTrie->end()) {
                 // reaching the end of this trie means that the closure has completed
                 if (ityp == CLOSURE || ityp == FRONTPROD) {
                     isEndVal = true;
                     return true;
                 }
                 // remove this trie from iterList as it means we've exhausted it
                 iterList.remove_if(
                         [&](std::pair<std::shared_ptr<souffle::Trie<1>>, souffle::Trie<1>::iterator> x) {
                             return x.first == cTrie;
                         });
                 // have we exhausted all other tries?
                 if (iterList.empty()) {
                     isEndVal = true;
                     return true;
                 }
                 // find the next smallest Trie
                 bool isStart = true;
                 std::pair<std::shared_ptr<souffle::Trie<1>>, souffle::Trie<1>::iterator>* ref = nullptr;
                 for (auto& x : iterList) {
                     if (isStart || (*x.second)[0] < (*frontIter)[0]) {
                         ref = &x;
                         cTrie = x.first;
                         frontIter = souffle::Trie<1>::iterator(x.second);
                         isStart = false;
                     }
                 }
                 // as we've made frontIter point to this, we move our iter to the next one in the Trie
                 ++ref->second;
                 backIter = cTrie->begin();
             } else {
                 if (ityp == FRONTPROD) {
                     // no more front closure?
                     if (fronts.empty()) {
                         isEndVal = true;
                         return true;
                     }
                     // step frontIter until we hit the next valid fronts
                     auto newFront = fronts.front();
                     fronts.pop_front();
                     do {
                         ++frontIter;
                     } while ((*frontIter)[0] != newFront);
                 } else {
                     // we can just step frontIter along one, because it will not step past the end of a trie
                     ++frontIter;
                     // step the front reference pointer one along
                     for (auto& x : iterList) {
                         if (x.first == cTrie) {
                             ++x.second;
                             break;
                         }
                     }
                 }
                 backIter = cTrie->begin();
             }
             // we live to yield another time
             return false;
         }
template<typename TupleType> void souffle::BinaryRelation< TupleType >::iterator::ffIterators (const TupleType & startVal) inline private
Fast forward the iterators in iterList (and also frontIter and backIter) s.t.
they point to positions >= start
Parameters
startVal the first pair that the iterators should be fast forwarded to
Definition at line 524 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::backIter, souffle::BinaryRelation< TupleType >::iterator::cTrie, souffle::BinaryRelation< TupleType >::iterator::frontIter, souffle::BinaryRelation< TupleType >::iterator::iterList, and x.
Referenced by souffle::BinaryRelation< TupleType >::iterator::iterator().
{
             souffle::Trie<1>::iterator smallestFirst;
             bool start = true;
             for (auto& x : iterList) {
                 auto checkIter = x.first->begin();
                 auto tmpIter = checkIter;
                 auto endTrieIter = x.first->end();
                 // keep moving iterators forward until we hit something valid
                 // this is based off the assumption that all elements in iterList do not begin at .end()
                 while ((*x.second)[0] < startVal[0]) {
                     ++x.second;
                     if (x.second == x.first->end()) {
                         // iterList.remove(x);
                         // TODO: erase this trie from list - we should use .erase instead of remove(), as we
                         // shouldn't iterate over the trie again!
                         // prematurely continue the outerLoop, because we shouldn't consider this value
                         goto breakLoop;
                     }
                 }
                 // check if we have to discard this trie -
                 // this happens when the trie that contains startVal[0], does not have a value larger than
                 // startVal[1]
                 // todo: we are finding the last element inefficiently, should be a faster way to find it
                 // faster
                 if ((*x.second)[0] == startVal[0]) {
                     while (checkIter != endTrieIter) {
                         // lag the iterator one behind to capture the last element
                         tmpIter = checkIter;
                         ++checkIter;
                     };
                     if ((*tmpIter)[0] < startVal[1]) {
                         ++x.second;
                         if (x.second == x.first->end()) {
                             // iterList.erase(x);
                             // TODO: erase this trie from list - we should use .erase instead of remove(), as
                             // we shouldn't iterate over the trie again!
                             // prematurely continue the outerLoop, because we shouldn't consider this value
                             goto breakLoop;
                         }
                     }
                 }
                 // update the frontIter to point to the front most trie now
                 if (start || ((*x.second) < *smallestFirst)) {
                     smallestFirst = souffle::Trie<1>::iterator(x.second);
                     cTrie = x.first;
                     start = false;
                 }
             breakLoop:;
             }
             frontIter = smallestFirst;
             backIter = cTrie->begin();
             // fast forward the back iterator to point to its starting element
             if ((*frontIter)[0] == startVal[0]) {
                 while ((*backIter)[0] < startVal[1]) ++backIter;
             }
         }
template<typename TupleType> void souffle::BinaryRelation< TupleType >::iterator::initCheckEnd () inline
special fn to set endVal = true only set when the current iterator actually cannot iterate anymore should only be called in the constructor
Definition at line 327 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::backIter, souffle::BinaryRelation< TupleType >::iterator::cTrie, souffle::BinaryRelation< TupleType >::iterator::frontIter, and souffle::BinaryRelation< TupleType >::iterator::isEndVal.
Referenced by souffle::BinaryRelation< TupleType >::iterator::iterator().
{
             if (!cTrie || (frontIter == cTrie->end() && backIter == cTrie->end())) {
                 isEndVal = true;
             }
         }
template<typename TupleType> void souffle::BinaryRelation< TupleType >::iterator::initIterator (std::shared_ptr< souffle::Trie< 1 >> trie) inline private
Single Trie Version of initIterators Only initialise one trie iterator.
Parameters
trie the trie that we point everything towards
Definition at line 513 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::backIter, souffle::Trie< Dim >::begin(), souffle::BinaryRelation< TupleType >::iterator::cTrie, and souffle::BinaryRelation< TupleType >::iterator::frontIter.
Referenced by souffle::BinaryRelation< TupleType >::iterator::iterator().
{
             frontIter = trie->begin();
             backIter = trie->begin();
             cTrie = trie;
         }
template<typename TupleType> void souffle::BinaryRelation< TupleType >::iterator::initIterators () inline private
Adjust the iterators to point to the beginning of each trie.
Definition at line 484 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::backIter, souffle::BinaryRelation< TupleType >::iterator::br, souffle::BinaryRelation< TupleType >::iterator::cTrie, souffle::BinaryRelation< TupleType >::iterator::cTrieEnds, souffle::BinaryRelation< TupleType >::iterator::frontIter, souffle::BinaryRelation< TupleType >::iterator::iterList, souffle::BinaryRelation< TupleType >::orderedStates, and x.
Referenced by souffle::BinaryRelation< TupleType >::iterator::iterator().
{
             bool start = true;
             for (auto& x : br->orderedStates) {
                 auto iterBeg = x.second->begin();
                 // find the smallest front element of the Tries to set the frontIter to
                 if (start) {
                     frontIter = souffle::Trie<1>::iterator(x.second->begin());
                     backIter = souffle::Trie<1>::iterator(frontIter);
                     cTrie = x.second;
                     start = false;
                 } else if ((*iterBeg)[0] <= (*frontIter)[0]) {
                     // if the current one is smaller, that becomes the smallest iter
                     frontIter = iterBeg;
                     backIter = souffle::Trie<1>::iterator(frontIter);
                     cTrie = x.second;
                 }
                 iterList.push_back(std::make_pair(x.second, iterBeg));
                 // add to hash map
                 cTrieEnds[x.second] = x.second->end();
             }
         }
template<typename TupleType> bool souffle::BinaryRelation< TupleType >::iterator::isTrieEnd (souffle::Trie< 1 >::iterator iter) inline private
Returns whether iter has reached the end of cTrie.
Definition at line 391 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::cTrie, and souffle::BinaryRelation< TupleType >::iterator::cTrieEnds.
{
             return iter == cTrieEnds[cTrie];
         }
template<typename TupleType> bool souffle::BinaryRelation< TupleType >::iterator::operator!= (const iterator & other) const inline
Definition at line 347 of file BinaryRelation.h.
{
             return !((*this) == other);
         }
template<typename TupleType> const TupleType& souffle::BinaryRelation< TupleType >::iterator::operator* () const inline
Definition at line 351 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::value.
{
             return value;
         }
template<typename TupleType> iterator& souffle::BinaryRelation< TupleType >::iterator::operator++ () inline
Definition at line 359 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::advanceFrontIter(), souffle::BinaryRelation< TupleType >::iterator::backIter, souffle::BinaryRelation< TupleType >::iterator::BETWEEN, souffle::BinaryRelation< TupleType >::iterator::cTrie, souffle::BinaryRelation< TupleType >::iterator::endPoint, souffle::BinaryRelation< TupleType >::iterator::frontIter, souffle::BinaryRelation< TupleType >::iterator::isEndVal, souffle::BinaryRelation< TupleType >::iterator::ityp, and souffle::BinaryRelation< TupleType >::iterator::setValue().
{
             if (isEndVal) throw "error: incrementing an out of range iterator";
             // if we're at the end of our iter, we must jump ahead
             if (backIter == cTrie->end() || ++souffle::Trie<1>::iterator(backIter) == cTrie->end()) {
                 // if we cannot do anything more, we quit prematurely, and mark that we've reached the end
                 if (advanceFrontIter()) return *this;
                 // ^^ the above function also sets backIter to point to the correct point
             } else {
                 // we can just step backIter along one
                 ++backIter;
             }
             // if its a iterate_until iterator, we should check if the current "value" is > end point
             // if so, mark it as end
             if (ityp == BETWEEN && ((*frontIter)[0] > endPoint[0] || ((*frontIter)[0] == endPoint[0] &&
                                                                              (*backIter)[0] > endPoint[1]))) {
                 isEndVal = true;
             } else {
                 setValue();
             }
             return *this;
         }
template<typename TupleType> const TupleType* souffle::BinaryRelation< TupleType >::iterator::operator-> () const inline
Definition at line 355 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::value.
{
             return &value;
         }
template<typename TupleType> iterator& souffle::BinaryRelation< TupleType >::iterator::operator= (const iterator & other) default
template<typename TupleType> bool souffle::BinaryRelation< TupleType >::iterator::operator== (const iterator & other) const inline
Definition at line 340 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::br, souffle::BinaryRelation< TupleType >::iterator::isEndVal, and souffle::BinaryRelation< TupleType >::iterator::value.
{
             // return true if we're both end tombstones and of the same br
             if (isEndVal && other.isEndVal) return br == other.br;
             return isEndVal == other.isEndVal && value == other.value;
         }
template<typename TupleType> void souffle::BinaryRelation< TupleType >::iterator::setValue () inline private
yield the current iterator value to update to what the iterator is currently pointing at
Definition at line 471 of file BinaryRelation.h.
References souffle::BinaryRelation< TupleType >::iterator::isEndVal, and souffle::BinaryRelation< TupleType >::iterator::value.
Referenced by souffle::BinaryRelation< TupleType >::iterator::iterator(), and souffle::BinaryRelation< TupleType >::iterator::operator++().
{
             if (!isEndVal) {
                 TupleType tmp;
                 tmp[0] = (*frontIter)[0];
                 tmp[1] = (*backIter)[0];
                 value = tmp;
             }
         }
Field Documentation
template<typename TupleType> souffle::Trie<1>::iterator souffle::BinaryRelation< TupleType >::iterator::backIter private
Definition at line 238 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< TupleType >::iterator::advanceFrontIter(), souffle::BinaryRelation< TupleType >::iterator::ffIterators(), souffle::BinaryRelation< TupleType >::iterator::initCheckEnd(), souffle::BinaryRelation< TupleType >::iterator::initIterator(), souffle::BinaryRelation< TupleType >::iterator::initIterators(), and souffle::BinaryRelation< TupleType >::iterator::operator++().
template<typename TupleType> const BinaryRelation* souffle::BinaryRelation< TupleType >::iterator::br = nullptr private
Definition at line 227 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< TupleType >::iterator::initIterators(), and souffle::BinaryRelation< TupleType >::iterator::operator==().
template<typename TupleType> std::shared_ptr<souffle::Trie<1> > souffle::BinaryRelation< TupleType >::iterator::cTrie private
Definition at line 239 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< TupleType >::iterator::advanceFrontIter(), souffle::BinaryRelation< TupleType >::iterator::ffIterators(), souffle::BinaryRelation< TupleType >::iterator::initCheckEnd(), souffle::BinaryRelation< TupleType >::iterator::initIterator(), souffle::BinaryRelation< TupleType >::iterator::initIterators(), souffle::BinaryRelation< TupleType >::iterator::isTrieEnd(), and souffle::BinaryRelation< TupleType >::iterator::operator++().
template<typename TupleType> std::unordered_map<std::shared_ptr<souffle::Trie<1> >, souffle::Trie<1>::iterator> souffle::BinaryRelation< TupleType >::iterator::cTrieEnds private
Definition at line 241 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< TupleType >::iterator::initIterators(), and souffle::BinaryRelation< TupleType >::iterator::isTrieEnd().
template<typename TupleType> TupleType souffle::BinaryRelation< TupleType >::iterator::endPoint private
Definition at line 244 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< TupleType >::iterator::operator++().
template<typename TupleType> souffle::Trie<1>::iterator souffle::BinaryRelation< TupleType >::iterator::frontIter private
Definition at line 237 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< TupleType >::iterator::advanceFrontIter(), souffle::BinaryRelation< TupleType >::iterator::ffIterators(), souffle::BinaryRelation< TupleType >::iterator::initCheckEnd(), souffle::BinaryRelation< TupleType >::iterator::initIterator(), souffle::BinaryRelation< TupleType >::iterator::initIterators(), souffle::BinaryRelation< TupleType >::iterator::iterator(), and souffle::BinaryRelation< TupleType >::iterator::operator++().
template<typename TupleType> std::list<DomainInt> souffle::BinaryRelation< TupleType >::iterator::fronts private
Definition at line 249 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< TupleType >::iterator::advanceFrontIter().
template<typename TupleType> bool souffle::BinaryRelation< TupleType >::iterator::isEndVal = false private
Definition at line 224 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< TupleType >::iterator::advanceFrontIter(), souffle::BinaryRelation< TupleType >::iterator::initCheckEnd(), souffle::BinaryRelation< TupleType >::iterator::iterator(), souffle::BinaryRelation< TupleType >::iterator::operator++(), souffle::BinaryRelation< TupleType >::iterator::operator==(), and souffle::BinaryRelation< TupleType >::iterator::setValue().
template<typename TupleType> std::list<std::pair<std::shared_ptr<souffle::Trie<1> >, souffle::Trie<1>::iterator> > souffle::BinaryRelation< TupleType >::iterator::iterList private
Definition at line 235 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< TupleType >::iterator::advanceFrontIter(), souffle::BinaryRelation< TupleType >::iterator::ffIterators(), and souffle::BinaryRelation< TupleType >::iterator::initIterators().
template<typename TupleType> IterType souffle::BinaryRelation< TupleType >::iterator::ityp private
Definition at line 231 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< TupleType >::iterator::advanceFrontIter(), souffle::BinaryRelation< TupleType >::iterator::iterator(), and souffle::BinaryRelation< TupleType >::iterator::operator++().
template<typename TupleType> DomainInt souffle::BinaryRelation< TupleType >::iterator::rep private
Definition at line 247 of file BinaryRelation.h.
template<typename TupleType> TupleType souffle::BinaryRelation< TupleType >::iterator::value private
Definition at line 226 of file BinaryRelation.h.
Referenced by souffle::BinaryRelation< TupleType >::iterator::operator*(), souffle::BinaryRelation< TupleType >::iterator::operator->(), souffle::BinaryRelation< TupleType >::iterator::operator==(), and souffle::BinaryRelation< TupleType >::iterator::setValue().
The documentation for this class was generated from the following file:
BinaryRelation.h