souffle: souffle::RamBinaryRelation Class Reference
souffle::RamBinaryRelation Class Reference
Binary constraint.
#include <RamCondition.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply.
RamBinaryRelation * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getLevel () override
Get level.
RamValue * getLHS () const
Get left-hand side.
BinaryConstraintOp getOperator () const
Get operator symbol.
RamValue * getRHS () const
Get right-hand side.
void print (std::ostream &os) const override
Print.
RamBinaryRelation (BinaryConstraintOp op, std::unique_ptr< RamValue > l, std::unique_ptr< RamValue > r)
void setLHS (std::unique_ptr< RamValue > l)
Set left-hand side.
void setRHS (std::unique_ptr< RamValue > r)
Set right-hand side.
std::unique_ptr< RamValue > takeLHS ()
Take left-hand side.
std::unique_ptr< RamValue > takeRHS ()
Take right-hand side.
Public Member Functions inherited from souffle::RamCondition
RamCondition (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::unique_ptr< RamValue > lhs
Left-hand side of constraint.
BinaryConstraintOp op
Operator.
std::unique_ptr< RamValue > rhs
Right-hand side of constraint.
Detailed Description
Binary constraint.
Definition at line 119 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamBinaryRelation::RamBinaryRelation (BinaryConstraintOp op, std::unique_ptr< RamValue > l, std::unique_ptr< RamValue > r) inline
Definition at line 131 of file RamCondition.h.
Referenced by clone().
             : RamCondition(RN_BinaryRelation), op(op), lhs(std::move(l)), rhs(std::move(r)) {}
Member Function Documentation
void souffle::RamBinaryRelation::apply (const RamNodeMapper & map) inline override virtual
Apply.
Implements souffle::RamNode.
Definition at line 192 of file RamCondition.h.
References lhs, map, and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
RamBinaryRelation* souffle::RamBinaryRelation::clone () const inline override virtual
Create clone.
Implements souffle::RamCondition.
Definition at line 185 of file RamCondition.h.
References lhs, op, RamBinaryRelation(), and rhs.
{
         RamBinaryRelation* res = new RamBinaryRelation(
                 op, std::unique_ptr<RamValue>(lhs->clone()), std::unique_ptr<RamValue>(rhs->clone()));
         return res;
     }
bool souffle::RamBinaryRelation::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 199 of file RamCondition.h.
References getLHS(), getOperator(), and getRHS().
{
         assert(nullptr != dynamic_cast<const RamBinaryRelation*>(&node));
         const auto& other = static_cast<const RamBinaryRelation&>(node);
         return getOperator() == other.getOperator() && getLHS() == other.getLHS() &&
                getRHS() == other.getRHS();
     }
std::vector<const RamNode*> souffle::RamBinaryRelation::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 180 of file RamCondition.h.
References lhs, and rhs.
{
         return {lhs.get(), rhs.get()};
     }
size_t souffle::RamBinaryRelation::getLevel () inline override virtual
Get level.
Implements souffle::RamCondition.
Definition at line 142 of file RamCondition.h.
References lhs, and rhs.
{
         return std::max(lhs->getLevel(), rhs->getLevel());
     }
RamValue* souffle::RamBinaryRelation::getLHS () const inline
Get left-hand side.
Definition at line 147 of file RamCondition.h.
References lhs.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalCond().
{
         return lhs.get();
     }
BinaryConstraintOp souffle::RamBinaryRelation::getOperator () const inline
Get operator symbol.
Definition at line 175 of file RamCondition.h.
References op.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalCond().
{
         return op;
     }
RamValue* souffle::RamBinaryRelation::getRHS () const inline
Get right-hand side.
Definition at line 151 of file RamCondition.h.
References rhs.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalCond().
{
         return rhs.get();
     }
void souffle::RamBinaryRelation::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 135 of file RamCondition.h.
References lhs, op, rhs, and souffle::toBinaryConstraintSymbol().
{
         lhs->print(os);
         os << " " << toBinaryConstraintSymbol(op) << " ";
         rhs->print(os);
     }
void souffle::RamBinaryRelation::setLHS (std::unique_ptr< RamValue > l) inline
Set left-hand side.
Definition at line 166 of file RamCondition.h.
References lhs.
{
         lhs.swap(l);
     }
void souffle::RamBinaryRelation::setRHS (std::unique_ptr< RamValue > r) inline
Set right-hand side.
Definition at line 170 of file RamCondition.h.
References rhs.
{
         rhs.swap(r);
     }
std::unique_ptr<RamValue> souffle::RamBinaryRelation::takeLHS () inline
Take left-hand side.
Definition at line 156 of file RamCondition.h.
References lhs.
{
         return std::move(lhs);
     }
std::unique_ptr<RamValue> souffle::RamBinaryRelation::takeRHS () inline
Take right-hand side.
Definition at line 161 of file RamCondition.h.
References rhs.
{
         return std::move(rhs);
     }
Field Documentation
std::unique_ptr<RamValue> souffle::RamBinaryRelation::lhs private
Left-hand side of constraint.
Definition at line 125 of file RamCondition.h.
Referenced by apply(), clone(), getChildNodes(), getLevel(), getLHS(), print(), setLHS(), and takeLHS().
BinaryConstraintOp souffle::RamBinaryRelation::op private
Operator.
Definition at line 122 of file RamCondition.h.
Referenced by clone(), getOperator(), and print().
std::unique_ptr<RamValue> souffle::RamBinaryRelation::rhs private
Right-hand side of constraint.
Definition at line 128 of file RamCondition.h.
Referenced by apply(), clone(), getChildNodes(), getLevel(), getRHS(), print(), setRHS(), and takeRHS().
The documentation for this class was generated from the following file:
RamCondition.h