souffle: souffle::RamRelationRef Class Reference
souffle::RamRelationRef Class Reference
A RAM Relation in the RAM intermediate representation.
#include <RamRelation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamRelationRef * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const std::string & getName () const
Get name.
void print (std::ostream &out) const override
Print RAM node.
RamRelationRef (std::string n)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::string name
Name of relation.
Detailed Description
A RAM Relation in the RAM intermediate representation.
TODO: Make RamRelation a sub-class of RAM node. TODO: Tidy-up interface and attributes
Definition at line 216 of file RamRelation.h.
Constructor & Destructor Documentation
souffle::RamRelationRef::RamRelationRef (std::string n) inline
Definition at line 222 of file RamRelation.h.
Referenced by clone().
 : RamNode(RN_RelationRef), name(std::move(n)) {}
Member Function Documentation
void souffle::RamRelationRef::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 246 of file RamRelation.h.
 {}
RamRelationRef* souffle::RamRelationRef::clone () const inline override virtual
Create clone.
Implements souffle::RamNode.
Definition at line 240 of file RamRelation.h.
References getName(), and RamRelationRef().
{
         RamRelationRef* res = new RamRelationRef(getName());
         return res;
     }
bool souffle::RamRelationRef::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 250 of file RamRelation.h.
References getName().
{
         assert(nullptr != dynamic_cast<const RamRelation*>(&node));
         const auto& other = static_cast<const RamRelation&>(node);
         return getName() == other.getName();
     }
std::vector<const RamNode*> souffle::RamRelationRef::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 235 of file RamRelation.h.
{
         return std::vector<const RamNode*>();  // no child nodes
     }
const std::string& souffle::RamRelationRef::getName () const inline
Get name.
Definition at line 225 of file RamRelation.h.
References name.
Referenced by clone(), and equal().
{
         return name;
     }
void souffle::RamRelationRef::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 230 of file RamRelation.h.
References name.
{
         out << name;
     }
Field Documentation
std::string souffle::RamRelationRef::name protected
Name of relation.
Definition at line 219 of file RamRelation.h.
Referenced by getName(), and print().
The documentation for this class was generated from the following file:
RamRelation.h