souffle: souffle::SparseDisjointSet< SparseDomain > Class Template Reference
souffle::SparseDisjointSet< SparseDomain > Class Template Reference
#include <UnionFind.h>
Data Structures
class iterator
iterator for the class - is assumed not to be thread safe (as modifications to the underlying class will invalidate anyway)
Public Member Functions
iterator begin (const SparseDomain rep)
iterator beginReps ()
void clear ()
bool contains (SparseDomain v1, SparseDomain v2)
iterator end (const SparseDomain rep)
iterator endReps ()
SparseDomain findNode (SparseDomain x)
void makeNode (SparseDomain val)
bool nodeExists (const SparseDomain val) const
SparseDisjointSet & operator= (const SparseDisjointSet &old)
SparseDomain readOnlyFindNode (SparseDomain x)
bool sameSet (SparseDomain x, SparseDomain y)
std::size_t size ()
std::size_t sizeOfRepresentativeSet (SparseDomain in)
Gets the number of the items in the underlying dense set (mapping from sparse->dense)
const SparseDomain toSparse (const parent_t in) const
For the given dense value, return the associated sparse value.
void unionNodes (SparseDomain x, SparseDomain y)
Private Member Functions
parent_t toDense (const SparseDomain in)
Retrieve dense encoding, adding it in if non-existent.
Private Attributes
std::vector< SparseDomain > denseToSparseMap
DisjointSet ds
souffle::shared_mutex mapsLock
std::unordered_map
< SparseDomain, parent_t > sparseToDenseMap
Detailed Description
template<typename SparseDomain>
class souffle::SparseDisjointSet< SparseDomain >
Definition at line 452 of file UnionFind.h.
Member Function Documentation
template<typename SparseDomain> iterator souffle::SparseDisjointSet< SparseDomain >::begin (const SparseDomain rep) inline
Definition at line 576 of file UnionFind.h.
Referenced by souffle::BinaryRelation< tuple_type >::extend(), souffle::BinaryRelation< tuple_type >::generateTrieIfNone(), souffle::BinaryRelation< tuple_type >::insertAll(), and souffle::BinaryRelation< tuple_type >::partition().
{
         return iterator(this, rep);
     };
template<typename SparseDomain> iterator souffle::SparseDisjointSet< SparseDomain >::beginReps () inline
Definition at line 583 of file UnionFind.h.
Referenced by souffle::BinaryRelation< tuple_type >::begin(), souffle::BinaryRelation< tuple_type >::extend(), souffle::BinaryRelation< tuple_type >::find(), souffle::BinaryRelation< tuple_type >::findBetween(), souffle::BinaryRelation< tuple_type >::insertAll(), souffle::BinaryRelation< tuple_type >::partition(), and souffle::BinaryRelation< tuple_type >::size().
{
         return iterator(this, true);
     };
template<typename SparseDomain> void souffle::SparseDisjointSet< SparseDomain >::clear () inline
Definition at line 625 of file UnionFind.h.
Referenced by souffle::BinaryRelation< tuple_type >::clear().
                  {
         // we should clear this first, as we want to reduce how many locks are blocking at one given moment
         ds.clear();
         mapsLock.lock();
         sparseToDenseMap.clear();
         denseToSparseMap.clear();
         mapsLock.unlock();
     }
template<typename SparseDomain> bool souffle::SparseDisjointSet< SparseDomain >::contains (SparseDomain v1, SparseDomain v2) inline
Definition at line 659 of file UnionFind.h.
Referenced by souffle::BinaryRelation< tuple_type >::contains(), and souffle::BinaryRelation< tuple_type >::getBoundaries().
{
         if (nodeExists(v1) && nodeExists(v2)) {
             return sameSet(v1, v2);
         }
         return false;
     }
template<typename SparseDomain> iterator souffle::SparseDisjointSet< SparseDomain >::end (const SparseDomain rep) inline
Definition at line 579 of file UnionFind.h.
Referenced by souffle::BinaryRelation< tuple_type >::extend(), souffle::BinaryRelation< tuple_type >::generateTrieIfNone(), souffle::BinaryRelation< tuple_type >::insertAll(), and souffle::BinaryRelation< tuple_type >::partition().
{
         return iterator(this, rep, true);
     };
template<typename SparseDomain> iterator souffle::SparseDisjointSet< SparseDomain >::endReps () inline
Definition at line 586 of file UnionFind.h.
Referenced by souffle::BinaryRelation< tuple_type >::begin(), souffle::BinaryRelation< tuple_type >::extend(), souffle::BinaryRelation< tuple_type >::find(), souffle::BinaryRelation< tuple_type >::findBetween(), souffle::BinaryRelation< tuple_type >::insertAll(), souffle::BinaryRelation< tuple_type >::partition(), and souffle::BinaryRelation< tuple_type >::size().
{
         return iterator(this, true, true);
     };
template<typename SparseDomain> SparseDomain souffle::SparseDisjointSet< SparseDomain >::findNode (SparseDomain x) inline
Definition at line 612 of file UnionFind.h.
{
         return toSparse(ds.findNode(toDense(x)));
     };
template<typename SparseDomain> void souffle::SparseDisjointSet< SparseDomain >::makeNode (SparseDomain val) inline
Definition at line 646 of file UnionFind.h.
{
         toDense(val);
     };
template<typename SparseDomain> bool souffle::SparseDisjointSet< SparseDomain >::nodeExists (const SparseDomain val) const inline
Definition at line 651 of file UnionFind.h.
Referenced by souffle::SparseDisjointSet< DomainInt >::contains(), souffle::BinaryRelation< tuple_type >::containsElement(), souffle::BinaryRelation< tuple_type >::generateTrieIfNone(), souffle::BinaryRelation< tuple_type >::getBoundaries(), and souffle::BinaryRelation< TupleType >::iterator::iterator().
{
         mapsLock.lock_shared();
         bool result = sparseToDenseMap.find(val) != sparseToDenseMap.end();
         mapsLock.unlock_shared();
         return result;
     };
template<typename SparseDomain> SparseDisjointSet& souffle::SparseDisjointSet< SparseDomain >::operator= (const SparseDisjointSet< SparseDomain > & old) inline
Definition at line 510 of file UnionFind.h.
{
         if (&old == this) return *this;
         ds = old.ds;
         sparseToDenseMap = old.sparseToDenseMap;
         denseToSparseMap = old.denseToSparseMap;
         return *this;
     }
template<typename SparseDomain> SparseDomain souffle::SparseDisjointSet< SparseDomain >::readOnlyFindNode (SparseDomain x) inline
Definition at line 608 of file UnionFind.h.
Referenced by souffle::BinaryRelation< tuple_type >::extend(), souffle::BinaryRelation< tuple_type >::frontProduct(), souffle::BinaryRelation< tuple_type >::generateTrieIfNone(), and souffle::BinaryRelation< tuple_type >::insert().
{
         return toSparse(ds.readOnlyFindNode(toDense(x)));
     };
template<typename SparseDomain> bool souffle::SparseDisjointSet< SparseDomain >::sameSet (SparseDomain x, SparseDomain y) inline
Definition at line 604 of file UnionFind.h.
Referenced by souffle::SparseDisjointSet< DomainInt >::contains().
{
         return ds.sameSet(toDense(x), toDense(y));
     };
template<typename SparseDomain> std::size_t souffle::SparseDisjointSet< SparseDomain >::size () inline
Definition at line 620 of file UnionFind.h.
{
         return ds.size();
     };
template<typename SparseDomain> std::size_t souffle::SparseDisjointSet< SparseDomain >::sizeOfRepresentativeSet (SparseDomain in) inline
Gets the number of the items in the underlying dense set (mapping from sparse->dense)
Parameters
in the node which we count the size of it's representative map
Returns
the size of the disjoint set
Definition at line 640 of file UnionFind.h.
Referenced by souffle::BinaryRelation< tuple_type >::partition(), and souffle::BinaryRelation< tuple_type >::size().
{
         parent_t inD = toDense(in);
         return ds.numInSet(ds.readOnlyFindNode(inD));
     }
template<typename SparseDomain> parent_t souffle::SparseDisjointSet< SparseDomain >::toDense (const SparseDomain in) inline private
Retrieve dense encoding, adding it in if non-existent.
Parameters
in the sparse value
Returns
the corresponding dense value
Definition at line 470 of file UnionFind.h.
Referenced by souffle::SparseDisjointSet< DomainInt >::findNode(), souffle::SparseDisjointSet< DomainInt >::makeNode(), souffle::SparseDisjointSet< DomainInt >::readOnlyFindNode(), souffle::SparseDisjointSet< DomainInt >::sameSet(), souffle::SparseDisjointSet< DomainInt >::sizeOfRepresentativeSet(), and souffle::SparseDisjointSet< DomainInt >::unionNodes().
{
         mapsLock.lock_shared();
         auto it = sparseToDenseMap.find(in);
         // use the pre-existing value
         if (it != sparseToDenseMap.end()) {
             auto ret = it->second;
             mapsLock.unlock_shared();
             return ret;
         }
         mapsLock.unlock_shared();
         // create node in conversion
         mapsLock.lock();
         it = sparseToDenseMap.find(in);
         // use the pre-existing value (as perhaps, it may have been written twice)
         if (it != sparseToDenseMap.end()) {
             auto ret = it->second;
             mapsLock.unlock();
             return ret;
         }
         size_t j = denseToSparseMap.size();
         // check if we create a dense value outside of the bounds that can be stored
         if (j > std::numeric_limits<parent_t>::max()) throw std::runtime_error("out of bounds dense value");
         auto jClipped = static_cast<parent_t>(j);
         // we create the node
         ds.makeNode();
         denseToSparseMap.push_back(in);
         sparseToDenseMap[in] = jClipped;
         mapsLock.unlock();
         return jClipped;
     }
template<typename SparseDomain> const SparseDomain souffle::SparseDisjointSet< SparseDomain >::toSparse (const parent_t in) const inline
For the given dense value, return the associated sparse value.
Parameters
in the supplied dense value
Returns
the sparse value from the denseToSparseMap
Definition at line 595 of file UnionFind.h.
Referenced by souffle::SparseDisjointSet< DomainInt >::findNode(), souffle::SparseDisjointSet< DomainInt >::readOnlyFindNode(), and souffle::SparseDisjointSet< SparseDomain >::iterator::yield().
{
         mapsLock.lock_shared();
         auto ret = denseToSparseMap.at(in);
         mapsLock.unlock_shared();
         return ret;
     };
template<typename SparseDomain> void souffle::SparseDisjointSet< SparseDomain >::unionNodes (SparseDomain x, SparseDomain y) inline
Definition at line 616 of file UnionFind.h.
Referenced by souffle::BinaryRelation< tuple_type >::insert().
{
         ds.unionNodes(toDense(x), toDense(y));
     };
Field Documentation
template<typename SparseDomain> std::vector<SparseDomain> souffle::SparseDisjointSet< SparseDomain >::denseToSparseMap private
Definition at line 462 of file UnionFind.h.
Referenced by souffle::SparseDisjointSet< DomainInt >::clear(), souffle::SparseDisjointSet< DomainInt >::operator=(), souffle::SparseDisjointSet< DomainInt >::toDense(), and souffle::SparseDisjointSet< DomainInt >::toSparse().
template<typename SparseDomain> DisjointSet souffle::SparseDisjointSet< SparseDomain >::ds private
Definition at line 458 of file UnionFind.h.
Referenced by souffle::SparseDisjointSet< DomainInt >::clear(), souffle::SparseDisjointSet< DomainInt >::findNode(), souffle::SparseDisjointSet< DomainInt >::operator=(), souffle::SparseDisjointSet< DomainInt >::readOnlyFindNode(), souffle::SparseDisjointSet< DomainInt >::sameSet(), souffle::SparseDisjointSet< DomainInt >::size(), souffle::SparseDisjointSet< DomainInt >::sizeOfRepresentativeSet(), souffle::SparseDisjointSet< DomainInt >::toDense(), and souffle::SparseDisjointSet< DomainInt >::unionNodes().
template<typename SparseDomain> souffle::shared_mutex souffle::SparseDisjointSet< SparseDomain >::mapsLock mutable private
Definition at line 456 of file UnionFind.h.
Referenced by souffle::SparseDisjointSet< DomainInt >::clear(), souffle::SparseDisjointSet< DomainInt >::nodeExists(), souffle::SparseDisjointSet< DomainInt >::toDense(), and souffle::SparseDisjointSet< DomainInt >::toSparse().
template<typename SparseDomain> std::unordered_map<SparseDomain, parent_t> souffle::SparseDisjointSet< SparseDomain >::sparseToDenseMap private
Definition at line 461 of file UnionFind.h.
Referenced by souffle::SparseDisjointSet< DomainInt >::clear(), souffle::SparseDisjointSet< DomainInt >::nodeExists(), souffle::SparseDisjointSet< DomainInt >::operator=(), and souffle::SparseDisjointSet< DomainInt >::toDense().
The documentation for this class was generated from the following file:
UnionFind.h