souffle: souffle::RamProject Class Reference
souffle::RamProject Class Reference
Projection.
#include <RamOperation.h>
Public Member Functions
void addArg (std::unique_ptr< RamValue > v)
Add value for a column.
void addCondition (std::unique_ptr< RamCondition > c, const RamOperation &root) override
Add condition to project, needed for different level check.
void apply (const RamNodeMapper &map) override
Apply mapper.
RamProject * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getDepth () const override
Get depth.
const RamRelation & getFilter () const
Get filter.
const RamRelation & getRelation () const
Get relation.
std::vector< RamValue * > getValues () const
Get values.
bool hasFilter () const
Check filter.
void print (std::ostream &os, int tabpos) const override
Print.
RamProject (std::unique_ptr< RamRelation > rel, size_t level)
RamProject (std::unique_ptr< RamRelation > rel, const RamRelation &filter, size_t level)
Public Member Functions inherited from souffle::RamOperation
void addCondition (std::unique_ptr< RamCondition > c)
Add condition.
RamCondition * getCondition () const
Get condition.
size_t getLevel () const
Get level.
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type, size_t l)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamRelation > filter
Relation to check whether does not exist.
std::unique_ptr< RamRelation > relation
Relation.
std::vector< std::unique_ptr
< RamValue > > values
Protected Attributes inherited from souffle::RamOperation
std::unique_ptr< RamCondition > condition
condition that is checked for each obtained tuple
size_t level
the nesting level of this operation
Detailed Description
Projection.
Definition at line 441 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamProject::RamProject (std::unique_ptr< RamRelation > rel, size_t level) inline
Definition at line 454 of file RamOperation.h.
Referenced by clone().
             : RamOperation(RN_Project, level), relation(std::move(rel)), filter(nullptr) {}
souffle::RamProject::RamProject (std::unique_ptr< RamRelation > rel, const RamRelation & filter, size_t level) inline
Definition at line 457 of file RamOperation.h.
             : RamOperation(RN_Project, level), relation(std::move(rel)),
               filter(std::make_unique<RamRelation>(filter)) {}
Member Function Documentation
void souffle::RamProject::addArg (std::unique_ptr< RamValue > v) inline
Add value for a column.
Definition at line 462 of file RamOperation.h.
References values.
{
         values.push_back(std::move(v));
     }
void souffle::RamProject::addCondition (std::unique_ptr< RamCondition > c, const RamOperation & root) override virtual
Add condition to project, needed for different level check.
Reimplemented from souffle::RamOperation.
Definition at line 270 of file RamOperation.cpp.
References souffle::RamOperation::condition, and souffle::RamOperation::level.
{
     // we can have condition arguments from lower levels, since the values we project are also from lower
     // levels
     assert(c->getLevel() <= level);
     if (condition) {
         condition = std::make_unique<RamAnd>(std::move(condition), std::move(c));
     } else {
         condition.swap(c);
     }
 }
void souffle::RamProject::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Reimplemented from souffle::RamOperation.
Definition at line 521 of file RamOperation.h.
References souffle::RamOperation::apply(), map, relation, and values.
{
         RamOperation::apply(map);
         relation = map(std::move(relation));
         for (auto& cur : values) {
             cur = map(std::move(cur));
         }
     }
RamProject* souffle::RamProject::clone () const inline override virtual
Create clone.
Implements souffle::RamOperation.
Definition at line 509 of file RamOperation.h.
References filter, souffle::RamOperation::level, RamProject(), relation, and values.
{
         RamProject* res = new RamProject(std::unique_ptr<RamRelation>(relation->clone()), level);
         if (filter != nullptr) {
             res->filter = std::make_unique<RamRelation>(*filter);
         }
         for (auto& cur : values) {
             res->values.push_back(std::unique_ptr<RamValue>(cur->clone()));
         }
         return res;
     }
bool souffle::RamProject::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamOperation.
Definition at line 531 of file RamOperation.h.
References souffle::RamOperation::equal(), souffle::equal_targets(), filter, getRelation(), and values.
{
         assert(nullptr != dynamic_cast<const RamProject*>(&node));
         const auto& other = static_cast<const RamProject&>(node);
         bool isFilterEqual = false;
         if (filter == nullptr && other.filter == nullptr) {
             isFilterEqual = true;
         } else if (filter != nullptr && other.filter != nullptr) {
             isFilterEqual = (*filter == *other.filter);
         }
         return RamOperation::equal(other) && getRelation() == other.getRelation() &&
                equal_targets(values, other.values) && isFilterEqual;
     }
std::vector<const RamNode*> souffle::RamProject::getChildNodes () const inline override virtual
Obtain list of child nodes.
Reimplemented from souffle::RamOperation.
Definition at line 499 of file RamOperation.h.
References souffle::RamOperation::getChildNodes(), relation, and values.
{
         auto res = RamOperation::getChildNodes();
         res.push_back(relation.get());
         for (const auto& cur : values) {
             res.push_back(cur.get());
         }
         return res;
     }
size_t souffle::RamProject::getDepth () const inline override virtual
Get depth.
Implements souffle::RamOperation.
Definition at line 491 of file RamOperation.h.
{
         return 1;
     }
const RamRelation& souffle::RamProject::getFilter () const inline
Get filter.
Definition at line 480 of file RamOperation.h.
References filter, and hasFilter().
Referenced by souffle::Synthesiser::emitCode().
{
         assert(hasFilter());
         return *filter;
     }
const RamRelation& souffle::RamProject::getRelation () const inline
Get relation.
Definition at line 470 of file RamOperation.h.
References relation.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalOp().
{
         return *relation;
     }
std::vector<RamValue*> souffle::RamProject::getValues () const inline
Get values.
Definition at line 486 of file RamOperation.h.
References souffle::toPtrVector(), and values.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalOp().
{
         return toPtrVector(values);
     }
bool souffle::RamProject::hasFilter () const inline
Check filter.
Definition at line 475 of file RamOperation.h.
References filter.
Referenced by souffle::Synthesiser::emitCode(), and getFilter().
{
         return (bool)filter;
     }
void souffle::RamProject::print (std::ostream & os, int tabpos) const override virtual
Print.
Implements souffle::RamOperation.
Definition at line 256 of file RamOperation.cpp.
References souffle::RamOperation::condition, souffle::RamOperation::getCondition(), souffle::join(), relation, and values.
{
     const std::string tabs(tabpos, '\t');
     os << tabs << "PROJECT (" << join(values, ", ", print_deref<std::unique_ptr<RamValue>>()) << ") INTO "
        << relation->getName();
     // support table-less options
     if (auto condition = getCondition()) {
         os << " IF ";
         condition->print(os);
     }
 }
Field Documentation
std::unique_ptr<RamRelation> souffle::RamProject::filter protected
Relation to check whether does not exist.
Definition at line 448 of file RamOperation.h.
Referenced by clone(), equal(), getFilter(), and hasFilter().
std::unique_ptr<RamRelation> souffle::RamProject::relation protected
Relation.
Definition at line 444 of file RamOperation.h.
Referenced by apply(), clone(), getChildNodes(), getRelation(), and print().
std::vector<std::unique_ptr<RamValue> > souffle::RamProject::values protected
Definition at line 451 of file RamOperation.h.
Referenced by addArg(), apply(), clone(), equal(), getChildNodes(), getValues(), and print().
The documentation for this class was generated from the following files:
RamOperation.h
RamOperation.cpp