souffle: souffle::AstBinaryConstraint Class Reference
souffle::AstBinaryConstraint Class Reference
Subclass of Constraint that represents a binary constraint e.g., x = y.
#include <AstLiteral.h>
Public Member Functions
void apply (const AstNodeMapper &map) override
Mutates this node.
AstBinaryConstraint (BinaryConstraintOp o, std::unique_ptr< AstArgument > ls, std::unique_ptr< AstArgument > rs)
AstBinaryConstraint (const std::string &op, std::unique_ptr< AstArgument > ls, std::unique_ptr< AstArgument > rs)
AstBinaryConstraint * clone () const override
Creates a clone of this AST sub-structure.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
AstArgument * getLHS () const
Return LHS argument.
BinaryConstraintOp getOperator () const
Return binary operator.
AstArgument * getRHS () const
Return RHS argument.
const bool isNumerical () const
Check whether constraint is a numeric constraint.
const bool isSymbolic () const
Check whether constraint is a symbolic constraint.
void negate () override
Negates the constraint.
void print (std::ostream &os) const override
Output the constraint to a given stream.
void setOperator (BinaryConstraintOp op)
Update the binary operator.
~AstBinaryConstraint () override=default
Public Member Functions inherited from souffle::AstConstraint
const AstAtom * getAtom () const override
Obtains the atom referenced by this literal - if any.
~AstConstraint () override=default
Public Member Functions inherited from souffle::AstLiteral
AstLiteral ()=default
~AstLiteral () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
std::unique_ptr< AstArgument > lhs
Left-hand side argument of a binary operation.
BinaryConstraintOp operation
The operator in this relation.
std::unique_ptr< AstArgument > rhs
Right-hand side argument of a binary operation.
Detailed Description
Subclass of Constraint that represents a binary constraint e.g., x = y.
Definition at line 355 of file AstLiteral.h.
Constructor & Destructor Documentation
souffle::AstBinaryConstraint::AstBinaryConstraint (BinaryConstraintOp o, std::unique_ptr< AstArgument > ls, std::unique_ptr< AstArgument > rs) inline
Definition at line 367 of file AstLiteral.h.
Referenced by clone().
             : operation(o), lhs(std::move(ls)), rhs(std::move(rs)) {}
souffle::AstBinaryConstraint::AstBinaryConstraint (const std::string & op, std::unique_ptr< AstArgument > ls, std::unique_ptr< AstArgument > rs) inline
Definition at line 371 of file AstLiteral.h.
             : operation(toBinaryConstraintOp(op)), lhs(std::move(ls)), rhs(std::move(rs)) {}
souffle::AstBinaryConstraint::~AstBinaryConstraint () override default
Member Function Documentation
void souffle::AstBinaryConstraint::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 428 of file AstLiteral.h.
References lhs, map, and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
AstBinaryConstraint* souffle::AstBinaryConstraint::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstConstraint.
Definition at line 420 of file AstLiteral.h.
References AstBinaryConstraint(), souffle::AstNode::getSrcLoc(), lhs, operation, rhs, and souffle::AstNode::setSrcLoc().
{
         AstBinaryConstraint* res = new AstBinaryConstraint(operation,
                 std::unique_ptr<AstArgument>(lhs->clone()), std::unique_ptr<AstArgument>(rhs->clone()));
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstBinaryConstraint::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 440 of file AstLiteral.h.
References lhs, operation, and rhs.
{
         assert(nullptr != dynamic_cast<const AstBinaryConstraint*>(&node));
         const auto& other = static_cast<const AstBinaryConstraint&>(node);
         return operation == other.operation && *lhs == *other.lhs && *rhs == *other.rhs;
     }
std::vector<const AstNode*> souffle::AstBinaryConstraint::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 434 of file AstLiteral.h.
References lhs, and rhs.
{
         return {lhs.get(), rhs.get()};
     }
AstArgument* souffle::AstBinaryConstraint::getLHS () const inline
Return LHS argument.
Definition at line 378 of file AstLiteral.h.
References lhs.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), souffle::getConstTerms(), souffle::getGroundedTerms(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::BddBddBTranslator::visitBinaryConstraint(), and souffle::LogicbloxConverter::visitBinaryConstraint().
{
         return lhs.get();
     }
BinaryConstraintOp souffle::AstBinaryConstraint::getOperator () const inline
Return binary operator.
Definition at line 388 of file AstLiteral.h.
References operation.
Referenced by souffle::AstSemanticChecker::checkProgram(), souffle::getConstTerms(), souffle::getGroundedTerms(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::BddBddBTranslator::visitBinaryConstraint(), and souffle::LogicbloxConverter::visitBinaryConstraint().
{
         return operation;
     }
AstArgument* souffle::AstBinaryConstraint::getRHS () const inline
Return RHS argument.
Definition at line 383 of file AstLiteral.h.
References rhs.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), souffle::getConstTerms(), souffle::getGroundedTerms(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::BddBddBTranslator::visitBinaryConstraint(), and souffle::LogicbloxConverter::visitBinaryConstraint().
{
         return rhs.get();
     }
const bool souffle::AstBinaryConstraint::isNumerical () const inline
Check whether constraint is a numeric constraint.
Definition at line 403 of file AstLiteral.h.
References souffle::isNumericBinaryConstraintOp(), and operation.
Referenced by souffle::AstSemanticChecker::checkProgram().
{
         return isNumericBinaryConstraintOp(operation);
     }
const bool souffle::AstBinaryConstraint::isSymbolic () const inline
Check whether constraint is a symbolic constraint.
Definition at line 408 of file AstLiteral.h.
References souffle::isSymbolicBinaryConstraintOp(), and operation.
Referenced by souffle::AstSemanticChecker::checkProgram().
{
         return isSymbolicBinaryConstraintOp(operation);
     }
void souffle::AstBinaryConstraint::negate () inline override virtual
Negates the constraint.
Implements souffle::AstConstraint.
Definition at line 398 of file AstLiteral.h.
References souffle::negatedConstraintOp(), operation, and setOperator().
{
         setOperator(souffle::negatedConstraintOp(operation));
     }
void souffle::AstBinaryConstraint::print (std::ostream & os) const inline override virtual
Output the constraint to a given stream.
Implements souffle::AstNode.
Definition at line 413 of file AstLiteral.h.
References lhs, operation, rhs, and souffle::toBinaryConstraintSymbol().
{
         lhs->print(os);
         os << " " << toBinaryConstraintSymbol(operation) << " ";
         rhs->print(os);
     }
void souffle::AstBinaryConstraint::setOperator (BinaryConstraintOp op) inline
Update the binary operator.
Definition at line 393 of file AstLiteral.h.
References operation.
Referenced by negate().
{
         operation = op;
     }
Field Documentation
std::unique_ptr<AstArgument> souffle::AstBinaryConstraint::lhs protected
Left-hand side argument of a binary operation.
Definition at line 361 of file AstLiteral.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getLHS(), and print().
BinaryConstraintOp souffle::AstBinaryConstraint::operation protected
The operator in this relation.
Definition at line 358 of file AstLiteral.h.
Referenced by clone(), equal(), getOperator(), isNumerical(), isSymbolic(), negate(), print(), and setOperator().
std::unique_ptr<AstArgument> souffle::AstBinaryConstraint::rhs protected
Right-hand side argument of a binary operation.
Definition at line 364 of file AstLiteral.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getRHS(), and print().
The documentation for this class was generated from the following file:
AstLiteral.h