souffle: souffle::RamAnd Class Reference
souffle::RamAnd Class Reference
Conjunction.
#include <RamCondition.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply.
RamAnd * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtains list of child nodes.
size_t getLevel () override
Get level.
const RamCondition & getLHS () const
Get left-hand side of conjunction.
const RamCondition & getRHS () const
Get right-hand side of conjunction.
void print (std::ostream &os) const override
Print.
RamAnd (std::unique_ptr< RamCondition > l, std::unique_ptr< RamCondition > r)
Public Member Functions inherited from souffle::RamCondition
RamCondition (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamCondition > lhs
Left-hand side of conjunction.
std::unique_ptr< RamCondition > rhs
Right-hand side of conjunction.
Detailed Description
Conjunction.
Definition at line 52 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamAnd::RamAnd (std::unique_ptr< RamCondition > l, std::unique_ptr< RamCondition > r) inline
Definition at line 61 of file RamCondition.h.
Referenced by clone().
             : RamCondition(RN_And), lhs(std::move(l)), rhs(std::move(r)) {}
Member Function Documentation
void souffle::RamAnd::apply (const RamNodeMapper & map) inline override virtual
Apply.
Implements souffle::RamNode.
Definition at line 101 of file RamCondition.h.
References lhs, map, and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
RamAnd* souffle::RamAnd::clone () const inline override virtual
Create clone.
Implements souffle::RamCondition.
Definition at line 94 of file RamCondition.h.
References lhs, RamAnd(), and rhs.
{
         RamAnd* res = new RamAnd(
                 std::unique_ptr<RamCondition>(lhs->clone()), std::unique_ptr<RamCondition>(rhs->clone()));
         return res;
     }
bool souffle::RamAnd::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 108 of file RamCondition.h.
References getLHS(), and getRHS().
{
         assert(nullptr != dynamic_cast<const RamAnd*>(&node));
         const auto& other = static_cast<const RamAnd&>(node);
         return getLHS() == other.getLHS() && getRHS() == other.getRHS();
     }
std::vector<const RamNode*> souffle::RamAnd::getChildNodes () const inline override virtual
Obtains list of child nodes.
Implements souffle::RamNode.
Definition at line 89 of file RamCondition.h.
References lhs, and rhs.
{
         return {lhs.get(), rhs.get()};
     }
size_t souffle::RamAnd::getLevel () inline override virtual
Get level.
Implements souffle::RamCondition.
Definition at line 84 of file RamCondition.h.
References lhs, and rhs.
{
         return std::max(lhs->getLevel(), rhs->getLevel());
     }
const RamCondition& souffle::RamAnd::getLHS () const inline
Get left-hand side of conjunction.
Definition at line 65 of file RamCondition.h.
References lhs.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalCond().
{
         assert(lhs);
         return *lhs;
     }
const RamCondition& souffle::RamAnd::getRHS () const inline
Get right-hand side of conjunction.
Definition at line 71 of file RamCondition.h.
References rhs.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalCond().
{
         assert(rhs);
         return *rhs;
     }
void souffle::RamAnd::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 77 of file RamCondition.h.
References lhs, and rhs.
{
         lhs->print(os);
         os << " and ";
         rhs->print(os);
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamAnd::lhs protected
Left-hand side of conjunction.
Definition at line 55 of file RamCondition.h.
Referenced by apply(), clone(), getChildNodes(), getLevel(), getLHS(), and print().
std::unique_ptr<RamCondition> souffle::RamAnd::rhs protected
Right-hand side of conjunction.
Definition at line 58 of file RamCondition.h.
Referenced by apply(), clone(), getChildNodes(), getLevel(), getRHS(), and print().
The documentation for this class was generated from the following file:
RamCondition.h