souffle: souffle::RamReturn Class Reference
souffle::RamReturn Class Reference
A statement for returning from a ram subroutine.
#include <RamOperation.h>
Public Member Functions
void addValue (std::unique_ptr< RamValue > val)
void apply (const RamNodeMapper &map) override
Apply mapper.
RamReturn * clone () const override
Create clone.
size_t getDepth () const override
Get depth.
RamValue & getValue (size_t i) const
Get value.
std::vector< RamValue * > getValues () const
void print (std::ostream &out, int tabpos) const override
Print.
RamReturn (size_t level)
Public Member Functions inherited from souffle::RamOperation
virtual void addCondition (std::unique_ptr< RamCondition > c, const RamOperation &root)
Add condition.
void addCondition (std::unique_ptr< RamCondition > c)
Add condition.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
RamCondition * getCondition () const
Get condition.
size_t getLevel () const
Get level.
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type, size_t l)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::vector< std::unique_ptr
< RamValue > > values
Protected Attributes inherited from souffle::RamOperation
std::unique_ptr< RamCondition > condition
condition that is checked for each obtained tuple
size_t level
the nesting level of this operation
Detailed Description
A statement for returning from a ram subroutine.
Definition at line 546 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamReturn::RamReturn (size_t level) inline
Definition at line 551 of file RamOperation.h.
Referenced by clone().
 : RamOperation(RN_Return, level) {}
Member Function Documentation
void souffle::RamReturn::addValue (std::unique_ptr< RamValue > val) inline
Definition at line 559 of file RamOperation.h.
References values.
{
         values.push_back(std::move(val));
     }
void souffle::RamReturn::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Reimplemented from souffle::RamOperation.
Definition at line 583 of file RamOperation.h.
References souffle::RamOperation::apply(), map, and values.
{
         RamOperation::apply(map);
         for (auto& cur : values) {
             cur = map(std::move(cur));
         }
     }
RamReturn* souffle::RamReturn::clone () const inline override virtual
Create clone.
Implements souffle::RamOperation.
Definition at line 574 of file RamOperation.h.
References souffle::RamOperation::level, RamReturn(), and values.
{
         auto* res = new RamReturn(level);
         for (auto& cur : values) {
             res->values.push_back(std::unique_ptr<RamValue>(cur->clone()));
         }
         return res;
     }
bool souffle::RamReturn::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamOperation.
Definition at line 592 of file RamOperation.h.
References souffle::RamOperation::equal(), souffle::equal_targets(), and values.
{
         assert(nullptr != dynamic_cast<const RamReturn*>(&node));
         const auto& other = static_cast<const RamReturn&>(node);
         return RamOperation::equal(other) && equal_targets(values, other.values);
     }
size_t souffle::RamReturn::getDepth () const inline override virtual
Get depth.
Implements souffle::RamOperation.
Definition at line 555 of file RamOperation.h.
{
         return 1;
     }
RamValue& souffle::RamReturn::getValue (size_t i) const inline
Get value.
Definition at line 568 of file RamOperation.h.
References i, and values.
{
         assert(i < values.size() && "value index out of range");
         return *values[i];
     }
std::vector<RamValue*> souffle::RamReturn::getValues () const inline
Definition at line 563 of file RamOperation.h.
References souffle::toPtrVector(), and values.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalOp(), and print().
{
         return toPtrVector(values);
     }
void souffle::RamReturn::print (std::ostream & os, int tabpos) const override virtual
Print.
Implements souffle::RamOperation.
Definition at line 283 of file RamOperation.cpp.
References getValues().
{
     const std::string tabs(tabpos, '\t');
     // return
     os << tabs << "RETURN (";
     for (auto val : getValues()) {
         if (val == nullptr) {
             os << "_";
         } else {
             val->print(os);
         }
         if (val != *(getValues().end() - 1)) {
             os << ", ";
         }
     }
     os << ")";
 }
Field Documentation
std::vector<std::unique_ptr<RamValue> > souffle::RamReturn::values protected
Definition at line 548 of file RamOperation.h.
Referenced by addValue(), apply(), clone(), equal(), getValue(), and getValues().
The documentation for this class was generated from the following files:
RamOperation.h
RamOperation.cpp