souffle: souffle::InterpreterIndex Class Reference
souffle::InterpreterIndex Class Reference
#include <InterpreterIndex.h>
Data Structures
struct comparator
Public Types
using iterator = index_set::iterator
Public Member Functions
std::pair< iterator, iterator > equalRange (const RamDomain *value) const
return start and end iterator of an equal range
bool exists (const RamDomain *value)
check whether tuple exists in index
iterator indexEnd () const
void insert (const RamDomain *tuple)
add tuple to the index
template<class Iter >
void insert (const Iter &a, const Iter &b)
add tuples to the index via an iterator
InterpreterIndex (InterpreterIndexOrder order)
std::pair< iterator, iterator > lowerUpperBound (const RamDomain *low, const RamDomain *high) const
return start and end iterator of a range
const InterpreterIndexOrder & order () const
void print (std::ostream &out) const
enables the index to be printed
void purge ()
purge all hashes of index
Protected Types
using index_set = btree_multiset< const RamDomain *, comparator, std::allocator< const RamDomain * >, 512 >
Private Attributes
index_set set
const InterpreterIndexOrder theOrder
Detailed Description
Definition at line 136 of file InterpreterIndex.h.
Member Typedef Documentation
using souffle::InterpreterIndex::index_set = btree_multiset<const RamDomain*, comparator, std::allocator<const RamDomain*>, 512> protected
Definition at line 175 of file InterpreterIndex.h.
using souffle::InterpreterIndex::iterator = index_set::iterator
Definition at line 178 of file InterpreterIndex.h.
Constructor & Destructor Documentation
souffle::InterpreterIndex::InterpreterIndex (InterpreterIndexOrder order) inline
Definition at line 185 of file InterpreterIndex.h.
             : theOrder(std::move(order)), set(comparator(theOrder), comparator(theOrder)) {}
Member Function Documentation
std::pair<iterator, iterator> souffle::InterpreterIndex::equalRange (const RamDomain * value) const inline
return start and end iterator of an equal range
Definition at line 229 of file InterpreterIndex.h.
References lowerUpperBound().
{
         return lowerUpperBound(value, value);
     }
bool souffle::InterpreterIndex::exists (const RamDomain * value) inline
check whether tuple exists in index
Definition at line 212 of file InterpreterIndex.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::end(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::find(), and set.
Referenced by souffle::InterpreterRelation::exists().
{
         return set.find(value) != set.end();
     }
iterator souffle::InterpreterIndex::indexEnd () const inline
Definition at line 239 of file InterpreterIndex.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::end(), and set.
{
         return set.end();
     }
void souffle::InterpreterIndex::insert (const RamDomain * tuple) inline
add tuple to the index
precondition: tuple does not exist in the index
Definition at line 197 of file InterpreterIndex.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert(), and set.
{
         set.insert(tuple);
     }
template<class Iter > void souffle::InterpreterIndex::insert (const Iter & a, const Iter & b) inline
add tuples to the index via an iterator
precondition: the tuples do not exist in the index
Definition at line 207 of file InterpreterIndex.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert(), and set.
{
         set.insert(a, b);
     };
std::pair<iterator, iterator> souffle::InterpreterIndex::lowerUpperBound (const RamDomain * low, const RamDomain * high) const inline
return start and end iterator of a range
Definition at line 234 of file InterpreterIndex.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::lower_bound(), set, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::upper_bound().
Referenced by equalRange().
{
         return std::pair<iterator, iterator>(set.lower_bound(low), set.upper_bound(high));
     }
const InterpreterIndexOrder& souffle::InterpreterIndex::order () const inline
Definition at line 188 of file InterpreterIndex.h.
References theOrder.
Referenced by souffle::InterpreterRelation::getIndex().
{
         return theOrder;
     }
void souffle::InterpreterIndex::print (std::ostream & out) const inline
enables the index to be printed
Definition at line 222 of file InterpreterIndex.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::printStats(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::printTree(), and set.
{
         set.printStats(out);
         out << "\n";
         set.printTree(out);
     }
void souffle::InterpreterIndex::purge () inline
purge all hashes of index
Definition at line 217 of file InterpreterIndex.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::clear(), and set.
                  {
         set.clear();
     }
Field Documentation
index_set souffle::InterpreterIndex::set private
Definition at line 182 of file InterpreterIndex.h.
Referenced by exists(), indexEnd(), insert(), lowerUpperBound(), print(), and purge().
const InterpreterIndexOrder souffle::InterpreterIndex::theOrder private
Definition at line 181 of file InterpreterIndex.h.
Referenced by order().
The documentation for this class was generated from the following file:
InterpreterIndex.h