souffle: souffle::SynthesiserRbtsetRelation Class Reference
souffle::SynthesiserRbtsetRelation Class Reference
#include <SynthesiserRelation.h>
Public Member Functions
void computeIndices () override
Generate index set for a rbtset relation.
void generateTypeStruct (std::ostream &out) override
Generate type struct of a rbtset relation.
std::string getTypeName () override
Generate type name of a rbtset relation.
SynthesiserRbtsetRelation (const RamRelation &ramRel, const IndexSet &indexSet, bool isProvenance)
Public Member Functions inherited from souffle::SynthesiserRelation
size_t getArity () const
Get arity of relation.
const std::string & getDataStructure () const
Get data structure of relation.
const IndexSet & getIndexSet () const
Get stored IndexSet.
std::vector< std::vector< int > > getIndices () const
Get list of indices used for relation, guaranteed that original indices in IndexSet come before any generated indices.
const RamRelation & getRamRelation () const
Get stored RamRelation.
SynthesiserRelation (const RamRelation &rel, const IndexSet &indices, const bool isProvenance=false)
~SynthesiserRelation ()=default
Additional Inherited Members
Static Public Member Functions inherited from souffle::SynthesiserRelation
static std::unique_ptr
< SynthesiserRelation > getSynthesiserRelation (const RamRelation &ramRel, const IndexSet &indexSet, bool isProvenance)
Factory method to generate a SynthesiserRelation.
Protected Attributes inherited from souffle::SynthesiserRelation
std::vector
< IndexSet::LexicographicalOrder > computedIndices
The final list of indices used.
std::string dataStructure
The data structure used for the relation.
const IndexSet & indices
Indices used for this relation.
const bool isProvenance
Is this relation used with provenance.
size_t masterIndex = -1
The number of the master index.
const RamRelation & relation
Ram relation referred to by this.
Detailed Description
Definition at line 140 of file SynthesiserRelation.h.
Constructor & Destructor Documentation
souffle::SynthesiserRbtsetRelation::SynthesiserRbtsetRelation (const RamRelation & ramRel, const IndexSet & indexSet, bool isProvenance) inline
Definition at line 142 of file SynthesiserRelation.h.
             : SynthesiserRelation(ramRel, indexSet, isProvenance) {}
Member Function Documentation
void souffle::SynthesiserRbtsetRelation::computeIndices () override virtual
Generate index set for a rbtset relation.
Implements souffle::SynthesiserRelation.
Definition at line 1263 of file SynthesiserRelation.cpp.
References souffle::SynthesiserRelation::computedIndices, souffle::IndexSet::getAllOrders(), souffle::SynthesiserRelation::getArity(), i, souffle::SynthesiserRelation::indices, souffle::SynthesiserRelation::isProvenance, and souffle::SynthesiserRelation::masterIndex.
{
     assert(!isProvenance && "rbtset cannot be used with provenance");
     // Generate and set indices
     std::vector<std::vector<int>> inds = indices.getAllOrders();
     // generate a full index if no indices exist
     if (inds.empty()) {
         std::vector<int> fullInd(getArity());
         std::iota(fullInd.begin(), fullInd.end(), 0);
         inds.push_back(fullInd);
     }
     // expand first index to be full if no full indices exist
     bool fullExists = false;
     for (size_t i = 0; i < inds.size(); i++) {
         auto& ind = inds[i];
         if (ind.size() == getArity()) {
             fullExists = true;
             masterIndex = i;
         }
     }
     // expand the first ind to be full, it is guaranteed that at least one index exists
     if (!fullExists) {
         std::set<int> curIndexElems(inds[0].begin(), inds[0].end());
         // expand index to be full
         for (size_t i = 0; i < getArity(); i++) {
             if (curIndexElems.find(i) == curIndexElems.end()) {
                 inds[0].push_back(i);
             }
         }
         masterIndex = 0;
     }
     computedIndices = inds;
 }
void souffle::SynthesiserRbtsetRelation::generateTypeStruct (std::ostream & out) override virtual
Generate type struct of a rbtset relation.
Implements souffle::SynthesiserRelation.
Definition at line 1320 of file SynthesiserRelation.cpp.
References arity, souffle::IndexSet::getAllOrders(), souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getIndexSet(), souffle::SynthesiserRelation::getIndices(), souffle::IndexSet::getLexOrder(), getTypeName(), i, souffle::join(), and souffle::SynthesiserRelation::masterIndex.
{
     size_t arity = getArity();
     const auto& inds = getIndices();
     size_t numIndexes = inds.size();
     std::map<std::vector<int>, int> indexToNumMap;
     // struct definition
     out << "struct " << getTypeName() << " {\n";
     // stored tuple type
     out << "using t_tuple = Tuple<RamDomain, " << arity << ">;\n";
     // generate the btree type for each relation
     for (size_t i = 0; i < inds.size(); i++) {
         auto& ind = inds[i];
         if (i < getIndexSet().getAllOrders().size()) {
             indexToNumMap[getIndexSet().getAllOrders()[i]] = i;
         }
         assert(ind.size() > 0 && "empty index!");
         // generate a custom index comparator based on the index order
         out << "struct tuple_less_" << i << " {\n";
         out << "bool operator()(const t_tuple& a, const t_tuple& b) const {\n";
         out << "return ";
         for (size_t i = 0; i < ind.size() - 1; i++) {
             out << "(a[" << ind[i] << "] < b[" << ind[i] << "] || (a[" << ind[i] << "] == b[" << ind[i]
                 << "] &&\n";
         }
         out << "a[" << ind[ind.size() - 1] << "] < b[" << ind[ind.size() - 1] << "]";
         for (size_t i = 0; i < 2 * (ind.size() - 1); i++) {
             out << ")";
         }
         out << ";\n";
         out << "}\n";
         out << "};\n";
         if (ind.size() == arity) {
             out << "using t_ind_" << i << " = std::set<t_tuple, tuple_less_" << i << ">;\n";
         } else {
             out << "using t_ind_" << i << " = std::multiset<t_tuple, tuple_less_" << i << ">;\n";
         }
         out << "t_ind_" << i << " ind_" << i << ";\n";
     }
     // typedef master index iterator to be struct iterator
     out << "using iterator = t_ind_" << masterIndex << "::iterator;\n";
     // create a global mutex lock for inserts
     out << "std::mutex lock;\n";
     // create a struct storing hints for each btree
     out << "struct context {\n";
     out << "};\n";
     out << "context createContext() { return context(); }\n";
     // insert methods
     out << "bool insert(const t_tuple& t) {\n";
     out << "std::lock_guard<std::mutex> guard(lock);\n";
     out << "if (!contains(t)) {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "ind_" << i << ".insert(t);\n";
     }
     out << "return true;\n";
     out << "} else return false;\n";
     out << "}\n";  // end of insert(t_tuple&)
     out << "bool insert(const t_tuple& t, context& h) {\n";
     out << "return insert(t);\n";
     out << "}\n";  // end of insert(t_tuple&, context&)
     out << "bool insert(const RamDomain* ramDomain) {\n";
     out << "RamDomain data[" << arity << "];\n";
     out << "std::copy(ramDomain, ramDomain + " << arity << ", data);\n";
     out << "const t_tuple& tuple = reinterpret_cast<const t_tuple&>(data);\n";
     out << "return insert(tuple);\n";
     out << "}\n";  // end of insert(RamDomain*)
     std::vector<std::string> decls, params;
     for (size_t i = 0; i < arity; i++) {
         decls.push_back("RamDomain a" + std::to_string(i));
         params.push_back("a" + std::to_string(i));
     }
     out << "bool insert(" << join(decls, ",") << ") {\n";
     out << "RamDomain data[" << arity << "] = {" << join(params, ",") << "};\n";
     out << "return insert(data);\n";
     out << "}\n";  // end of insert(RamDomain x1, RamDomain x2, ...)
     // insertAll methods
     out << "template <typename T>\n";
     out << "void insertAll(T& other) {\n";
     out << "for (auto const& cur : other) {\n";
     out << "insert(cur);\n";
     out << "}\n";
     out << "}\n";  // end of insertAll<T>
     // contains methods
     out << "bool contains(const t_tuple& t) const {\n";
     out << "return ind_" << masterIndex << ".find(t) != ind_" << masterIndex << ".end();\n";
     out << "}\n";
     out << "bool contains(const t_tuple& t, context& h) const {\n";
     out << "return contains(t);\n";
     out << "}\n";
     // size method
     out << "std::size_t size() const {\n";
     out << "return ind_" << masterIndex << ".size();\n";
     out << "}\n";
     // find methods
     out << "iterator find(const t_tuple& t) const {\n";
     out << "return ind_" << masterIndex << ".find(t);\n";
     out << "}\n";
     out << "iterator find(const t_tuple& t, context& h) const {\n";
     out << "return ind_" << masterIndex << ".find(t);\n";
     out << "}\n";
     // empty equalRange method
     out << "range<iterator> equalRange_0(const t_tuple& t, context& h) const {\n";
     out << "return range<iterator>(ind_" << masterIndex << ".begin(),ind_" << masterIndex << ".end());\n";
     out << "}\n";
     // equalRange methods for each pattern which is used to search this relation
     for (int64_t search : getIndexSet().getSearches()) {
         auto lexOrder = getIndexSet().getLexOrder(search);
         size_t indNum = indexToNumMap[lexOrder];
         out << "range<t_ind_" << indNum << "::iterator> equalRange_" << search;
         out << "(const t_tuple& t) const {\n";
         // generate lower and upper bounds for range search
         out << "t_tuple low(t); t_tuple high(t);\n";
         // check which indices to pad out
         for (size_t column = 0; column < arity; column++) {
             // if bit number column is set
             if (!((search >> column) & 1)) {
                 out << "low[" << column << "] = MIN_RAM_DOMAIN;\n";
                 out << "high[" << column << "] = MAX_RAM_DOMAIN;\n";
             }
         }
         out << "return make_range(ind_" << indNum << ".lower_bound(low), ind_" << indNum
             << ".upper_bound(high));\n";
         out << "}\n";
         out << "range<t_ind_" << indNum << "::iterator> equalRange_" << search;
         out << "(const t_tuple& t, context& h) const {\n";
         out << "return equalRange_" << search << "(t);\n";
         out << "}\n";
     }
     // empty method
     out << "bool empty() const {\n";
     out << "return ind_" << masterIndex << ".empty();\n";
     out << "}\n";
     // partition method for parallelism
     out << "std::vector<range<iterator>> partition() const {\n";
     out << "range<iterator> full(begin(), end());\n";
     out << "return full.partition(100);\n";
     out << "}\n";
     // purge method
     out << "void purge() {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "ind_" << i << ".clear();\n";
     }
     out << "}\n";
     // begin and end iterators
     out << "iterator begin() const {\n";
     out << "return ind_" << masterIndex << ".begin();\n";
     out << "}\n";
     out << "iterator end() const {\n";
     out << "return ind_" << masterIndex << ".end();\n";
     out << "}\n";
     // printHintStatistics method
     out << "void printHintStatistics(std::ostream& o, const std::string prefix) const {\n";
     out << "o << \"rbtset index: no hint statistics supported\\n\";\n";
     out << "}\n";
     // end struct
     out << "};\n";
 }
std::string souffle::SynthesiserRbtsetRelation::getTypeName () override virtual
Generate type name of a rbtset relation.
Implements souffle::SynthesiserRelation.
Definition at line 1304 of file SynthesiserRelation.cpp.
References souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getIndexSet(), souffle::SynthesiserRelation::getIndices(), and souffle::join().
Referenced by generateTypeStruct().
{
     std::stringstream res;
     res << "t_rbtset_" << getArity();
     for (auto& ind : getIndices()) {
         res << "__" << join(ind, "_");
     }
     for (auto& search : getIndexSet().getSearches()) {
         res << "__" << search;
     }
     return res.str();
 }
The documentation for this class was generated from the following files:
SynthesiserRelation.h
SynthesiserRelation.cpp