souffle: souffle::profile::HtmlString Class Reference
souffle::profile::HtmlString Class Reference
#include <HtmlString.h>
Public Member Functions
std::string get_first_half ()
std::string get_second_half ()
Protected Member Functions
std::string wrapCss (const std::string &css)
std::string wrapJs (const std::string &js)
Detailed Description
Definition at line 30 of file HtmlString.h.
Member Function Documentation
std::string souffle::profile::HtmlString::get_first_half () inline
Definition at line 32 of file HtmlString.h.
References souffle::profile::html::cssChartist, souffle::profile::html::cssStyle, souffle::profile::html::htmlBodyTop, souffle::profile::html::htmlHeadBottom, souffle::profile::html::htmlHeadTop, and wrapCss().
Referenced by souffle::profile::Tui::outputJson().
{
         std::stringstream ss;
         ss << html::htmlHeadTop << wrapCss(html::cssChartist) << wrapCss(html::cssStyle)
            << html::htmlHeadBottom << html::htmlBodyTop << "<script>";
         return ss.str();
     }
std::string souffle::profile::HtmlString::get_second_half () inline
Definition at line 38 of file HtmlString.h.
References souffle::profile::html::htmlBodyBottom, souffle::profile::html::jsChartistPlugin, souffle::profile::html::jsMain, souffle::profile::html::jsTableSort, souffle::profile::html::jsUtil, and wrapJs().
{
         std::stringstream ss;
         ss << "</script>" << wrapJs(html::jsTableSort) << wrapJs(html::jsChartistMin)
            << wrapJs(html::jsChartistPlugin) << wrapJs(html::jsUtil) << wrapJs(html::jsMain)
            << html::htmlBodyBottom;
         return ss.str();
     }
std::string souffle::profile::HtmlString::wrapCss (const std::string & css) inline protected
Definition at line 47 of file HtmlString.h.
Referenced by get_first_half().
{
         return "<style>" + css + "</style>";
     }
std::string souffle::profile::HtmlString::wrapJs (const std::string & js) inline protected
Definition at line 50 of file HtmlString.h.
Referenced by get_second_half().
{
         return "<script>" + js + "</script>";
     }
The documentation for this class was generated from the following file:
profile/HtmlString.h