souffle: souffle::RamArgument Class Reference
souffle::RamArgument Class Reference
Access argument of a subroutine.
#include <RamValue.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamArgument * clone () const override
Create clone.
size_t getArgNumber () const
Get argument number.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getLevel () const override
Get level.
void print (std::ostream &os) const override
Print.
RamArgument (size_t number)
Public Member Functions inherited from souffle::RamValue
bool isConstant () const
Determines whether this value is a constant or not.
RamValue (RamNodeType type, bool isCnst)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
size_t number
Argument number.
Additional Inherited Members
Protected Attributes inherited from souffle::RamValue
bool cnst
Detailed Description
Access argument of a subroutine.
Arguments are number from zero 0 to n-1 where n is the number of arguments of the subroutine.
Definition at line 567 of file RamValue.h.
Constructor & Destructor Documentation
souffle::RamArgument::RamArgument (size_t number) inline
Definition at line 572 of file RamValue.h.
Referenced by clone().
 : RamValue(RN_Argument, false), number(number) {}
Member Function Documentation
void souffle::RamArgument::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 602 of file RamValue.h.
 {}
RamArgument* souffle::RamArgument::clone () const inline override virtual
Create clone.
Implements souffle::RamValue.
Definition at line 596 of file RamValue.h.
References getArgNumber(), and RamArgument().
{
         auto* res = new RamArgument(getArgNumber());
         return res;
     }
bool souffle::RamArgument::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 606 of file RamValue.h.
References getArgNumber().
{
         assert(nullptr != dynamic_cast<const RamArgument*>(&node));
         const auto& other = static_cast<const RamArgument&>(node);
         return getArgNumber() == other.getArgNumber();
     }
size_t souffle::RamArgument::getArgNumber () const inline
Get argument number.
Definition at line 575 of file RamValue.h.
References number.
Referenced by clone(), souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalVal().
{
         return number;
     }
std::vector<const RamNode*> souffle::RamArgument::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 591 of file RamValue.h.
{
         return std::vector<const RamNode*>();
     }
size_t souffle::RamArgument::getLevel () const inline override virtual
Get level.
Implements souffle::RamValue.
Definition at line 586 of file RamValue.h.
{
         return 0;
     }
void souffle::RamArgument::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 580 of file RamValue.h.
References number.
{
         os << "argument(" << number << ")";
     }
Field Documentation
size_t souffle::RamArgument::number private
Argument number.
Definition at line 569 of file RamValue.h.
Referenced by getArgNumber(), and print().
The documentation for this class was generated from the following file:
RamValue.h