souffle: souffle::SymbolMask Class Reference
souffle::SymbolMask Class Reference
#include <SymbolMask.h>
Public Member Functions
size_t getArity () const
bool isSymbol (size_t index) const
bool operator!= (const SymbolMask &other) const
bool operator== (const SymbolMask &other) const
void print (std::ostream &out) const
void setSymbol (size_t index, bool value=true)
SymbolMask (size_t arity)
SymbolMask (std::initializer_list< bool > symbolList)
Private Attributes
std::vector< bool > mask
Friends
std::ostream & operator<< (std::ostream &out, const SymbolMask &mask)
Detailed Description
Definition at line 22 of file SymbolMask.h.
Constructor & Destructor Documentation
souffle::SymbolMask::SymbolMask (size_t arity) inline
Definition at line 26 of file SymbolMask.h.
 : mask(arity) {}
souffle::SymbolMask::SymbolMask (std::initializer_list< bool > symbolList) inline
Definition at line 28 of file SymbolMask.h.
 : mask(symbolList) {}
Member Function Documentation
size_t souffle::SymbolMask::getArity () const inline
Definition at line 30 of file SymbolMask.h.
References mask.
Referenced by isSymbol(), souffle::ReadStreamSQLite::readNextTuple(), souffle::ReadStreamCSV::readNextTuple(), souffle::ReadStreamCSV::ReadStreamCSV(), setSymbol(), souffle::WriteFileCSV::writeNextTuple(), souffle::WriteCoutCSV::writeNextTuple(), and souffle::WriteStreamSQLite::WriteStreamSQLite().
{
         return mask.size();
     }
bool souffle::SymbolMask::isSymbol (size_t index) const inline
Definition at line 34 of file SymbolMask.h.
References getArity(), and mask.
Referenced by souffle::WriteStreamSQLite::createRelationView(), souffle::ReadStreamSQLite::readNextTuple(), souffle::ReadStreamCSV::readNextTuple(), souffle::WriteStreamSQLite::writeNextTuple(), souffle::WriteFileCSV::writeNextTuple(), and souffle::WriteCoutCSV::writeNextTuple().
{
         return index < getArity() && mask[index];
     }
bool souffle::SymbolMask::operator!= (const SymbolMask & other) const inline
Definition at line 48 of file SymbolMask.h.
References mask.
{
         return mask != other.mask;
     }
bool souffle::SymbolMask::operator== (const SymbolMask & other) const inline
Definition at line 44 of file SymbolMask.h.
References mask.
{
         return mask == other.mask;
     }
void souffle::SymbolMask::print (std::ostream & out) const inline
Definition at line 52 of file SymbolMask.h.
References mask.
{
         auto cur = mask.begin();
         if (cur == mask.end()) {
             return;
         }
         out << *cur++;
         for (; cur != mask.end(); ++cur) {
             out << ", " << *cur;
         }
     }
void souffle::SymbolMask::setSymbol (size_t index, bool value = true) inline
Definition at line 38 of file SymbolMask.h.
References getArity(), and mask.
Referenced by souffle::ExplainProvenance::getRelationOutput().
{
         if (index < getArity()) {
             mask[index] = value;
         }
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const SymbolMask & mask) friend
Definition at line 64 of file SymbolMask.h.
{
         mask.print(out);
         return out;
     }
Field Documentation
std::vector<bool> souffle::SymbolMask::mask private
Definition at line 23 of file SymbolMask.h.
Referenced by souffle::RamRelation::equal(), getArity(), isSymbol(), operator!=(), operator==(), print(), and setSymbol().
The documentation for this class was generated from the following file:
SymbolMask.h