souffle: souffle::AstSubroutineArgument Class Reference
souffle::AstSubroutineArgument Class Reference
An argument taking its value from an argument of a RAM subroutine.
#include <AstArgument.h>
Public Member Functions
void apply (const AstNodeMapper &) override
Mutates this node.
AstSubroutineArgument (size_t n)
AstSubroutineArgument * clone () const override
Creates a clone of this AST sub-structure.
size_t getNumber () const
Return argument number.
void print (std::ostream &os) const override
Print argument to the given output stream.
Public Member Functions inherited from souffle::AstArgument
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Private Attributes
size_t number
Index of argument in argument list.
Detailed Description
An argument taking its value from an argument of a RAM subroutine.
Definition at line 742 of file AstArgument.h.
Constructor & Destructor Documentation
souffle::AstSubroutineArgument::AstSubroutineArgument (size_t n) inline
Definition at line 748 of file AstArgument.h.
Referenced by clone().
 : AstArgument(), number(n) {}
Member Function Documentation
void souffle::AstSubroutineArgument::apply (const AstNodeMapper &) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 768 of file AstArgument.h.
{
         // no sub-nodes to consider
     }
AstSubroutineArgument* souffle::AstSubroutineArgument::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstArgument.
Definition at line 761 of file AstArgument.h.
References AstSubroutineArgument(), souffle::AstNode::getSrcLoc(), and number.
{
         auto* res = new AstSubroutineArgument(number);
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstSubroutineArgument::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 774 of file AstArgument.h.
References number.
{
         assert(nullptr != dynamic_cast<const AstSubroutineArgument*>(&node));
         const auto& other = static_cast<const AstSubroutineArgument&>(node);
         return number == other.number;
     }
size_t souffle::AstSubroutineArgument::getNumber () const inline
Return argument number.
Definition at line 751 of file AstArgument.h.
References number.
{
         return number;
     }
void souffle::AstSubroutineArgument::print (std::ostream & os) const inline override virtual
Print argument to the given output stream.
Implements souffle::AstNode.
Definition at line 756 of file AstArgument.h.
References number.
{
         os << "arg_" << number;
     }
Field Documentation
size_t souffle::AstSubroutineArgument::number private
Index of argument in argument list.
Definition at line 745 of file AstArgument.h.
Referenced by clone(), equal(), getNumber(), and print().
The documentation for this class was generated from the following file:
AstArgument.h