souffle: souffle::RamOperation Class Reference
souffle::RamOperation Class Reference abstract
Abstract class for a relational algebra operation.
#include <RamOperation.h>
Public Member Functions
virtual void addCondition (std::unique_ptr< RamCondition > c, const RamOperation &root)
Add condition.
void addCondition (std::unique_ptr< RamCondition > c)
Add condition.
void apply (const RamNodeMapper &map) override
Apply mapper.
RamOperation * clone () const override=0
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
RamCondition * getCondition () const
Get condition.
virtual size_t getDepth () const =0
Get depth.
size_t getLevel () const
Get level.
virtual void print (std::ostream &os, int tabpos) const =0
Print.
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type, size_t l)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamCondition > condition
condition that is checked for each obtained tuple
size_t level
the nesting level of this operation
Detailed Description
Abstract class for a relational algebra operation.
Definition at line 38 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamOperation::RamOperation (RamNodeType type, size_t l) inline
Definition at line 51 of file RamOperation.h.
 : RamNode(type), level(l), condition(nullptr) {}
Member Function Documentation
void souffle::RamOperation::addCondition (std::unique_ptr< RamCondition > c, const RamOperation & root) virtual
Add condition.
add condition
Reimplemented in souffle::RamProject, souffle::RamAggregate, souffle::RamScan, and souffle::RamSearch.
Definition at line 31 of file RamOperation.cpp.
References condition, and level.
Referenced by addCondition(), and souffle::RamSearch::addCondition().
{
     assert(c->getLevel() == level);
     if (condition) {
         condition = std::make_unique<RamAnd>(std::move(condition), std::move(c));
     } else {
         condition.swap(c);
     }
 }
void souffle::RamOperation::addCondition (std::unique_ptr< RamCondition > c) inline
Add condition.
Definition at line 75 of file RamOperation.h.
References addCondition().
{
         addCondition(std::move(c), *this);
     }
void souffle::RamOperation::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Reimplemented in souffle::RamReturn, souffle::RamProject, souffle::RamAggregate, souffle::RamLookup, souffle::RamScan, and souffle::RamSearch.
Definition at line 96 of file RamOperation.h.
References condition, and map.
Referenced by souffle::RamSearch::apply(), souffle::RamProject::apply(), and souffle::RamReturn::apply().
{
         if (condition) {
             condition = map(std::move(condition));
         }
     }
RamOperation* souffle::RamOperation::clone () const override pure virtual
Create clone.
Implements souffle::RamNode.
Implemented in souffle::RamReturn, souffle::RamProject, souffle::RamAggregate, souffle::RamLookup, and souffle::RamScan.
Referenced by souffle::RamScan::clone().
bool souffle::RamOperation::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Reimplemented in souffle::RamReturn, souffle::RamProject, souffle::RamAggregate, souffle::RamLookup, souffle::RamScan, and souffle::RamSearch.
Definition at line 104 of file RamOperation.h.
References getCondition().
Referenced by souffle::RamSearch::equal(), souffle::RamProject::equal(), and souffle::RamReturn::equal().
{
         assert(nullptr != dynamic_cast<const RamOperation*>(&node));
         const auto& other = static_cast<const RamOperation&>(node);
         if (getCondition() != nullptr && other.getCondition() != nullptr) {
             return *getCondition() == *other.getCondition();
         } else if (getCondition() == nullptr && other.getCondition() == nullptr) {
             return true;
         } else {
             return false;
         }
     }
std::vector<const RamNode*> souffle::RamOperation::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Reimplemented in souffle::RamProject, souffle::RamScan, and souffle::RamSearch.
Definition at line 85 of file RamOperation.h.
References condition.
Referenced by souffle::RamSearch::getChildNodes(), and souffle::RamProject::getChildNodes().
{
         if (!condition) {
             return toVector<const RamNode*>();
         }
         return {condition.get()};
     }
RamCondition* souffle::RamOperation::getCondition () const inline
Get condition.
Definition at line 80 of file RamOperation.h.
References condition.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::Interpreter::evalOp(), souffle::RamScan::print(), souffle::RamLookup::print(), souffle::RamAggregate::print(), and souffle::RamProject::print().
{
         return condition.get();
     }
virtual size_t souffle::RamOperation::getDepth () const pure virtual
Get depth.
Implemented in souffle::RamReturn, souffle::RamProject, and souffle::RamSearch.
Referenced by souffle::Interpreter::evalOp().
size_t souffle::RamOperation::getLevel () const inline
Get level.
Definition at line 55 of file RamOperation.h.
References level.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalOp(), souffle::RamLookup::print(), and souffle::RamAggregate::print().
{
         return level;
     }
virtual void souffle::RamOperation::print (std::ostream & os, int tabpos) const pure virtual
Print.
Implemented in souffle::RamReturn, souffle::RamProject, souffle::RamAggregate, souffle::RamLookup, and souffle::RamScan.
Referenced by print(), souffle::RamScan::print(), souffle::RamLookup::print(), and souffle::RamAggregate::print().
void souffle::RamOperation::print (std::ostream & os) const inline override virtual
Pretty print.
Implements souffle::RamNode.
Definition at line 67 of file RamOperation.h.
References print().
{
         print(os, 0);
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamOperation::condition protected
condition that is checked for each obtained tuple
If condition is a nullptr, then no condition applies
Definition at line 48 of file RamOperation.h.
Referenced by addCondition(), souffle::RamAggregate::addCondition(), souffle::RamProject::addCondition(), apply(), souffle::RamScan::clone(), getChildNodes(), getCondition(), souffle::RamScan::print(), souffle::RamLookup::print(), souffle::RamAggregate::print(), and souffle::RamProject::print().
size_t souffle::RamOperation::level protected
the nesting level of this operation
Definition at line 41 of file RamOperation.h.
Referenced by addCondition(), souffle::RamSearch::addCondition(), souffle::RamScan::addCondition(), souffle::RamAggregate::addCondition(), souffle::RamProject::addCondition(), souffle::RamProject::clone(), souffle::RamReturn::clone(), getLevel(), and souffle::RamScan::print().
The documentation for this class was generated from the following files:
RamOperation.h
RamOperation.cpp