souffle: souffle::LogStatement Class Reference
souffle::LogStatement Class Reference
#include <LogStatement.h>
Static Public Member Functions
static const std::string cRecursiveRelation (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string nNonrecursiveRelation (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string nNonrecursiveRule (const std::string &relationName, const SrcLocation &srcLocation, const std::string &datalogText)
static const std::string nRecursiveRelation (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string nRecursiveRule (const std::string &relationName, const int version, const SrcLocation &srcLocation, const std::string &datalogText)
static const std::string pProofCounter (const std::string &relationName, const SrcLocation &srcLocation, const std::string &datalogText)
static const std::string runtime ()
static const std::string startDebug ()
static const std::string tNonrecursiveRelation (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string tNonrecursiveRule (const std::string &relationName, const SrcLocation &srcLocation, const std::string &datalogText)
static const std::string tRecursiveRelation (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string tRecursiveRule (const std::string &relationName, const int version, const SrcLocation &srcLocation, const std::string &datalogText)
static const std::string tRelationLoadTime (const std::string &relationName, const SrcLocation &srcLocation)
static const std::string tRelationSaveTime (const std::string &relationName, const SrcLocation &srcLocation)
Static Private Member Functions
static const std::string & getLogFileType ()
Detailed Description
Definition at line 24 of file LogStatement.h.
Member Function Documentation
static const std::string souffle::LogStatement::cRecursiveRelation (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 199 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateRecursiveRelation().
{
         const char* messageType = "@c-recursive-relation";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << "\"time\": ";
         } else {
             line << messageType << ";" << relationName << ";" << srcLocation << ";";
         }
         return line.str();
     }
static const std::string& souffle::LogStatement::getLogFileType () inline static private
Definition at line 26 of file LogStatement.h.
References souffle::Global::config(), and souffle::fileExtension().
Referenced by cRecursiveRelation(), nNonrecursiveRelation(), nNonrecursiveRule(), nRecursiveRelation(), nRecursiveRule(), pProofCounter(), runtime(), startDebug(), tNonrecursiveRelation(), tNonrecursiveRule(), tRecursiveRelation(), tRecursiveRule(), tRelationLoadTime(), and tRelationSaveTime().
{
         static const std::string logFileType = fileExtension(Global::config().get("profile"));
         return logFileType;
     }
static const std::string souffle::LogStatement::nNonrecursiveRelation (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 79 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateNonRecursiveRelation().
{
         const char* messageType = "@n-nonrecursive-relation";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << "\"tuples\": ";
         } else {
             line << messageType << ";" << relationName << ";" << srcLocation << ";";
         }
         return line.str();
     }
static const std::string souffle::LogStatement::nNonrecursiveRule (const std::string & relationName, const SrcLocation & srcLocation, const std::string & datalogText) inline static
Definition at line 112 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateNonRecursiveRelation().
{
         const char* messageType = "@n-nonrecursive-rule";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << R"("rule": ")" << datalogText << "\", ";
             line << "\"tuples\": ";
         } else {
             line << messageType << ";" << relationName << ";" << srcLocation << ";" << datalogText << ";";
         }
         return line.str();
     }
static const std::string souffle::LogStatement::nRecursiveRelation (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 183 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateRecursiveRelation().
{
         const char* messageType = "@n-recursive-relation";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << "\"tuples\": ";
         } else {
             line << messageType << ";" << relationName << ";" << srcLocation << ";";
         }
         return line.str();
     }
static const std::string souffle::LogStatement::nRecursiveRule (const std::string & relationName, const int version, const SrcLocation & srcLocation, const std::string & datalogText) inline static
Definition at line 148 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateRecursiveRelation().
{
         const char* messageType = "@n-recursive-rule";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("version": ")" << version << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << R"("rule": ")" << datalogText << "\", ";
             line << "\"tuples\": ";
         } else {
             line << messageType << ";" << relationName << ";" << version << ";" << srcLocation << ";"
                  << datalogText << ";";
         }
         return line.str();
     }
static const std::string souffle::LogStatement::pProofCounter (const std::string & relationName, const SrcLocation & srcLocation, const std::string & datalogText) inline static
Definition at line 215 of file LogStatement.h.
References getLogFileType().
{
         // TODO (#590): the profiler should be modified to use this type of log message, as currently these
         // messages are ignored
         const char* messageType = "#p-proof-counter";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << R"("rule": ")" << datalogText << "\", ";
             line << "\"failed-proofs\": ";
         } else {
             line << messageType << ";" << relationName << ";" << srcLocation << ";" << datalogText << ";";
             // TODO (#590): the additional semicolon is added to maintain backwards compatibility and should
             // eventually be removed
             line << ";";
         }
         return line.str();
     }
static const std::string souffle::LogStatement::runtime () inline static
Definition at line 237 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateProgram().
{
         const char* messageType = "@runtime";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << "\"time\": ";
         } else {
             line << messageType << ";";
         }
         return line.str();
     }
static const std::string souffle::LogStatement::startDebug () inline static
Definition at line 250 of file LogStatement.h.
References getLogFileType().
{
         const char* messageType = "@start-debug";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "[";
         } else {
             line << messageType;
         }
         return line.str();
     }
static const std::string souffle::LogStatement::tNonrecursiveRelation (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 32 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateNonRecursiveRelation().
{
         const char* messageType = "@t-nonrecursive-relation";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << "\"time\": ";
         } else {
             line << messageType << ";" << relationName << ";" << srcLocation << ";";
         }
         return line.str();
     }
static const std::string souffle::LogStatement::tNonrecursiveRule (const std::string & relationName, const SrcLocation & srcLocation, const std::string & datalogText) inline static
Definition at line 95 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateNonRecursiveRelation().
{
         const char* messageType = "@t-nonrecursive-rule";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << R"("rule": ")" << datalogText << "\", ";
             line << "\"time\": ";
         } else {
             line << messageType << ";" << relationName << ";" << srcLocation << ";" << datalogText << ";";
         }
         return line.str();
     }
static const std::string souffle::LogStatement::tRecursiveRelation (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 167 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateRecursiveRelation().
{
         const char* messageType = "@t-recursive-relation";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << "\"time\": ";
         } else {
             line << messageType << ";" << relationName << ";" << srcLocation << ";";
         }
         return line.str();
     }
static const std::string souffle::LogStatement::tRecursiveRule (const std::string & relationName, const int version, const SrcLocation & srcLocation, const std::string & datalogText) inline static
Definition at line 129 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateRecursiveRelation().
{
         const char* messageType = "@t-recursive-rule";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("version": ")" << version << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << R"("rule": ")" << datalogText << "\", ";
             line << "\"time\": ";
         } else {
             line << messageType << ";" << relationName << ";" << version << ";" << srcLocation << ";"
                  << datalogText << ";";
         }
         return line.str();
     }
static const std::string souffle::LogStatement::tRelationLoadTime (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 47 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateProgram().
{
         const char* messageType = "@t-relation-loadtime";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << "\"loadtime\": ";
         } else {
             line << messageType << ";" << relationName << ";" << srcLocation << ";loadtime;";
         }
         return line.str();
     }
static const std::string souffle::LogStatement::tRelationSaveTime (const std::string & relationName, const SrcLocation & srcLocation) inline static
Definition at line 63 of file LogStatement.h.
References getLogFileType().
Referenced by souffle::AstTranslator::translateProgram().
{
         const char* messageType = "@t-relation-savetime";
         std::stringstream line;
         if (LogStatement::getLogFileType() == "json") {
             line << "{";
             line << R"("msg-type": ")" << messageType << "\", ";
             line << R"("relation": ")" << relationName << "\", ";
             line << R"("src-locator": ")" << srcLocation << "\", ";
             line << "\"savetime\": ";
         } else {
             line << messageType << ";" << relationName << ";" << srcLocation << ";savetime;";
         }
         return line.str();
     }
The documentation for this class was generated from the following file:
LogStatement.h