souffle: souffle::profile::ProgramRun Class Reference
souffle::profile::ProgramRun Class Reference
#include <ProgramRun.h>
Public Member Functions
std::string formatNum (int precision, long number)
std::vector< std::vector
< std::string > > formatTable (Table table, int precision)
std::string formatTime (double runtime)
std::chrono::microseconds getEndtime () const
Relation * getRelation (std::string name)
std::unordered_map
< std::string, std::shared_ptr
< Relation > > & getRelation_map ()
std::set< std::shared_ptr
< Relation > > getRelationsAtTime (double start, double end)
std::string getRuntime ()
std::chrono::microseconds getStarttime () const
double getTotCopyTime ()
double getTotLoadtime ()
long getTotNumRecTuples ()
long getTotNumTuples ()
double getTotSavetime ()
double getTotTime ()
ProgramRun ()
void setEndtime (std::chrono::microseconds time)
void setRelation_map (std::unordered_map< std::string, std::shared_ptr< Relation >> &relation_map)
void setStarttime (std::chrono::microseconds time)
std::string toString ()
void update ()
Private Attributes
std::chrono::microseconds endTime {0}
std::unordered_map
< std::string, std::shared_ptr
< Relation > > relation_map
std::chrono::microseconds startTime {0}
double tot_copy_time = 0.0
double tot_rec_tup = 0.0
Detailed Description
Definition at line 29 of file ProgramRun.h.
Constructor & Destructor Documentation
souffle::profile::ProgramRun::ProgramRun () inline
Definition at line 39 of file ProgramRun.h.
 : relation_map() {}
Member Function Documentation
std::string souffle::profile::ProgramRun::formatNum (int precision, long number) inline
Definition at line 155 of file ProgramRun.h.
References souffle::profile::Tools::formatNum().
{
         return Tools::formatNum(precision, number);
     }
std::vector<std::vector<std::string> > souffle::profile::ProgramRun::formatTable (Table table, int precision) inline
Definition at line 159 of file ProgramRun.h.
References souffle::profile::Tools::formatTable().
{
         return Tools::formatTable(table, precision);
     }
std::string souffle::profile::ProgramRun::formatTime (double runtime) inline
Definition at line 151 of file ProgramRun.h.
References souffle::profile::Tools::formatTime().
Referenced by getRuntime().
{
         return Tools::formatTime(runtime);
     }
std::chrono::microseconds souffle::profile::ProgramRun::getEndtime () const inline
Definition at line 82 of file ProgramRun.h.
References endTime.
{
         return endTime;
     }
Relation* souffle::profile::ProgramRun::getRelation (std::string name) inline
Definition at line 134 of file ProgramRun.h.
References name, and relation_map.
{
         if (relation_map.find(name) != relation_map.end()) {
             return &(*relation_map[name]);
         }
         return nullptr;
     }
std::unordered_map<std::string, std::shared_ptr<Relation> >& souffle::profile::ProgramRun::getRelation_map () inline
Definition at line 67 of file ProgramRun.h.
References relation_map.
{
         return relation_map;
     }
std::set<std::shared_ptr<Relation> > souffle::profile::ProgramRun::getRelationsAtTime (double start, double end) inline
Definition at line 141 of file ProgramRun.h.
References relation_map.
{
         std::set<std::shared_ptr<Relation>> result;
         for (auto& cur : relation_map) {
             if (cur.second->getStarttime() <= end && cur.second->getEndtime() >= start) {
                 result.insert(cur.second);
             }
         }
         return result;
     }
std::string souffle::profile::ProgramRun::getRuntime () inline
Definition at line 71 of file ProgramRun.h.
References endTime, formatTime(), and startTime.
Referenced by toString().
{
         if (startTime == endTime) {
             return "--";
         }
         return formatTime((endTime - startTime).count() / 1000000);
     }
std::chrono::microseconds souffle::profile::ProgramRun::getStarttime () const inline
Definition at line 78 of file ProgramRun.h.
References startTime.
{
         return startTime;
     }
double souffle::profile::ProgramRun::getTotCopyTime () inline
Definition at line 118 of file ProgramRun.h.
References relation_map.
Referenced by update().
{
         double result = 0;
         for (auto& item : relation_map) {
             result += item.second->getCopyTime();
         }
         return result;
     }
double souffle::profile::ProgramRun::getTotLoadtime () inline
Definition at line 86 of file ProgramRun.h.
References relation_map.
{
         double result = 0;
         for (auto& item : relation_map) {
             result += item.second->getLoadtime();
         }
         return result;
     }
long souffle::profile::ProgramRun::getTotNumRecTuples () inline
Definition at line 110 of file ProgramRun.h.
References relation_map.
Referenced by update().
{
         long result = 0;
         for (auto& item : relation_map) {
             result += item.second->getTotNumRec_tuples();
         }
         return result;
     }
long souffle::profile::ProgramRun::getTotNumTuples () inline
Definition at line 102 of file ProgramRun.h.
References relation_map.
{
         long result = 0;
         for (auto& item : relation_map) {
             result += item.second->getTotNum_tuples();
         }
         return result;
     }
double souffle::profile::ProgramRun::getTotSavetime () inline
Definition at line 94 of file ProgramRun.h.
References relation_map.
{
         double result = 0;
         for (auto& item : relation_map) {
             result += item.second->getSavetime();
         }
         return result;
     }
double souffle::profile::ProgramRun::getTotTime () inline
Definition at line 126 of file ProgramRun.h.
References relation_map.
{
         double result = 0;
         for (auto& item : relation_map) {
             result += item.second->getRecTime();
         }
         return result;
     }
void souffle::profile::ProgramRun::setEndtime (std::chrono::microseconds time) inline
Definition at line 45 of file ProgramRun.h.
References endTime.
{
         endTime = time;
     }
void souffle::profile::ProgramRun::setRelation_map (std::unordered_map< std::string, std::shared_ptr< Relation >> & relation_map) inline
Definition at line 49 of file ProgramRun.h.
References relation_map.
{
         this->relation_map = relation_map;
     }
void souffle::profile::ProgramRun::setStarttime (std::chrono::microseconds time) inline
Definition at line 41 of file ProgramRun.h.
References startTime.
{
         startTime = time;
     }
std::string souffle::profile::ProgramRun::toString () inline
Definition at line 58 of file ProgramRun.h.
References getRuntime(), and relation_map.
{
         std::ostringstream output;
         output << "ProgramRun:" << getRuntime() << "\nRelations:\n";
         for (auto r = relation_map.begin(); r != relation_map.end(); ++r) {
             output << r->second->toString() << "\n";
         }
         return output.str();
     }
void souffle::profile::ProgramRun::update () inline
Definition at line 53 of file ProgramRun.h.
References getTotCopyTime(), getTotNumRecTuples(), tot_copy_time, and tot_rec_tup.
{
         tot_rec_tup = (double)getTotNumRecTuples();
         tot_copy_time = getTotCopyTime();
     };
Field Documentation
std::chrono::microseconds souffle::profile::ProgramRun::endTime {0} private
Definition at line 33 of file ProgramRun.h.
Referenced by getEndtime(), getRuntime(), and setEndtime().
std::unordered_map<std::string, std::shared_ptr<Relation> > souffle::profile::ProgramRun::relation_map private
Definition at line 31 of file ProgramRun.h.
Referenced by getRelation(), getRelation_map(), getRelationsAtTime(), getTotCopyTime(), getTotLoadtime(), getTotNumRecTuples(), getTotNumTuples(), getTotSavetime(), getTotTime(), setRelation_map(), and toString().
std::chrono::microseconds souffle::profile::ProgramRun::startTime {0} private
Definition at line 32 of file ProgramRun.h.
Referenced by getRuntime(), getStarttime(), and setStarttime().
double souffle::profile::ProgramRun::tot_copy_time = 0.0 private
Definition at line 36 of file ProgramRun.h.
Referenced by update().
double souffle::profile::ProgramRun::tot_rec_tup = 0.0 private
Definition at line 35 of file ProgramRun.h.
Referenced by update().
The documentation for this class was generated from the following file:
profile/ProgramRun.h