souffle: souffle::SparseDisjointSet< SparseDomain >::iterator Class Reference
souffle::SparseDisjointSet< SparseDomain >::iterator Class Reference
iterator for the class - is assumed not to be thread safe (as modifications to the underlying class will invalidate anyway)
#include <UnionFind.h>
Public Member Functions
iterator (SparseDisjointSet *sds, const SparseDomain rep)
iterator (SparseDisjointSet *sds, const SparseDomain rep, bool)
iterator (SparseDisjointSet *sds, bool isRepIter)
iterator (SparseDisjointSet *sds, bool isRepIter, bool)
const SparseDomain operator* () const
SparseDomain operator* ()
iterator & operator++ (int)
iterator operator++ ()
Private Member Functions
SparseDomain yield () const
Private Attributes
DisjointSet::iterator maskIter
SparseDisjointSet * sds
Friends
bool operator!= (const iterator &x, const iterator &y)
bool operator== (const iterator &x, const iterator &y)
Detailed Description
template<typename SparseDomain>
class souffle::SparseDisjointSet< SparseDomain >::iterator
iterator for the class - is assumed not to be thread safe (as modifications to the underlying class will invalidate anyway)
Definition at line 523 of file UnionFind.h.
Constructor & Destructor Documentation
template<typename SparseDomain> souffle::SparseDisjointSet< SparseDomain >::iterator::iterator (SparseDisjointSet * sds, const SparseDomain rep) inline
Definition at line 537 of file UnionFind.h.
                 : sds(sds), maskIter(sds->ds.begin(sds->toDense(rep))){};
template<typename SparseDomain> souffle::SparseDisjointSet< SparseDomain >::iterator::iterator (SparseDisjointSet * sds, const SparseDomain rep, bool) inline
Definition at line 540 of file UnionFind.h.
                 : sds(sds), maskIter(sds->ds.end(sds->toDense(rep))){};
template<typename SparseDomain> souffle::SparseDisjointSet< SparseDomain >::iterator::iterator (SparseDisjointSet * sds, bool isRepIter) inline
Definition at line 544 of file UnionFind.h.
 : sds(sds), maskIter(sds->ds.beginReps()){};
template<typename SparseDomain> souffle::SparseDisjointSet< SparseDomain >::iterator::iterator (SparseDisjointSet * sds, bool isRepIter, bool) inline
Definition at line 546 of file UnionFind.h.
 : sds(sds), maskIter(sds->ds.endReps()){};
Member Function Documentation
template<typename SparseDomain> const SparseDomain souffle::SparseDisjointSet< SparseDomain >::iterator::operator* () const inline
Definition at line 559 of file UnionFind.h.
References souffle::SparseDisjointSet< SparseDomain >::iterator::yield().
{
             return yield();
         }
template<typename SparseDomain> SparseDomain souffle::SparseDisjointSet< SparseDomain >::iterator::operator* () inline
Definition at line 563 of file UnionFind.h.
References souffle::SparseDisjointSet< SparseDomain >::iterator::yield().
{
             return yield();
         }
template<typename SparseDomain> iterator& souffle::SparseDisjointSet< SparseDomain >::iterator::operator++ (int) inline
Definition at line 548 of file UnionFind.h.
References souffle::SparseDisjointSet< SparseDomain >::iterator::maskIter.
{
             ++maskIter;
             return *this;
         }
template<typename SparseDomain> iterator souffle::SparseDisjointSet< SparseDomain >::iterator::operator++ () inline
Definition at line 553 of file UnionFind.h.
References souffle::SparseDisjointSet< SparseDomain >::iterator::maskIter.
{
             iterator ret(*this);
             ++maskIter;
             return ret;
         }
template<typename SparseDomain> SparseDomain souffle::SparseDisjointSet< SparseDomain >::iterator::yield () const inline private
Definition at line 531 of file UnionFind.h.
References souffle::SparseDisjointSet< SparseDomain >::iterator::maskIter, souffle::SparseDisjointSet< SparseDomain >::iterator::sds, and souffle::SparseDisjointSet< SparseDomain >::toSparse().
Referenced by souffle::SparseDisjointSet< SparseDomain >::iterator::operator*().
{
             return sds->toSparse(*maskIter);
         }
Friends And Related Function Documentation
template<typename SparseDomain> bool operator!= (const iterator & x, const iterator & y) friend
Definition at line 571 of file UnionFind.h.
{
             return !(x == y);
         };
template<typename SparseDomain> bool operator== (const iterator & x, const iterator & y) friend
Definition at line 567 of file UnionFind.h.
{
             return x.sds == y.sds && x.maskIter == y.maskIter;
         };
Field Documentation
template<typename SparseDomain> DisjointSet::iterator souffle::SparseDisjointSet< SparseDomain >::iterator::maskIter private
Definition at line 528 of file UnionFind.h.
Referenced by souffle::SparseDisjointSet< SparseDomain >::iterator::operator++(), and souffle::SparseDisjointSet< SparseDomain >::iterator::yield().
template<typename SparseDomain> SparseDisjointSet* souffle::SparseDisjointSet< SparseDomain >::iterator::sds private
Definition at line 524 of file UnionFind.h.
Referenced by souffle::SparseDisjointSet< SparseDomain >::iterator::yield().
The documentation for this class was generated from the following file:
UnionFind.h