souffle: souffle::AstUnaryFunctor Class Reference
souffle::AstUnaryFunctor Class Reference
Subclass of Argument that represents a unary function.
#include <AstArgument.h>
Public Member Functions
bool acceptsNumbers () const
Check if the argument of this functor is a number type.
bool acceptsSymbols () const
Check if the argument of this functor is a symbol type.
void apply (const AstNodeMapper &map) override
Mutates this node.
AstUnaryFunctor (UnaryOp fun, std::unique_ptr< AstArgument > o)
AstUnaryFunctor * clone () const override
Creates a clone.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
UnaryOp getFunction () const
AstArgument * getOperand () const
bool isNumerical () const
Check if the return value of this functor is a number type.
bool isSymbolic () const
Check if the return value of this functor is a symbol type.
void print (std::ostream &os) const override
Print argument to the given output stream.
~AstUnaryFunctor () override=default
Public Member Functions inherited from souffle::AstArgument
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
UnaryOp fun
std::unique_ptr< AstArgument > operand
Detailed Description
Subclass of Argument that represents a unary function.
Definition at line 278 of file AstArgument.h.
Constructor & Destructor Documentation
souffle::AstUnaryFunctor::AstUnaryFunctor (UnaryOp fun, std::unique_ptr< AstArgument > o) inline
Definition at line 285 of file AstArgument.h.
Referenced by clone().
 : fun(fun), operand(std::move(o)) {}
souffle::AstUnaryFunctor::~AstUnaryFunctor () override default
Member Function Documentation
bool souffle::AstUnaryFunctor::acceptsNumbers () const inline
Check if the argument of this functor is a number type.
Definition at line 308 of file AstArgument.h.
References fun, and souffle::unaryOpAcceptsNumbers().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return unaryOpAcceptsNumbers(fun);
     }
bool souffle::AstUnaryFunctor::acceptsSymbols () const inline
Check if the argument of this functor is a symbol type.
Definition at line 313 of file AstArgument.h.
References fun, and souffle::unaryOpAcceptsSymbols().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return unaryOpAcceptsSymbols(fun);
     }
void souffle::AstUnaryFunctor::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 333 of file AstArgument.h.
References map, and operand.
{
         operand = map(std::move(operand));
     }
AstUnaryFunctor* souffle::AstUnaryFunctor::clone () const inline override virtual
Creates a clone.
Implements souffle::AstArgument.
Definition at line 326 of file AstArgument.h.
References AstUnaryFunctor(), fun, souffle::AstNode::getSrcLoc(), and operand.
{
         auto res = new AstUnaryFunctor(fun, std::unique_ptr<AstArgument>(operand->clone()));
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstUnaryFunctor::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 346 of file AstArgument.h.
References fun, and operand.
{
         assert(nullptr != dynamic_cast<const AstUnaryFunctor*>(&node));
         const auto& other = static_cast<const AstUnaryFunctor&>(node);
         return fun == other.fun && *operand == *other.operand;
     }
std::vector<const AstNode*> souffle::AstUnaryFunctor::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Reimplemented from souffle::AstArgument.
Definition at line 338 of file AstArgument.h.
References souffle::AstArgument::getChildNodes(), and operand.
{
         auto res = AstArgument::getChildNodes();
         res.push_back(operand.get());
         return res;
     }
UnaryOp souffle::AstUnaryFunctor::getFunction () const inline
Definition at line 293 of file AstArgument.h.
References fun.
{
         return fun;
     }
AstArgument* souffle::AstUnaryFunctor::getOperand () const inline
Definition at line 289 of file AstArgument.h.
References operand.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), souffle::getConstTerms(), and souffle::getGroundedTerms().
{
         return operand.get();
     }
bool souffle::AstUnaryFunctor::isNumerical () const inline
Check if the return value of this functor is a number type.
Definition at line 298 of file AstArgument.h.
References fun, and souffle::isNumericUnaryOp().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return isNumericUnaryOp(fun);
     }
bool souffle::AstUnaryFunctor::isSymbolic () const inline
Check if the return value of this functor is a symbol type.
Definition at line 303 of file AstArgument.h.
References fun, and souffle::isSymbolicUnaryOp().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return isSymbolicUnaryOp(fun);
     }
void souffle::AstUnaryFunctor::print (std::ostream & os) const inline override virtual
Print argument to the given output stream.
Implements souffle::AstNode.
Definition at line 318 of file AstArgument.h.
References fun, souffle::getSymbolForUnaryOp(), and operand.
{
         os << getSymbolForUnaryOp(fun);
         os << "(";
         operand->print(os);
         os << ")";
     }
Field Documentation
UnaryOp souffle::AstUnaryFunctor::fun protected
Definition at line 280 of file AstArgument.h.
Referenced by acceptsNumbers(), acceptsSymbols(), clone(), equal(), getFunction(), isNumerical(), isSymbolic(), and print().
std::unique_ptr<AstArgument> souffle::AstUnaryFunctor::operand protected
Definition at line 282 of file AstArgument.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getOperand(), and print().
The documentation for this class was generated from the following file:
AstArgument.h