souffle: souffle::RamLookup Class Reference
souffle::RamLookup Class Reference
Record lookup.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamLookup * clone () const override
Create clone.
std::size_t getArity () const
Get Arity.
std::size_t getReferenceLevel () const
Get reference level.
std::size_t getReferencePosition () const
Get reference position.
void print (std::ostream &os, int tabpos) const override
Print.
RamLookup (std::unique_ptr< RamOperation > nested, std::size_t ref_level, std::size_t ref_pos, std::size_t arity)
Public Member Functions inherited from souffle::RamSearch
void addCondition (std::unique_ptr< RamCondition > c, const RamOperation &root) override
Add condition.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getDepth () const override
Get depth of query.
RamOperation * getNestedOperation () const
get nested operation
const RamOperation & getOperation () const
get nested operation
const std::string & getProfileText () const
get profile text
RamSearch (RamNodeType type, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
void addCondition (std::unique_ptr< RamCondition > c)
Add condition.
RamCondition * getCondition () const
Get condition.
size_t getLevel () const
Get level.
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type, size_t l)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::size_t arity
Arity of the unpacked tuple.
std::size_t refLevel
Level of the tuple containing record reference.
std::size_t refPos
Position of the tuple containing record reference.
Additional Inherited Members
Protected Attributes inherited from souffle::RamOperation
std::unique_ptr< RamCondition > condition
condition that is checked for each obtained tuple
size_t level
the nesting level of this operation
Detailed Description
Record lookup.
Definition at line 284 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamLookup::RamLookup (std::unique_ptr< RamOperation > nested, std::size_t ref_level, std::size_t ref_pos, std::size_t arity) inline
Definition at line 295 of file RamOperation.h.
Referenced by clone().
             : RamSearch(RN_Lookup, std::move(nested)), refLevel(ref_level), refPos(ref_pos), arity(arity) {}
Member Function Documentation
void souffle::RamLookup::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Reimplemented from souffle::RamSearch.
Definition at line 325 of file RamOperation.h.
References souffle::RamSearch::apply().
{
         RamSearch::apply(map);
     }
RamLookup* souffle::RamLookup::clone () const inline override virtual
Create clone.
Implements souffle::RamOperation.
Definition at line 318 of file RamOperation.h.
References arity, souffle::RamSearch::getNestedOperation(), RamLookup(), refLevel, and refPos.
{
         RamLookup* res = new RamLookup(
                 std::unique_ptr<RamOperation>(getNestedOperation()->clone()), refLevel, refPos, arity);
         return res;
     }
bool souffle::RamLookup::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamSearch.
Definition at line 331 of file RamOperation.h.
References souffle::RamSearch::equal(), getArity(), getReferenceLevel(), and getReferencePosition().
{
         assert(nullptr != dynamic_cast<const RamLookup*>(&node));
         const auto& other = static_cast<const RamLookup&>(node);
         return RamSearch::equal(other) && getReferencePosition() == other.getReferencePosition() &&
                getReferenceLevel() == other.getReferenceLevel() && getArity() == other.getArity();
     }
std::size_t souffle::RamLookup::getArity () const inline
Get Arity.
Definition at line 310 of file RamOperation.h.
References arity.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalOp().
{
         return arity;
     }
std::size_t souffle::RamLookup::getReferenceLevel () const inline
Get reference level.
Definition at line 300 of file RamOperation.h.
References refLevel.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalOp().
{
         return refLevel;
     }
std::size_t souffle::RamLookup::getReferencePosition () const inline
Get reference position.
Definition at line 305 of file RamOperation.h.
References refPos.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalOp().
{
         return refPos;
     }
void souffle::RamLookup::print (std::ostream & os, int tabpos) const override virtual
Print.
print search
Implements souffle::RamOperation.
Definition at line 162 of file RamOperation.cpp.
References souffle::RamOperation::condition, souffle::RamOperation::getCondition(), souffle::RamOperation::getLevel(), souffle::RamSearch::getNestedOperation(), souffle::RamOperation::print(), refLevel, refPos, and souffle::times().
{
     os << times('\t', tabpos);
     os << "UNPACK env(t" << refLevel << ", i" << refPos << ") INTO t" << getLevel();
     if (auto condition = getCondition()) {
         os << " WHERE ";
         condition->print(os);
     }
     os << " FOR \n";
     getNestedOperation()->print(os, tabpos + 1);
 }
Field Documentation
std::size_t souffle::RamLookup::arity private
Arity of the unpacked tuple.
Definition at line 292 of file RamOperation.h.
Referenced by clone(), and getArity().
std::size_t souffle::RamLookup::refLevel private
Level of the tuple containing record reference.
Definition at line 286 of file RamOperation.h.
Referenced by clone(), getReferenceLevel(), and print().
std::size_t souffle::RamLookup::refPos private
Position of the tuple containing record reference.
Definition at line 289 of file RamOperation.h.
Referenced by clone(), getReferencePosition(), and print().
The documentation for this class was generated from the following files:
RamOperation.h
RamOperation.cpp