souffle: souffle::Trie< 0u >::iterator_core< I > Class Template Reference
souffle::Trie< 0u >::iterator_core< I > Class Template Reference
The iterator core for this type of trie level.
#include <Trie.h>
Public Member Functions
bool inc ()
template<typename Tuple >
bool inc (Tuple &)
iterator_core (bool end=true)
template<typename Tuple >
iterator_core (bool end, Tuple &)
bool operator!= (const iterator_core &other) const
bool operator== (const iterator_core &other) const
void print (std::ostream &out) const
Private Attributes
bool end
Friends
std::ostream & operator<< (std::ostream &out, const iterator_core &iter)
Detailed Description
template<>
template<unsigned I = 0>
class souffle::Trie< 0u >::iterator_core< I >
The iterator core for this type of trie level.
Definition at line 2625 of file Trie.h.
Constructor & Destructor Documentation
template<unsigned I = 0> souffle::Trie< 0u >::iterator_core< I >::iterator_core (bool end = true) inline
Definition at line 2629 of file Trie.h.
 : end(end) {}
template<unsigned I = 0> template<typename Tuple > souffle::Trie< 0u >::iterator_core< I >::iterator_core (bool end, Tuple &) inline
Definition at line 2632 of file Trie.h.
 : end(end) {}
Member Function Documentation
template<unsigned I = 0> bool souffle::Trie< 0u >::iterator_core< I >::inc () inline
Definition at line 2634 of file Trie.h.
References souffle::Trie< Dim >::end().
                    {
             auto res = end;
             end = true;
             return res;
         }
template<unsigned I = 0> template<typename Tuple > bool souffle::Trie< 0u >::iterator_core< I >::inc (Tuple &) inline
Definition at line 2641 of file Trie.h.
References souffle::Trie< Dim >::iterator_core< I >::inc().
{
             return inc();
         }
template<unsigned I = 0> bool souffle::Trie< 0u >::iterator_core< I >::operator!= (const iterator_core & other) const inline
Definition at line 2649 of file Trie.h.
{
             return !(*this == other);
         }
template<unsigned I = 0> bool souffle::Trie< 0u >::iterator_core< I >::operator== (const iterator_core & other) const inline
Definition at line 2645 of file Trie.h.
References souffle::Trie< Dim >::end().
{
             return end && other.end;
         }
template<unsigned I = 0> void souffle::Trie< 0u >::iterator_core< I >::print (std::ostream & out) const inline
Definition at line 2654 of file Trie.h.
References souffle::Trie< Dim >::end().
{
             out << ((end) ? "end" : "single");
         }
Friends And Related Function Documentation
template<unsigned I = 0> std::ostream& operator<< (std::ostream & out, const iterator_core & iter) friend
Definition at line 2658 of file Trie.h.
{
             iter.print(out);
             return out;
         }
Field Documentation
template<unsigned I = 0> bool souffle::Trie< 0u >::iterator_core< I >::end private
Definition at line 2626 of file Trie.h.
The documentation for this class was generated from the following file:
Trie.h