souffle: souffle::profile Namespace Reference
souffle::profile Namespace Reference
Namespaces
html
Tools
Data Structures
class Atom
class Cell
class Cell< double >
class Cell< long >
class Cell< std::string >
class Cell< void >
class CellInterface
class Cli
class ConfigProcessor
Config entry processor.
class DataComparator
class EventProcessor
Abstract Class for EventProcessor.
class EventProcessorSingleton
Event Processor Singleton.
class FrequencyAtomProcessor
Frequency Atom Processor.
class HtmlString
class InputReader
class Iteration
class NonRecursiveRelationNumberProcessor
Non-Recursive Relation Number Profile Event Processor.
class NonRecursiveRelationTimingProcessor
Non-Recursive Relation Number Profile Event Processor.
class NonRecursiveRuleNumberProcessor
Non-Recursive Rule Number Profile Event Processor.
class NonRecursiveRuleTimingProcessor
Non-Recursive Rule Timing Profile Event Processor.
class OutputProcessor
class ProgramResourceUtilisationProcessor
Program Resource Utilisation Event Processor.
class ProgramRun
class ProgramRuntimeProcessor
Program Run Event Processor.
class ProgramTimepointProcessor
Program Run Event Processor.
class Reader
class RecursiveRelationCopyTimingProcessor
Recursive Relation Copy Timing Profile Event Processor.
class RecursiveRelationNumberProcessor
Recursive Relation Timing Profile Event Processor.
class RecursiveRelationTimingProcessor
Recursive Relation Timing Profile Event Processor.
class RecursiveRuleNumberProcessor
Recursive Rule Number Profile Event Processor.
class RecursiveRuleTimingProcessor
Recursive Rule Timing Profile Event Processor.
class Relation
class RelationIOTimingProcessor
Recursive Relation Copy Timing Profile Event Processor.
class Row
class Rule
class Table
class TextProcessor
Text entry processor.
class Tui
Functions
comma (firstRow)
if (ver_table.rows.size() > 0)
outfile<< "\n ";outfile
<< '"' << row[6]-> toString (0)<< R"_("
Variables
souffle::profile::ConfigProcessor configProcessor
else
souffle::profile::FrequencyAtomProcessor frequencyAtomProcessor
class souffle::profile::Tui n
souffle::profile::NonRecursiveRelationNumberProcessor nonRecursiveRelationNumberProcessor
souffle::profile::NonRecursiveRelationTimingProcessor nonRecursiveRelationTimingProcessor
souffle::profile::NonRecursiveRuleNumberProcessor nonRecursiveRuleNumberProcessor
souffle::profile::NonRecursiveRuleTimingProcessor nonRecursiveRuleTimingProcessor
class souffle::profile::Tui outfile
outfile<< R"_("rul": {)_";firstRow=true;for(auto
&_row:rul_table_state.getRows()){Row
row=*_row;std::vector
< std::string > part = Tools::split(row[6]->toString(0), ".")
souffle::profile::ProgramResourceUtilisationProcessor programResourceUtilisationProcessor
souffle::profile::ProgramRuntimeProcessor programRuntimeProcessor
souffle::profile::ProgramTimepointProcessor programTimepointProcessor
souffle::profile::RecursiveRelationCopyTimingProcessor recursiveRelationCopyTimingProcessor
souffle::profile::RecursiveRelationNumberProcessor recursiveRelationNumberProcessor
souffle::profile::RecursiveRelationTimingProcessor recursiveRelationTimingProcessor
souffle::profile::RecursiveRuleNumberProcessor recursiveRuleNumberProcessor
souffle::profile::RecursiveRuleTimingProcessor recursiveRuleTimingProcessor
souffle::profile::RelationIOTimingProcessor relationIOTimingProcessor
std::string src
std::string strRel = "R" + part[0].substr(1)
souffle::profile::TextProcessor textProcessor
Table ver_table = out.getVersions(strRel, row[6]->toString(0))
Function Documentation
souffle::profile::comma (firstRow)
Referenced by souffle::profile::Tui::outputJson(), and toString().
souffle::profile::if (ver_table.rows. size(), 0)
Definition at line 362 of file Tui.h.
References souffle::profile::Table::rows, and toString().
{
                 if (ver_table.rows[0]->cells[9] != nullptr) {
                     src = (*ver_table.rows[0])[9]->toString(0);
                 } else {
                     src = "-";
                 }
             } else {
outfile<< "\n "; outfile << '"' << row[6]-> souffle::profile::toString (0)
Definition at line 374 of file Tui.h.
References souffle::profile::Tools::cleanJsonOut(), and comma().
Referenced by if(), souffle::profile::Tui::outputJson(), verAtoms(), verGraph(), and verRul().
                                                           : [)_";
             outfile << '"' << Tools::cleanJsonOut(row[5]->toString(0)) << R"_(", )_";
             outfile << '"' << Tools::cleanJsonOut(row[6]->toString(0)) << R"_(", )_";
             outfile << row[0]->getDoubVal() << ", ";
             outfile << row[1]->getDoubVal() << ", ";
             outfile << row[2]->getDoubVal() << ", ";
             outfile << row[3]->getDoubVal() << ", ";
             outfile << row[4]->getLongVal() << ", ";
             outfile << '"' << src << R"_(", )_";
             outfile << "[";
             bool has_ver = false;
             bool firstCol = true;
             for (auto& _ver_row : ver_table.getRows()) {
                 comma(firstCol);
                 has_ver = true;
                 Row ver_row = *_ver_row;
                 outfile << '[';
                 outfile << '"' << Tools::cleanJsonOut(ver_row[5]->toString(0)) << R"_(", )_";
                 outfile << '"' << Tools::cleanJsonOut(ver_row[6]->toString(0)) << R"_(", )_";
                 outfile << ver_row[0]->getDoubVal() << ", ";
                 outfile << ver_row[1]->getDoubVal() << ", ";
                 outfile << ver_row[2]->getDoubVal() << ", ";
                 outfile << ver_row[3]->getDoubVal() << ", ";
                 outfile << ver_row[4]->getLongVal() << ", ";
                 outfile << '"' << src << R"_(", )_";
                 outfile << ver_row[8]->getLongVal();
                 outfile << ']';
             }
             outfile << "], ";
             if (row[6]->toString(0).at(0) != 'C') {
                 outfile << "{}, {}]";
Variable Documentation
souffle::profile::ConfigProcessor souffle::profile::configProcessor
souffle::profile::else
Initial value:
{
                src = row[10]->toString(-1)
Definition at line 368 of file Tui.h.
souffle::profile::FrequencyAtomProcessor souffle::profile::frequencyAtomProcessor
class souffle::profile::Tui souffle::profile::n
souffle::profile::NonRecursiveRelationNumberProcessor souffle::profile::nonRecursiveRelationNumberProcessor
souffle::profile::NonRecursiveRelationTimingProcessor souffle::profile::nonRecursiveRelationTimingProcessor
souffle::profile::NonRecursiveRuleNumberProcessor souffle::profile::nonRecursiveRuleNumberProcessor
souffle::profile::NonRecursiveRuleTimingProcessor souffle::profile::nonRecursiveRuleTimingProcessor
class souffle::profile::Tui souffle::profile::outfile
Referenced by souffle::profile::Tui::outputJson().
outfile<< R"_("rul": {)_"; firstRow = true; for (auto& _row : rul_table_state.getRows()) { Row row = *_row; std::vector<std::string> souffle::profile::part = Tools::split(row[6]->toString(0), ".")
Definition at line 357 of file Tui.h.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::collectChunks().
souffle::profile::ProgramResourceUtilisationProcessor souffle::profile::programResourceUtilisationProcessor
souffle::profile::ProgramRuntimeProcessor souffle::profile::programRuntimeProcessor
souffle::profile::ProgramTimepointProcessor souffle::profile::programTimepointProcessor
souffle::profile::RecursiveRelationCopyTimingProcessor souffle::profile::recursiveRelationCopyTimingProcessor
souffle::profile::RecursiveRelationNumberProcessor souffle::profile::recursiveRelationNumberProcessor
souffle::profile::RecursiveRelationTimingProcessor souffle::profile::recursiveRelationTimingProcessor
souffle::profile::RecursiveRuleNumberProcessor souffle::profile::recursiveRuleNumberProcessor
souffle::profile::RecursiveRuleTimingProcessor souffle::profile::recursiveRuleTimingProcessor
souffle::profile::RelationIOTimingProcessor souffle::profile::relationIOTimingProcessor
std::string souffle::profile::src
Definition at line 361 of file Tui.h.
Referenced by souffle::Interpreter::evalStmt().
std::string souffle::profile::strRel = "R" + part[0].substr(1)
Definition at line 358 of file Tui.h.
Referenced by souffle::profile::OutputProcessor::getAtomTable(), and souffle::profile::OutputProcessor::getSubrulTable().
souffle::profile::TextProcessor souffle::profile::textProcessor
Table souffle::profile::ver_table = out.getVersions(strRel, row[6]->toString(0))
Definition at line 359 of file Tui.h.